// V3-32 test material, generated by code (not by hand): client repositories the compatibility check meets — a Wizard
// system (compiled from a module plan like a real build), Vite + React projects with a pnpm, npm or yarn lockfile, the
// same without a lockfile, a PHP / 1С-Битрикс site, a pnpm monorepo with a web app, a mobile app and a library, plus a
// few edge cases (no tests, two lockfiles, Angular, Flutter, 1С, Python). Each fixture also says what the sandbox would
// report for it, so a fake sandbox can answer without running anything.
// As a script: `node packages/agents/test/repo-fixtures.ts <dir>` writes every fixture out as a directory.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compilePlan } from "@wizard/modules";
import { DEFAULT_REGISTRY, finalizePlan } from "../src/planner/index.js";
import { type RepoSnapshot, snapshotOf } from "../src/repo/snapshot.js";
import { B2_SCENARIOS } from "./build-v2-scenarios.js";

export type FixtureFiles = Record<string, string | { link: string } | { submodule: string }>;

export interface RepoFixture {
  name: string;
  files: FixtureFiles;
  /** What a sandbox reports for install / build / test of this repository (ms and success). */
  sandbox: {
    install?: { ok: boolean; ms: number };
    build?: { ok: boolean; ms: number };
    test?: { ok: boolean; ms: number };
  };
}

const json = (v: unknown) => `${JSON.stringify(v, null, 2)}\n`;

function vitePackage(name: string, o: { test?: boolean; deps?: Record<string, string> } = {}) {
  return json({
    name,
    private: true,
    version: "0.1.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "tsc -b && vite build",
      ...(o.test === false ? {} : { test: "vitest run" }),
    },
    dependencies: { react: "^19.1.0", "react-dom": "^19.1.0", ...o.deps },
    devDependencies: {
      "@vitejs/plugin-react": "^5.0.0",
      typescript: "^5.9.0",
      vite: "^7.1.0",
      ...(o.test === false ? {} : { vitest: "^3.2.0", "@testing-library/react": "^16.3.0" }),
    },
  });
}

const APP = `import { useState } from "react";

export function App() {
  const [count, setCount] = useState(0);
  return (
    <main>
      <h1>Пекарня «Колос»</h1>
      <button type="button" onClick={() => setCount(count + 1)}>
        В корзине: {count}
      </button>
    </main>
  );
}
`;

const APP_TEST = `import { render, screen } from "@testing-library/react";
import { expect, test } from "vitest";
import { App } from "./App";

test("shows the cart", () => {
  render(<App />);
  expect(screen.getByRole("button").textContent).toContain("В корзине");
});
`;

function viteSources(prefix = ""): Record<string, string> {
  return {
    [`${prefix}index.html`]:
      '<!doctype html>\n<div id="root"></div>\n<script type="module" src="/src/main.tsx"></script>\n',
    [`${prefix}src/main.tsx`]:
      'import { createRoot } from "react-dom/client";\nimport { App } from "./App";\n\ncreateRoot(document.getElementById("root") as HTMLElement).render(<App />);\n',
    [`${prefix}src/App.tsx`]: APP,
    [`${prefix}src/App.test.tsx`]: APP_TEST,
    [`${prefix}vite.config.ts`]:
      'import react from "@vitejs/plugin-react";\nimport { defineConfig } from "vite";\n\nexport default defineConfig({ plugins: [react()] });\n',
    [`${prefix}tsconfig.json`]: json({
      compilerOptions: { jsx: "react-jsx", strict: true, module: "ESNext" },
    }),
  };
}

const LOCK = {
  pnpm: (name: string) =>
    `lockfileVersion: '9.0'\n\nsettings:\n  autoInstallPeers: true\n\nimporters:\n\n  .:\n    dependencies:\n      react:\n        specifier: ^19.1.0\n        version: 19.1.0\n# ${name}\n`,
  npm: (name: string) =>
    json({
      name,
      version: "0.1.0",
      lockfileVersion: 3,
      requires: true,
      packages: { "": { name, version: "0.1.0" } },
    }),
  yarn: (name: string) =>
    `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.\n# yarn lockfile v1\n# ${name}\n\nreact@^19.1.0:\n  version "19.1.0"\n`,
} as const;

const README = (title: string) => `# ${title}\n\nСайт пекарни: каталог, корзина, заказ.\n`;

/** A Wizard system repository: the compiled dental clinic of the module catalog in the V3-30 layout. */
function wizardSystemFiles(): FixtureFiles {
  const sc = B2_SCENARIOS[0];
  if (!sc) throw new Error("no B2 scenario");
  const r = compilePlan(finalizePlan(sc.plan, DEFAULT_REGISTRY), DEFAULT_REGISTRY);
  if (!r.ok) throw new Error(JSON.stringify(r.errors));
  const files: FixtureFiles = {
    "spec/appspec.json": json(r.spec),
    "brief/brief.json": json({ goals: [], audience: "Пациенты клиники", scenarios: [] }),
    "tests/scenarios.json": json([]),
    "AGENTS.md":
      "# Стоматология\n\nЭто полный исходник системы «Стоматология», собранной в Wizard. Wizard обновляет репозиторий при каждой ревизии.\n\n## Как устроен репозиторий\n",
    "README.md": "# Стоматология\n",
  };
  for (const [path, content] of Object.entries(r.files)) files[path] = content;
  return files;
}

/** Every fixture of the suite. */
export function repoFixtures(): RepoFixture[] {
  const ok = {
    install: { ok: true, ms: 45_000 },
    build: { ok: true, ms: 30_000 },
    test: { ok: true, ms: 20_000 },
  };
  const vite = (pm: "pnpm" | "npm" | "yarn"): RepoFixture => {
    const name = `bakery-${pm}`;
    const lockName = pm === "pnpm" ? "pnpm-lock.yaml" : pm === "npm" ? "package-lock.json" : "yarn.lock";
    return {
      name: `vite-react-${pm}`,
      files: {
        "package.json": vitePackage(name),
        [lockName]: LOCK[pm](name),
        "README.md": README(name),
        ...viteSources(),
      },
      sandbox: ok,
    };
  };
  const mono: RepoFixture = {
    name: "monorepo",
    files: {
      "package.json": json({
        name: "bakery-mono",
        private: true,
        scripts: {
          build: "pnpm -r --filter ./apps/web --filter ./packages/ui run build",
          test: "pnpm -r run test",
        },
        packageManager: "pnpm@10.33.0",
      }),
      "pnpm-workspace.yaml": "packages:\n  - 'apps/*'\n  - 'packages/*'\n",
      "pnpm-lock.yaml": LOCK.pnpm("bakery-mono"),
      "apps/web/package.json": vitePackage("@bakery/web", { deps: { "@bakery/ui": "workspace:*" } }),
      ...viteSources("apps/web/"),
      "apps/mobile/package.json": json({
        name: "@bakery/mobile",
        private: true,
        scripts: { start: "expo start", test: "jest" },
        dependencies: { expo: "~54.0.0", "react-native": "0.81.0", react: "^19.1.0" },
      }),
      "apps/mobile/android/app/src/main/AndroidManifest.xml": '<manifest package="ru.kolos"/>\n',
      "apps/mobile/App.tsx":
        'import { Text } from "react-native";\nexport default function App() {\n  return <Text>Колос</Text>;\n}\n',
      "packages/ui/package.json": json({
        name: "@bakery/ui",
        private: true,
        scripts: { build: "tsc -p .", test: "vitest run" },
        devDependencies: { typescript: "^5.9.0", vitest: "^3.2.0" },
      }),
      "packages/ui/src/index.ts": 'export const brand = "Колос";\n',
      "README.md": README("Колос"),
    },
    sandbox: {
      install: { ok: true, ms: 120_000 },
      build: { ok: true, ms: 90_000 },
      test: { ok: true, ms: 60_000 },
    },
  };
  const noLock = vite("npm");
  delete (noLock.files as Record<string, unknown>)["package-lock.json"];
  return [
    { name: "wizard-system", files: wizardSystemFiles(), sandbox: {} },
    vite("pnpm"),
    vite("npm"),
    vite("yarn"),
    { ...noLock, name: "vite-react-no-lockfile" },
    {
      name: "php-bitrix",
      files: {
        "index.php":
          '<?php\nrequire($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");\n$APPLICATION->SetTitle("Главная");\n',
        "bitrix/.settings.php": "<?php\nreturn [];\n",
        "local/php_interface/init.php": "<?php\n// обработчики событий\n",
        "local/templates/main/header.php": '<!doctype html>\n<html lang="ru">\n',
        "local/templates/main/script.js": "document.addEventListener('DOMContentLoaded', () => {});\n",
        "package.json": json({
          name: "bitrix-site-assets",
          scripts: { build: "gulp" },
          devDependencies: { gulp: "^5.0.0" },
        }),
        "composer.json": json({ require: { php: ">=8.1" } }),
      },
      sandbox: {},
    },
    mono,
    // Edge cases.
    {
      ...vite("pnpm"),
      name: "vite-react-no-tests",
      files: { ...vite("pnpm").files, "package.json": vitePackage("bakery", { test: false }) },
    },
    {
      ...vite("pnpm"),
      name: "two-lockfiles",
      files: { ...vite("pnpm").files, "package-lock.json": LOCK.npm("bakery") },
    },
    {
      name: "angular",
      files: {
        "package.json": json({
          name: "shop",
          scripts: { build: "ng build", test: "ng test" },
          dependencies: { "@angular/core": "^20.0.0" },
        }),
        "package-lock.json": LOCK.npm("shop"),
        "src/main.ts": "console.log('shop');\n",
      },
      sandbox: ok,
    },
    {
      name: "flutter",
      files: {
        "pubspec.yaml": "name: kolos\n",
        "lib/main.dart": "void main() {}\n",
        "android/app/src/main/AndroidManifest.xml": "<manifest/>\n",
      },
      sandbox: {},
    },
    {
      name: "onec",
      files: {
        "src/Configuration.xml": "<Configuration/>\n",
        "src/CommonModules/Общий/Ext/Module.bsl": "Процедура Тест()\nКонецПроцедуры\n",
      },
      sandbox: {},
    },
    {
      name: "python",
      files: { "pyproject.toml": "[project]\nname = 'kolos'\n", "app/main.py": "print('Колос')\n" },
      sandbox: {},
    },
    {
      ...vite("npm"),
      name: "vite-react-failing-tests",
      sandbox: {
        install: { ok: true, ms: 40_000 },
        build: { ok: true, ms: 20_000 },
        test: { ok: false, ms: 10_000 },
      },
    },
    {
      ...vite("npm"),
      name: "vite-react-slow",
      sandbox: {
        install: { ok: true, ms: 300_000 },
        build: { ok: true, ms: 250_000 },
        test: { ok: true, ms: 100_000 },
      },
    },
  ];
}

export const fixture = (name: string): RepoFixture => {
  const f = repoFixtures().find((x) => x.name === name);
  if (!f) throw new Error(`no repo fixture ${name}`);
  return f;
};

export const snapshotOfFixture = (name: string): RepoSnapshot => snapshotOf(fixture(name).files);

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = process.argv[2];
  if (!out) throw new Error("usage: node packages/agents/test/repo-fixtures.ts <dir>");
  for (const f of repoFixtures())
    for (const [path, v] of Object.entries(f.files)) {
      if (typeof v !== "string") continue;
      const file = join(out, f.name, path);
      mkdirSync(dirname(file), { recursive: true });
      writeFileSync(file, v);
    }
  process.stdout.write(`wrote ${repoFixtures().length} repositories to ${out}\n`);
}
