// V3-32 acceptance 1 (D77_v3 (4)): the compatibility check — JS/TS web project with a lockfile, build and tests in the
// sandbox within 10 minutes — and the owner's report «что сможем / не сможем» with the reason of each «не сможем».
// Fixtures are generated by code (repo-fixtures.ts); the sandbox is a fake that runs nothing; a Wizard system is checked
// by our real G0 and static G2 in process.
import { describe, expect, test } from "vitest";
import {
  agentAllowed,
  type CompatReport,
  profileRepo,
  runCompatCheck,
  SANDBOX_LIMIT_MS,
  sandboxPlan,
} from "../src/repo/index.js";
import { fixture, repoFixtures, snapshotOfFixture } from "./repo-fixtures.js";
import { FakeSandbox } from "./repo-helpers.js";

async function check(name: string, sandbox: "fake" | "none" = "fake") {
  const fx = fixture(name);
  const sb = sandbox === "fake" ? new FakeSandbox(fx.sandbox) : null;
  const r = await runCompatCheck(snapshotOfFixture(name), sb);
  return { ...r, sb };
}

const whyOf = (r: CompatReport, what: RegExp) => r.cannot.find((c) => what.test(c.what_ru))?.why_ru ?? "";
const text = (r: CompatReport) => JSON.stringify([r.summary_ru, r.can, r.cannot]);

describe("fixtures are generated by code", () => {
  test("the suite: every kind the acceptance names, distinct names", () => {
    const names = repoFixtures().map((f) => f.name);
    expect(new Set(names).size).toBe(names.length);
    for (const n of [
      "wizard-system",
      "vite-react-pnpm",
      "vite-react-npm",
      "vite-react-yarn",
      "vite-react-no-lockfile",
      "php-bitrix",
      "monorepo",
    ])
      expect(names).toContain(n);
  });
});

describe("compatibility report «что сможем / не сможем»", () => {
  test("a Wizard system: compatible, checked by G0 and the static G2 in process (nothing of the client's runs)", async () => {
    const r = await check("wizard-system", "none");
    expect(r.profile.kind).toBe("wizard_system");
    expect(r.report.verdict).toBe("compatible");
    expect(r.report.sandbox?.status).toBe("passed");
    expect(r.report.sandbox?.steps.map((s) => s.command)).toEqual([
      "G0 — сборка и типы",
      "G2 — права, ПДн и секреты",
    ]);
    expect(r.report.can[0]).toMatch(/^Дорабатывать систему Wizard по задаче: интерфейс ui\/\*\*/);
    expect(whyOf(r.report, /бриф/)).toMatch(/их пишет Wizard/);
    expect(r.report.rules).toEqual(["AGENTS.md"]);
    expect(agentAllowed(r.report)).toBe(true);
  }, 120_000);

  for (const [pm, install, lock] of [
    ["pnpm", "pnpm install --frozen-lockfile", "pnpm-lock.yaml"],
    ["npm", "npm ci", "package-lock.json"],
    ["yarn", "yarn install --frozen-lockfile", "yarn.lock"],
  ] as const)
    test(`Vite + React with ${lock}: compatible; install by the lockfile, build and tests in the sandbox ≤ 10 min`, async () => {
      const r = await check(`vite-react-${pm}`);
      expect(r.profile).toMatchObject({
        kind: "js_web",
        packageManager: pm,
        lockfile: lock,
        typescript: true,
      });
      expect(r.report.verdict).toBe("compatible");
      expect(r.report.stack.frameworks).toEqual(["Vite", "React"]);
      expect(r.report.sandbox).toMatchObject({ status: "passed", totalMs: 95_000 });
      expect(r.report.sandbox?.steps.map((s) => s.command)).toEqual([
        install,
        `${pm} run build`,
        pm === "npm" ? "npm test" : `${pm} run test`,
      ]);
      expect(r.report.can).toEqual([
        "Дорабатывать код по задаче: Vite и React на TypeScript",
        `Ставить зависимости (${install}) по lockfile ${lock}, собирать и прогонять тесты репозитория в песочнице — не дольше 10 минут`,
        "Работать на этапе агента без сети, проверять правку техревью и открывать черновой PR в ветке wizard/…",
        "Предложить правила для агентов (AGENTS.md) отдельным черновым PR — в репозитории нет AGENTS.md, CLAUDE.md и CONTRIBUTING",
      ]);
      // Network only for the install; build and tests ran without it.
      expect(r.sb?.runs.map((x) => [x.phase, x.network])).toEqual([
        ["install", "registry"],
        ["build", "none"],
        ["test", "none"],
      ]);
      expect(whyOf(r.report, /Мержить PR/)).toBe(
        "PR черновой: мержит только человек, деплой — вашими средствами",
      );
      expect(agentAllowed(r.report)).toBe(true);
    });

  test("no lockfile: incompatible, the reason names the lockfiles; nothing runs", async () => {
    const r = await check("vite-react-no-lockfile");
    expect(r.report.verdict).toBe("incompatible");
    expect(r.report.can).toEqual([]);
    expect(whyOf(r.report, /Устанавливать зависимости/)).toMatch(
      /^нет lockfile \(pnpm-lock\.yaml, package-lock\.json или yarn\.lock\)/,
    );
    expect(r.sb?.opened).toBe(0);
    expect(agentAllowed(r.report)).toBe(false);
  });

  test("PHP / 1С-Битрикс: incompatible, «Запросы на развитие» or «под ключ»", async () => {
    const r = await check("php-bitrix");
    expect(r.profile).toMatchObject({ kind: "bitrix", stackRu: "PHP (1С-Битрикс)" });
    expect(r.report.verdict).toBe("incompatible");
    expect(whyOf(r.report, /Дорабатывать этот репозиторий/)).toBe(
      "PHP (1С-Битрикс) пока не дорабатываем: агент работает с системами Wizard и веб-проектами на JS/TS. Записали в «Запросы на развитие»; доработку можно заказать «под ключ»",
    );
    expect(r.report.developmentRequest).toEqual({
      category: "other",
      quote: "Доработка репозитория на PHP (1С-Битрикс)",
    });
    expect(r.sb?.opened).toBe(0);
  });

  test("a pnpm monorepo: partial — the web app and the library yes, the mobile app no (a development request)", async () => {
    const r = await check("monorepo");
    expect(r.profile.kind).toBe("js_monorepo");
    expect(r.profile.workspaces.map((w) => [w.path, w.kind])).toEqual([
      ["apps/mobile", "mobile"],
      ["apps/web", "web"],
      ["packages/ui", "library"],
    ]);
    expect(r.report.verdict).toBe("partial");
    expect(r.report.can[0]).toBe(
      "Дорабатывать веб-пакеты монорепозитория: apps/web (Vite и React) на TypeScript",
    );
    expect(whyOf(r.report, /apps\/mobile/)).toMatch(/мобильные приложения пока не дорабатываем/);
    expect(r.report.cannot.find((c) => /apps\/mobile/.test(c.what_ru))?.what_ru).toBe(
      "Пакет apps/mobile (Expo (React Native))",
    );
    expect(r.report.developmentRequest?.category).toBe("mobile");
    expect(r.report.stack.monorepo).toBe(true);
    expect(r.report.sandbox?.steps.map((s) => s.command)).toEqual([
      "pnpm install --frozen-lockfile",
      "pnpm run build",
      "pnpm run test",
    ]);
    expect(agentAllowed(r.report)).toBe(true);
  });

  test("edge cases: no tests (partial), two lockfiles, Angular, Flutter, 1С, Python (incompatible)", async () => {
    const noTests = await check("vite-react-no-tests");
    expect(noTests.report.verdict).toBe("partial");
    expect(whyOf(noTests.report, /тесты/)).toMatch(/нет скрипта test/);
    expect(noTests.report.sandbox?.steps.map((s) => s.step)).toEqual(["install", "build"]);
    const two = await check("two-lockfiles");
    expect(two.report.verdict).toBe("incompatible");
    expect(whyOf(two.report, /зависимости/)).toMatch(
      /несколько lockfile \(pnpm-lock\.yaml, package-lock\.json\)/,
    );
    expect(whyOf((await check("angular")).report, /проект/)).toMatch(/^Angular пока не поддерживаем/);
    const flutter = await check("flutter");
    expect(flutter.profile.kind).toBe("mobile");
    expect(flutter.report.developmentRequest?.category).toBe("mobile");
    expect(text((await check("onec")).report)).toMatch(/1С пока не дорабатываем/);
    expect(whyOf((await check("python")).report, /репозиторий/)).toMatch(
      /стек Python — не веб-проект на JS\/TS/,
    );
  });

  test("the sandbox decides: failing tests before any change, over 10 minutes, no sandbox on the stand", async () => {
    const failing = await check("vite-react-failing-tests");
    expect(failing.report.verdict).toBe("incompatible");
    expect(whyOf(failing.report, /тестами/)).toMatch(
      /^тесты репозитория не проходят ещё до правок \(npm test\)/,
    );
    const slow = await check("vite-react-slow");
    expect(slow.report.verdict).toBe("incompatible");
    expect(slow.report.sandbox?.status).toBe("timeout");
    expect(slow.report.sandbox?.totalMs).toBeLessThanOrEqual(SANDBOX_LIMIT_MS);
    expect(whyOf(slow.report, /сборкой и тестами/)).toMatch(/дольше 10 минут/);
    const none = await check("vite-react-pnpm", "none");
    expect(none.report.verdict).toBe("unchecked");
    expect(agentAllowed(none.report)).toBe(false);
    expect(whyOf(none.report, /Подтвердить/)).toMatch(/песочница/);
  });

  test("the blocking reason: why the agent takes no tasks (null when it does)", async () => {
    expect((await check("vite-react-pnpm")).report.blocking_ru).toBeNull();
    expect((await check("monorepo")).report.blocking_ru).toBeNull();
    expect((await check("vite-react-no-lockfile")).report.blocking_ru).toMatch(/^нет lockfile/);
    expect((await check("php-bitrix")).report.blocking_ru).toMatch(
      /^PHP \(1С-Битрикс\) пока не дорабатываем/,
    );
    expect((await check("vite-react-pnpm", "none")).report.blocking_ru).toMatch(/песочница/);
  });

  test("yarn Berry installs --immutable; a monorepo without root scripts runs every package's", () => {
    const files = { ...fixture("vite-react-yarn").files, ".yarnrc.yml": "nodeLinker: node-modules\n" };
    const p = profileRepo(
      new Map([
        ...snapshotOfFixture("vite-react-yarn"),
        [
          ".yarnrc.yml",
          { path: ".yarnrc.yml", mode: "100644", size: 1, text: files[".yarnrc.yml"] as string },
        ],
      ]),
    );
    expect(sandboxPlan(p)?.install?.label).toBe("yarn install --immutable");
    const mono = profileRepo(snapshotOfFixture("monorepo"));
    const bare = { ...mono, scripts: { build: false, test: false } };
    expect(sandboxPlan(bare)?.build?.label).toBe("pnpm -r --if-present run build");
  });
});
