// Runtime functions of «Интернет-магазин» (V3-23; sources generated from the parameters, sdk.md):
// - shopPlaceOrder (public mutation of the checkout): an order from the cart — prices, the stock and the delivery price
//   are the server's; the stock is written off in the same serializable transaction (two concurrent orders of the last
//   item cannot both pass: one retries and is refused); the order gets its number and keeps the buyer's secret (token);
// - shopOrder (public query of the order page): the order by its id and the buyer's secret — goods, sums, status,
//   delivery; never the buyer's contacts;
// - shopCdekOptions (public action, СДЭК): the city → pickup points and the price of the parcel by the СДЭК client of
//   functions/integrations/cdek (the passport's mock until the key passes its check), kept as a quote for 30 minutes;
//   shopCartWeight and shopSaveQuote are its internal steps;
// - shopReturnStock (workflow of a cancelled order): the goods go back to the stock once;
// - shopOrderPaid (workflow of a paid order): an order paid after its cancel takes its goods off the stock again.
import type { GenContext } from "../types.js";
import {
  DELIVERY_METHODS,
  type DeliveryMethod,
  ORDER_STATUSES,
  SOLD_STATUSES,
  shopOptions,
} from "./compile.js";

export const PLACE_ORDER_FILE = "functions/shop/placeOrder.ts";
export const ORDER_FILE = "functions/shop/order.ts";
export const CDEK_OPTIONS_FILE = "functions/shop/cdekOptions.ts";
export const CART_WEIGHT_FILE = "functions/shop/cartWeight.ts";
export const SAVE_QUOTE_FILE = "functions/shop/saveQuote.ts";
export const RETURN_STOCK_FILE = "functions/shop/returnStock.ts";
export const ORDER_PAID_FILE = "functions/shop/orderPaid.ts";

/** СДЭК tariff of the quote: «Посылка склад-склад» (the parcel to a pickup point). */
export const CDEK_TARIFF = 136;
/** Minutes a СДЭК quote stays valid for the checkout. */
export const QUOTE_MINUTES = 30;

const lit = (v: unknown) => JSON.stringify(v);

const HELPERS = `type Row = Record<string, unknown>;
/** Money in kopecks (sums are added in whole kopecks). */
const kop = (v: unknown): number => Math.round(Number(v ?? 0) * 100);
const text = (v: unknown): string | null => (typeof v === "string" && v.trim() !== "" ? v.trim() : null);
`;

const linesArg = `v.array(v.object({ product: v.id("product"), qty: v.int({ min: 1, max: 99 }) }), { max: 50 })`;

export function placeOrderSource(ctx: GenContext): string {
  const o = shopOptions(ctx.params);
  const has = (d: DeliveryMethod) => o.delivery.includes(d);
  const methods = o.delivery.map(lit).join(", ");
  return `// Generated by the module «Интернет-магазин» (V3-23): an order from the cart of the site. The buyer sends only the
// goods, their quantities, the delivery he chose and his contacts; prices, the stock and the delivery price are the
// server's. The stock is written off in this transaction (serializable: concurrent orders of the last item cannot both
// pass). The order keeps the buyer's secret (made by his browser): it opens the order's page and its payment.
import { mutation, v } from "@wizard/sdk";

${HELPERS}const ONLINE = ${o.online};
${o.online ? `const RESERVE_MINUTES = ${o.reserveMinutes};\n` : ""}${has("courier") ? `const COURIER_PRICE = ${o.courierPrice};\n` : ""}${has("cdek") ? `const PARCEL_WEIGHT = ${o.parcelWeight};\n` : ""}
interface Line {
  product: string;
  name: string;
  qty: number;
  price: number;
  sum: number;
  stock: number;
  weight: number;
}
${
  has("cdek")
    ? `
/** Pickup points of a quote: [{code, address}] as shopCdekOptions kept them. */
function quotePoints(v: unknown): { code: string; address: string }[] {
  try {
    const list = JSON.parse(typeof v === "string" ? v : "[]") as unknown;
    return Array.isArray(list)
      ? list
          .map((x) => x as Row)
          .filter((x) => typeof x.code === "string" && typeof x.address === "string")
          .map((x) => ({ code: String(x.code), address: String(x.address) }))
      : [];
  } catch {
    return [];
  }
}
`
    : ""
}
export default mutation({
  args: {
    lines: ${linesArg},
    delivery: v.enum(${methods}),${has("pickup") ? `\n    pickupPoint: v.optional(v.id("pickup_point")),` : ""}${
      has("cdek")
        ? `\n    quote: v.optional(v.id("delivery_quote")),\n    cdekPoint: v.optional(v.string({ min: 1, max: 40 })),`
        : ""
    }${has("courier") ? `\n    address: v.optional(v.string({ max: 300 })),` : ""}
    name: v.string({ min: 1, max: 120 }),
    phone: v.phone(),
    email: v.optional(v.email()),
    comment: v.optional(v.string({ max: 1000 })),
    // The buyer's secret of the order: the page makes it in the browser (crypto.getRandomValues) and keeps it.
    token: v.string({ min: 32, max: 64, pattern: /^[A-Za-z0-9_-]{32,64}$/ }),
  },
  handler: async (ctx, args) => {
    const wanted = new Map<string, number>();
    for (const l of args.lines) wanted.set(l.product, (wanted.get(l.product) ?? 0) + l.qty);
    if (wanted.size === 0) throw ctx.error("EMPTY_CART", { message: "Корзина пуста — добавьте товары" });
    // +7XXXXXXXXXX of the stored phone (8… and 10 digits of a Russian number too).
    const raw = args.phone.replace(/\\D/g, "");
    const phone = "+" + (raw.length === 10 ? "7" + raw : raw.length === 11 && raw.startsWith("8") ? "7" + raw.slice(1) : raw);
    if (!/^\\+[1-9][0-9]{6,14}$/.test(phone))
      throw ctx.error("VALIDATION_FAILED", {
        message: "Проверьте телефон",
        fields: [{ field: "phone", code: "phone", message: "Неверный номер телефона" }],
      });
    const lines: Line[] = [];
    for (const [id, qty] of wanted) {
      const p = (await ctx.systemDb.product.get(id as never)) as unknown as Row | null;
      const name = text(p?.name) ?? "Товар";
      if (!p || p.active !== true)
        throw ctx.error("NOT_AVAILABLE", { message: \`«\${name}» больше не продаётся — уберите его из корзины\`, product: id });
      if (qty > 99) throw ctx.error("TOO_MANY", { message: \`«\${name}»: не больше 99 шт. в одном заказе\`, product: id });
      const stock = typeof p.stock === "number" ? p.stock : 0;${
        o.withStock
          ? `
      if (stock < qty)
        throw ctx.error("OUT_OF_STOCK", {
          message: stock > 0 ? \`«\${name}»: в наличии только \${stock} шт.\` : \`«\${name}» закончился\`,
          product: id,
          left: stock,
        });`
          : ""
      }
      const price = kop(p.price);
      const weight = typeof p.weight_g === "number" && p.weight_g > 0 ? p.weight_g : ${has("cdek") ? "PARCEL_WEIGHT" : "0"};
      lines.push({ product: id, name, qty, price, sum: price * qty, stock, weight: weight * qty });
    }

    const order: Row = {};
    let delivery = 0;${
      has("pickup")
        ? `
    if (args.delivery === "pickup") {
      const point = args.pickupPoint ? ((await ctx.systemDb.pickup_point.get(args.pickupPoint)) as unknown as Row | null) : null;
      if (!point || point.active !== true)
        throw ctx.error("PICKUP_POINT_REQUIRED", { message: "Выберите пункт самовывоза" });
      order.pickup_point = point.id;
    }`
        : ""
    }${
      has("courier")
        ? `
    if (args.delivery === "courier") {
      const address = text(args.address);
      if (!address || address.length < 5)
        throw ctx.error("ADDRESS_REQUIRED", { message: "Укажите адрес доставки: улица, дом, квартира" });
      order.address = address;
      delivery = kop(COURIER_PRICE);
    }`
        : ""
    }${
      has("cdek")
        ? `
    if (args.delivery === "cdek") {
      const q = args.quote ? ((await ctx.systemDb.delivery_quote.get(args.quote)) as unknown as Row | null) : null;
      if (!q || typeof q.expires_at !== "string" || Date.parse(q.expires_at) < ctx.now.getTime())
        throw ctx.error("QUOTE_EXPIRED", { message: "Расчёт доставки устарел — найдите пункты выдачи ещё раз" });
      const weight = lines.reduce((s, l) => s + l.weight, 0);
      if (typeof q.weight_g === "number" && weight > q.weight_g)
        throw ctx.error("QUOTE_EXPIRED", { message: "Состав корзины изменился — рассчитайте доставку ещё раз" });
      const point = quotePoints(q.points).find((x) => x.code === args.cdekPoint);
      if (!point) throw ctx.error("CDEK_POINT_REQUIRED", { message: "Выберите пункт выдачи СДЭК из списка" });
      order.cdek_city = text(q.city);
      order.cdek_point = point.code;
      order.cdek_point_address = point.address.slice(0, 300);
      order.cdek_days = text(q.days);
      delivery = kop(q.price);
    }`
        : ""
    }

    // The next free number (an order the owner deleted leaves a gap; a concurrent order makes this one retry).
    let number = (await ctx.systemDb.shop_order.count()) + 1001;
    while (await ctx.systemDb.shop_order.getBy("number", number)) number += 1;
    const items = lines.reduce((s, l) => s + l.sum, 0);
    const token = args.token;
    const summary = lines.map((l) => \`\${l.name} × \${l.qty}\`).join("; ");
    const id = await ctx.systemDb.shop_order.insert({
      number,
      status: ONLINE ? "awaiting_payment" : "new",
      total: (items + delivery) / 100,
      items_total: items / 100,
      delivery_price: delivery / 100,
      delivery: args.delivery,
      name: args.name.trim(),
      phone,
      ...(args.email ? { email: args.email } : {}),
      ...(text(args.comment) ? { comment: text(args.comment) } : {}),
      items_summary: summary.length > 600 ? \`\${summary.slice(0, 597)}…\` : summary,${
        o.online
          ? `\n      pay_until: new Date(ctx.now.getTime() + RESERVE_MINUTES * 60_000).toISOString(),`
          : ""
      }${o.withStock ? `\n      stock_returned: false,` : ""}
      token,
      ...order,
    } as never);
    for (const l of lines) {
      await ctx.systemDb.shop_order_line.insert({
        shop_order: id,
        product: l.product,
        name: l.name,
        qty: l.qty,
        price: l.price / 100,
        sum: l.sum / 100,
      } as never);${
        o.withStock
          ? `
      await ctx.systemDb.product.patch(l.product as never, { stock: l.stock - l.qty } as never);
      await ctx.systemDb.stock_move.insert({ product: l.product, shop_order: id, qty: -l.qty, kind: "sale" } as never);`
          : ""
      }
    }
    return { id: String(id), number, token, total: (items + delivery) / 100, pay: ONLINE };
  },
});
`;
}

export function orderSource(ctx: GenContext): string {
  const o = shopOptions(ctx.params);
  const has = (d: DeliveryMethod) => o.delivery.includes(d);
  const statuses = Object.fromEntries(ORDER_STATUSES.map((s) => [s.value, s.label]));
  const methods = Object.fromEntries(DELIVERY_METHODS.map((d) => [d.value, d.label]));
  return `// Generated by the module «Интернет-магазин» (V3-23): the order's page of its buyer. The order is found by its id and
// the buyer's secret his browser made at the checkout; the answer holds the goods, the sums, the status and the delivery, never
// the buyer's contacts. A wrong secret looks like a missing order.
import { query, v } from "@wizard/sdk";

${HELPERS}const ONLINE = ${o.online};
const STATUSES: Record<string, string> = ${lit(statuses)};
const DELIVERY: Record<string, string> = ${lit(methods)};
const SOLD = new Set<string>(${lit(SOLD_STATUSES)});

/** Constant-time comparison of two secrets. */
function same(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let d = 0;
  for (let i = 0; i < a.length; i++) d |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return d === 0;
}

export default query({
  args: { id: v.id("shop_order"), token: v.string({ min: 16, max: 128 }) },
  handler: async (ctx, args) => {
    const o = (await ctx.systemDb.shop_order.get(args.id)) as unknown as Row | null;
    if (!o || typeof o.token !== "string" || !same(o.token, args.token)) return null;
    const lines = (await ctx.systemDb.shop_order_line.list({ where: { shop_order: args.id }, limit: 100 })) as unknown as Row[];
    const status = String(o.status ?? "");${
      has("pickup")
        ? `
    const point =
      o.delivery === "pickup" && typeof o.pickup_point === "string"
        ? ((await ctx.systemDb.pickup_point.get(o.pickup_point as never)) as unknown as Row | null)
        : null;`
        : ""
    }
    return {
      id: String(o.id),
      number: Number(o.number ?? 0),
      status,
      statusLabel: STATUSES[status] ?? status,
      paid: SOLD.has(status),
      payable: ONLINE && status === "awaiting_payment",
      payUntil: text(o.pay_until),
      total: kop(o.total) / 100,
      itemsTotal: kop(o.items_total) / 100,
      deliveryPrice: kop(o.delivery_price) / 100,
      delivery: String(o.delivery ?? ""),
      deliveryLabel: DELIVERY[String(o.delivery ?? "")] ?? "",
      pickup: ${has("pickup") ? `point ? { name: text(point.name) ?? "", address: text(point.address) ?? "", hours: text(point.hours) } : null` : "null"},
      cdek: ${
        has("cdek")
          ? `o.delivery === "cdek"
        ? {
            city: text(o.cdek_city),
            address: text(o.cdek_point_address) ?? "",
            days: text(o.cdek_days),
            track: text(o.track_number),
          }
        : null`
          : "null"
      },
      courier: o.delivery === "courier",
      lines: lines.map((l) => ({
        name: text(l.name) ?? "",
        qty: Number(l.qty ?? 0),
        price: kop(l.price) / 100,
        sum: kop(l.sum) / 100,
      })),
      createdAt: text(o.created_at),
    };
  },
});
`;
}

export function cartWeightSource(ctx: GenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): the weight of a cart for the СДЭК quote, grams (a product
// without its weight counts as the parcel weight of the shop's settings). Products the caller cannot see weigh nothing.
import { query, v } from "@wizard/sdk";

const PARCEL_WEIGHT = ${o.parcelWeight};

export default query({
  args: { lines: ${linesArg} },
  handler: async (ctx, args) => {
    let grams = 0;
    for (const l of args.lines) {
      const p = await ctx.db.product.get(l.product);
      if (!p) continue;
      const w = (p as unknown as Record<string, unknown>).weight_g;
      grams += (typeof w === "number" && w > 0 ? w : PARCEL_WEIGHT) * l.qty;
    }
    return Math.max(1, grams);
  },
});
`;
}

export function cdekOptionsSource(ctx: GenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): СДЭК for the checkout — the buyer's city → its pickup points
// and the price of the parcel (tariff ${CDEK_TARIFF} «Посылка склад-склад» from the shop's city). The СДЭК client is
// functions/integrations/cdek: the passport's mock until the shop's key passes its check (then the integration layer
// puts the live client there). The quote is kept for ${QUOTE_MINUTES} minutes: the order takes its price, never the page's.
import { action, v } from "@wizard/sdk";
import { calculateTariff, listCities, listDeliveryPoints, MODE } from "../integrations/cdek/client";

const FROM_CITY = ${lit(o.cdekFromCity)};
const TARIFF = ${CDEK_TARIFF};

/** What the checkout gets: the quote (its price is the order's), the city, the term, the points. */
interface CdekOptions {
  quote: string;
  city: string;
  price: number;
  days: string;
  points: { code: string; name: string; address: string; hours: string }[];
  test: boolean;
}

const days = (min: number, max: number): string => (min === max ? \`\${min} раб. дн.\` : \`\${min}–\${max} раб. дн.\`);

export default action({
  args: { city: v.string({ min: 2, max: 80 }), lines: ${linesArg} },
  handler: async (ctx, args): Promise<CdekOptions> => {
    const weight: number = await ctx.runQuery("shopCartWeight", { lines: args.lines });
    const [to] = await listCities(ctx, { countryCodes: "RU", city: args.city.trim(), size: 1 });
    if (!to) throw ctx.error("CITY_NOT_FOUND", { message: "СДЭК не нашёл такой город — проверьте название" });
    const [from] = await listCities(ctx, { countryCodes: "RU", city: FROM_CITY, size: 1 });
    if (!from) throw ctx.error("CDEK_UNAVAILABLE", { message: "Доставка СДЭК сейчас недоступна — выберите другой способ" });
    const found = await listDeliveryPoints(ctx, { cityCode: to.code, type: "PVZ", countryCode: "RU", size: 50 });
    const points = found
      .filter((p) => p.is_handout !== false && typeof p.location.address === "string")
      .slice(0, 50)
      .map((p) => ({ code: p.code, name: p.name ?? "", address: p.location.address, hours: p.work_time ?? "" }));
    if (points.length === 0)
      throw ctx.error("NO_POINTS", { message: \`В городе «\${to.city}» нет пунктов выдачи СДЭК\` });
    const tariff = await calculateTariff(ctx, {
      body: { type: 1, tariff_code: TARIFF, from_location: { code: from.code }, to_location: { code: to.code }, packages: [{ weight }] },
    });
    const price = Math.ceil(tariff.total_sum);
    const term = days(tariff.period_min, tariff.period_max);
    const quote: string = await ctx.runMutation("shopSaveQuote", {
      city: to.city.slice(0, 80),
      cityCode: to.code,
      price,
      tariffCode: TARIFF,
      days: term,
      weight,
      points: JSON.stringify(points.map((p) => ({ code: p.code, address: p.address }))),
    });
    // test: the answer is the passport's mock (no key yet) — the page says the prices are an example.
    return { quote, city: to.city, price, days: term, points, test: (MODE as string) === "mock" };
  },
});
`;
}

export const saveQuoteSource = `// Generated by the module «Интернет-магазин» (V3-23): a СДЭК quote of shopCdekOptions kept for ${QUOTE_MINUTES} minutes:
// the checkout's order takes the price and checks the pickup point by it.
import { mutation, v } from "@wizard/sdk";

export default mutation({
  args: {
    city: v.string({ min: 1, max: 80 }),
    cityCode: v.int(),
    price: v.number({ min: 0 }),
    tariffCode: v.int(),
    days: v.string({ max: 40 }),
    weight: v.int({ min: 1 }),
    points: v.string({ max: 20000 }),
  },
  handler: async (ctx, args) => {
    const id = await ctx.systemDb.delivery_quote.insert({
      city: args.city,
      city_code: args.cityCode,
      price: args.price,
      tariff_code: args.tariffCode,
      days: args.days,
      weight_g: args.weight,
      points: args.points,
      expires_at: new Date(ctx.now.getTime() + ${QUOTE_MINUTES} * 60_000).toISOString(),
    });
    return String(id);
  },
});
`;

export const returnStockSource = `// Generated by the module «Интернет-магазин» (V3-23): a cancelled order gives its goods back to the stock — once, by
// the stock journal of the order (what was written off for it).
import { mutation, v } from "@wizard/sdk";

type Row = Record<string, unknown>;

export default mutation({
  args: { id: v.id("shop_order") },
  handler: async (ctx, args) => {
    const o = (await ctx.systemDb.shop_order.get(args.id)) as unknown as Row | null;
    if (!o || o.status !== "canceled" || o.stock_returned === true) return { ok: false };
    const moves = (await ctx.systemDb.stock_move.list({ where: { shop_order: args.id }, limit: 500 })) as unknown as Row[];
    const net = new Map<string, number>();
    for (const m of moves) net.set(String(m.product), (net.get(String(m.product)) ?? 0) - Number(m.qty ?? 0));
    for (const [product, qty] of net) {
      if (qty <= 0) continue;
      const p = (await ctx.systemDb.product.get(product as never)) as unknown as Row | null;
      if (!p) continue;
      const stock = typeof p.stock === "number" ? p.stock : 0;
      await ctx.systemDb.product.patch(product as never, { stock: stock + qty } as never);
      await ctx.systemDb.stock_move.insert({ product, shop_order: args.id, qty, kind: "return" } as never);
    }
    await ctx.systemDb.shop_order.patch(args.id, { stock_returned: true } as never);
    return { ok: true };
  },
});
`;

export const orderPaidSource = `// Generated by the module «Интернет-магазин» (V3-23): an order paid after its cancel (the payment page stayed open past
// the time to pay) takes its goods off the stock again; what the stock lacks is written in the shop's note.
import { mutation, v } from "@wizard/sdk";

type Row = Record<string, unknown>;

export default mutation({
  args: { id: v.id("shop_order") },
  handler: async (ctx, args) => {
    const o = (await ctx.systemDb.shop_order.get(args.id)) as unknown as Row | null;
    if (!o || o.status !== "paid" || o.stock_returned !== true) return { ok: false };
    const lines = (await ctx.systemDb.shop_order_line.list({ where: { shop_order: args.id }, limit: 100 })) as unknown as Row[];
    const short: string[] = [];
    for (const l of lines) {
      if (typeof l.product !== "string") continue;
      const p = (await ctx.systemDb.product.get(l.product as never)) as unknown as Row | null;
      if (!p) continue;
      const stock = typeof p.stock === "number" ? p.stock : 0;
      const qty = Number(l.qty ?? 0);
      const take = Math.min(stock, qty);
      if (take < qty) short.push(\`\${String(l.name ?? "Товар")}: не хватает \${qty - take} шт.\`);
      if (take <= 0) continue;
      await ctx.systemDb.product.patch(l.product as never, { stock: stock - take } as never);
      await ctx.systemDb.stock_move.insert({ product: l.product, shop_order: args.id, qty: -take, kind: "sale" } as never);
    }
    const note = short.length ? \`Оплачен после отмены. \${short.join("; ")}\`.slice(0, 300) : undefined;
    await ctx.systemDb.shop_order.patch(args.id, { stock_returned: false, ...(note ? { note } : {}) } as never);
    return { ok: true };
  },
});
`;
