// Public pages of «Интернет-магазин» on the v2 front (screen generators, V3-23): the goods, a product's page (V3-18),
// the cart with the checkout, the order's page. They render the ui-kit shop components (ShopProducts, ShopProduct,
// ShopCart, ShopCheckout, ShopOrder) over the headless shop of v3; on the v3 front these screens are the composer's
// (patterns shop-*, product-*, cart-*, checkout-*, order-*).
import type { AppSpec } from "@wizard/appspec";
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";
import {
  DELIVERY_METHODS,
  SHOP_FUNCTIONS,
  SHOP_NAMES,
  SHOP_PAYMENT,
  SHOP_ROUTES,
  SHOP_TERMS_ROUTES,
  shopOptions,
} from "./compile.js";
import { ORDER_CONSENT_FIELD } from "./functions.js";

/** Prefix of the order's page («/order/»). */
export const ORDER_PREFIX = SHOP_ROUTES.order.replace(/:id$/, "");
/** Prefix of a product's page («/shop/», V3-18). */
export const PRODUCT_PREFIX = SHOP_ROUTES.product.replace(/:id$/, "");

/** The order keeps the buyer's consent to the letters about it (notify adds the field with visitor_emails). */
export const ordersConsent = (spec: Pick<AppSpec, "entities">): boolean =>
  spec.entities.some(
    (e) => e.name === SHOP_NAMES.order && e.fields.some((f) => f.name === ORDER_CONSENT_FIELD),
  );

/**
 * The checkout's configuration of a plan (props of ShopCheckout and of the v3 checkout patterns); with the spec — the
 * box of the letters about the order when the order keeps that consent (V3-18).
 */
export function checkoutConfig(params: Readonly<Record<string, unknown>>, spec?: Pick<AppSpec, "entities">) {
  const o = shopOptions(params);
  return {
    methods: DELIVERY_METHODS.filter((d) => o.delivery.includes(d.value)).map((d) => ({ ...d })),
    online: o.online,
    ...(o.delivery.includes("courier") ? { courierPrice: o.courierPrice } : {}),
    pointEntity: SHOP_NAMES.point,
    placeFn: SHOP_FUNCTIONS.place,
    cdekFn: SHOP_FUNCTIONS.cdek,
    ...(o.online
      ? { payment: { integration: SHOP_PAYMENT.integration, binding: SHOP_PAYMENT.binding } }
      : {}),
    orderPath: ORDER_PREFIX,
    ...(spec && ordersConsent(spec) ? { consentMessages: true } : {}),
  };
}

/** JSX attributes `name={json}` of an object (each attribute is typed by its prop, literals stay literal). */
const attrs = (o: Readonly<Record<string, unknown>>): string =>
  Object.entries(o)
    .map(([k, v]) => `${k}={${js(v)}}`)
    .join(" ");

/** /shop: the goods on sale with «В корзину». */
export function shopPage(ctx: ScreenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): the goods on sale with «В корзину».
import { LandingSection, ShopProducts } from "@wizard/ui-kit";

export default function ShopShop() {
  return (
    <main>
      <LandingSection title=${js(ctx.screen.title)} main>
        <ShopProducts entity=${js(SHOP_NAMES.product)} cartPath=${js(SHOP_ROUTES.cart)} productPath=${js(PRODUCT_PREFIX)} fields={${js({ stock: o.withStock ? "stock" : null })}} emptyText="Товары скоро появятся" />
      </LandingSection>
    </main>
  );
}
`;
}

/** /shop/:id: one product with its photo, the whole description, the price and «В корзину» (V3-18). */
export function productPage(ctx: ScreenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-18): a product's page — photo, description, price, «В корзину».
import { LandingSection, ShopProduct } from "@wizard/ui-kit";

export default function ShopProductPage() {
  return (
    <main>
      <LandingSection title=${js(ctx.screen.title)} main>
        <ShopProduct entity=${js(SHOP_NAMES.product)} path=${js(PRODUCT_PREFIX)} cartPath=${js(SHOP_ROUTES.cart)} shopPath=${js(SHOP_ROUTES.shop)} fields={${js({ stock: o.withStock ? "stock" : null })}} />
      </LandingSection>
    </main>
  );
}
`;
}

/** /cart: the lines of the cart and the checkout. */
export function cartPage(ctx: ScreenContext): string {
  return `// Generated by the module «Интернет-магазин» (V3-23): the cart and the checkout (delivery, contacts, payment).
import { LandingSection, ShopCart, ShopCheckout } from "@wizard/ui-kit";

export default function ShopCartPage() {
  return (
    <main>
      <LandingSection title=${js(ctx.screen.title)} main>
        <ShopCart shopPath=${js(SHOP_ROUTES.shop)} />
        <ShopCheckout ${attrs({ ...checkoutConfig(ctx.params, ctx.spec), terms: SHOP_TERMS_ROUTES })} />
      </LandingSection>
    </main>
  );
}
`;
}

/** /order/:id: the order of its buyer (by the secret kept in his browser) and its payment. */
export function orderPage(ctx: ScreenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): the order of its buyer and its payment while it waits for one.
import { LandingSection, ShopOrder } from "@wizard/ui-kit";

export default function ShopOrderPage() {
  return (
    <main>
      <LandingSection title="Ваш заказ" main>
        <ShopOrder path=${js(ORDER_PREFIX)} orderFn=${js(SHOP_FUNCTIONS.order)} payment={${js(o.online ? { integration: SHOP_PAYMENT.integration, binding: SHOP_PAYMENT.binding } : null)}} shopPath=${js(SHOP_ROUTES.shop)} />
      </LandingSection>
    </main>
  );
}
`;
}
