// Public pages of «Интернет-магазин» on the v2 front (screen generators, V3-23): the goods, the cart with the checkout,
// the order's page. They render the ui-kit shop components (ShopProducts, ShopCart, ShopCheckout, ShopOrder) over the
// headless shop of v3; on the v3 front these screens are the composer's (patterns shop-*, cart-*, checkout-*, order-*).
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";
import {
  DELIVERY_METHODS,
  SHOP_FUNCTIONS,
  SHOP_NAMES,
  SHOP_PAYMENT,
  SHOP_ROUTES,
  shopOptions,
} from "./compile.js";

/** Prefix of the order's page («/order/»). */
export const ORDER_PREFIX = SHOP_ROUTES.order.replace(/:id$/, "");

/** The checkout's configuration of a plan (props of ShopCheckout and of the v3 checkout patterns). */
export function checkoutConfig(params: Readonly<Record<string, unknown>>) {
  const o = shopOptions(params);
  return {
    methods: DELIVERY_METHODS.filter((d) => o.delivery.includes(d.value)).map((d) => ({ ...d })),
    online: o.online,
    ...(o.delivery.includes("courier") ? { courierPrice: o.courierPrice } : {}),
    pointEntity: SHOP_NAMES.point,
    placeFn: SHOP_FUNCTIONS.place,
    cdekFn: SHOP_FUNCTIONS.cdek,
    ...(o.online
      ? { payment: { integration: SHOP_PAYMENT.integration, binding: SHOP_PAYMENT.binding } }
      : {}),
    orderPath: ORDER_PREFIX,
  };
}

/** JSX attributes `name={json}` of an object (each attribute is typed by its prop, literals stay literal). */
const attrs = (o: Readonly<Record<string, unknown>>): string =>
  Object.entries(o)
    .map(([k, v]) => `${k}={${js(v)}}`)
    .join(" ");

/** /shop: the goods on sale with «В корзину». */
export function shopPage(ctx: ScreenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): the goods on sale with «В корзину».
import { LandingSection, ShopProducts } from "@wizard/ui-kit";

export default function ShopShop() {
  return (
    <main>
      <LandingSection title=${js(ctx.screen.title)} main>
        <ShopProducts entity=${js(SHOP_NAMES.product)} cartPath=${js(SHOP_ROUTES.cart)} fields={${js({ stock: o.withStock ? "stock" : null })}} emptyText="Товары скоро появятся" />
      </LandingSection>
    </main>
  );
}
`;
}

/** /cart: the lines of the cart and the checkout. */
export function cartPage(ctx: ScreenContext): string {
  return `// Generated by the module «Интернет-магазин» (V3-23): the cart and the checkout (delivery, contacts, payment).
import { LandingSection, ShopCart, ShopCheckout } from "@wizard/ui-kit";

export default function ShopCartPage() {
  return (
    <main>
      <LandingSection title=${js(ctx.screen.title)} main>
        <ShopCart shopPath=${js(SHOP_ROUTES.shop)} />
        <ShopCheckout ${attrs(checkoutConfig(ctx.params))} />
      </LandingSection>
    </main>
  );
}
`;
}

/** /order/:id: the order of its buyer (by the secret kept in his browser) and its payment. */
export function orderPage(ctx: ScreenContext): string {
  const o = shopOptions(ctx.params);
  return `// Generated by the module «Интернет-магазин» (V3-23): the order of its buyer and its payment while it waits for one.
import { LandingSection, ShopOrder } from "@wizard/ui-kit";

export default function ShopOrderPage() {
  return (
    <main>
      <LandingSection title="Ваш заказ" main>
        <ShopOrder path=${js(ORDER_PREFIX)} orderFn=${js(SHOP_FUNCTIONS.order)} payment={${js(o.online ? { integration: SHOP_PAYMENT.integration, binding: SHOP_PAYMENT.binding } : null)}} shopPath=${js(SHOP_ROUTES.shop)} />
      </LandingSection>
    </main>
  );
}
`;
}
