// generateTypes lives in @wizard/appspec and emits `_generated/wizard.d.ts` in the sdk.md §4 format (L2-17);
// the forum snapshot is checked by @wizard/sdk through its @wizard/sdk/codegen re-export.
import { readFileSync } from "node:fs";
import ts from "typescript";
import { describe, expect, test } from "vitest";
import {
  type AppSpec,
  entityIndexes,
  FIELD_TYPES,
  type Field,
  generateTypes,
  isRangeValue,
  planMigration,
  resolveIndex,
  uniqueFields,
} from "../src/index.js";
import { forumSpec, miniSpec, repoRoot } from "./helpers.js";

/** miniSpec plus one field of every type, a composite index, a unique field, a hidden field and payments. */
function richSpec(): AppSpec {
  const spec = miniSpec();
  const task = spec.entities[0] as AppSpec["entities"][number];
  const extra: Field[] = FIELD_TYPES.filter((t) => t !== "enum" && t !== "ref").map((type) => ({
    name: `f_${type}`,
    label: `Поле ${type}`,
    type,
  }));
  task.fields.push(...extra, { name: "code", label: "Код", type: "string", unique: true });
  task.indexes = [{ fields: ["state", "points"] }];
  spec.permissions.push({ role: "guest", entity: "comment", ops: ["read"], hiddenFields: ["body"] });
  spec.integrations?.push(
    { name: "pay", connector: "yookassa", config: { bindings: [{ id: "task" }, { id: "comment" }] } },
    { name: "tg", connector: "telegram", config: {} },
  );
  return spec;
}

function block(out: string, name: string): string {
  const start = out.indexOf(`    ${name}: {`);
  return out.slice(start, out.indexOf("\n    };", start));
}

describe("generateTypes (sdk.md §4)", () => {
  const out = generateTypes(richSpec());

  test("augments the five registries of @wizard/sdk and imports only what it uses", () => {
    expect(out.startsWith("// Generated by @wizard/sdk/codegen generateTypes(spec). Do not edit.\n")).toBe(
      true,
    );
    expect(out).toContain(
      'import type { EmailConnector, Id, Json, Range, TelegramConnector, YookassaConnector } from "@wizard/sdk";',
    );
    expect(out).toContain('declare module "@wizard/sdk" {');
    for (const i of ["Roles", "Entities", "Functions", "Connectors", "Payments"]) {
      expect(out).toMatch(new RegExp(`\\n  interface ${i} \\{`));
    }
    expect(out).toContain('stats: typeof import("../functions/stats").default;');
    expect(out).toContain('pay: "task" | "comment";');
    expect(out).toContain("mail: EmailConnector;");
    expect(generateTypes(richSpec(), { importBase: "../../" })).toContain('import("../../functions/stats")');
  });

  test("field type mapping", () => {
    const t = block(out, "task");
    const want: Record<string, string> = {
      string: "string",
      text: "string",
      email: "string",
      phone: "string",
      url: "string",
      file: "string",
      qr_token: "string",
      int: "number",
      decimal: "number",
      money: "number",
      bool: "boolean",
      date: "string",
      datetime: "string",
      json: "Json",
    };
    for (const [type, ts] of Object.entries(want)) expect(t).toContain(` f_${type}: ${ts} | null;`);
    expect(t).toContain('/** Статус */ state: "todo" | "done" | null;');
    expect(t).toContain('/** Владелец */ owner: Id<"users"> | null;');
    expect(t).toContain("/** Название */ title: string;");
    expect(t).toMatch(/insert: \{\n\s+title: string;\n\s+owner\?: Id<"users"> \| null;/);
    expect(t).toContain('unique: "code";');
    expect(block(out, "comment")).toMatch(/clientDoc: \{\n\s+task: Id<"task">;\n\s+body\?: string;/);
  });

  test("the real forum example matches the normative fragment of sdk.md §4", () => {
    const sdkMd = readFileSync(`${repoRoot}specs/runtime/sdk.md`, "utf8");
    const importLine = sdkMd
      .split("\n")
      .find((l) => l.startsWith("import type {") && l.includes("@wizard/sdk"));
    const forum = generateTypes(forumSpec());
    expect(importLine).toBeDefined();
    expect(forum).toContain(importLine);
    expect(forum).toMatch(/interface Payments \{\n\s+yookassa: "ticket";/);
    expect(block(forum, "stream")).toContain("where:");
  });

  test("the declarations typecheck: where rejects `{}` and keys outside index prefixes", () => {
    const files: Record<string, string> = {
      "/sdk.d.ts": `declare module "@wizard/sdk" {
        export type Id<T extends string = string> = string & { readonly __table?: T };
        export type Range<T> = { gt?: T; gte?: T; lt?: T; lte?: T };
        export type Json = null | boolean | number | string | Json[] | { [k: string]: Json };
        export interface Roles {} export interface Entities {} export interface Functions {}
        export interface Connectors {} export interface Payments {}
        export interface EmailConnector { email: true } export interface TelegramConnector { telegram: true }
        export interface YookassaConnector { yookassa: true } export interface QrConnector { qr: true }
      }`,
      "/m/_generated/wizard.d.ts": out,
      "/m/functions/stats.ts": 'const fn: { kind: "query" } = { kind: "query" };\nexport default fn;\n',
      "/m/usage.ts": `
        import type { Connectors, Entities, Functions, Payments, Roles } from "@wizard/sdk";
        type Task = Entities["task"];
        export const state: Task["doc"]["state"] = "todo";
        // @ts-expect-error not an enum value
        export const badState: Task["doc"]["state"] = "archived";
        export const ins: Task["insert"] = { title: "x" };
        // @ts-expect-error title is required
        export const insBad: Task["insert"] = { code: "c" };
        export const w1: Task["where"] = { state: "todo", points: { gte: 1 } };
        export const w2: Task["where"] = { created_at: { lt: "2026-10-01" } };
        // @ts-expect-error {} is not an index prefix
        export const w0: Task["where"] = {};
        // @ts-expect-error title is not indexed
        export const w3: Task["where"] = { title: "x" };
        // @ts-expect-error points without state is not a prefix
        export const w4: Task["where"] = { points: 1 };
        export const u: Task["unique"] = "code";
        export const role: keyof Roles = "worker";
        // @ts-expect-error unknown role
        export const badRole: keyof Roles = "admin";
        export const kind: Functions["stats"]["kind"] = "query";
        export const pay: Payments["pay"] = "comment";
        export const tg: Connectors["tg"] = { telegram: true };
        export const hidden: Entities["comment"]["clientDoc"] = { task: "t" };
        // @ts-expect-error task is not hidden for any role
        export const notHidden: Entities["comment"]["clientDoc"] = { body: "b" };
      `,
    };
    const options: ts.CompilerOptions = {
      strict: true,
      noEmit: true,
      target: ts.ScriptTarget.ES2022,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      types: [],
      noLib: true,
    };
    const host = ts.createCompilerHost(options);
    host.getSourceFile = (name, lang) => {
      const text = files[name];
      return text === undefined ? undefined : ts.createSourceFile(name, text, lang);
    };
    host.fileExists = (name) => name in files;
    host.readFile = (name) => files[name];
    host.directoryExists = (dir) =>
      Object.keys(files).some((f) => f.startsWith(`${dir.replace(/\/$/, "")}/`));
    host.getCurrentDirectory = () => "/";
    const program = ts.createProgram(Object.keys(files), options, host);
    const diags = ts.getPreEmitDiagnostics(program).filter((d) => d.code !== 2318); // noLib: missing global types
    expect(
      diags.map((d) => `${d.file?.fileName}: ${ts.flattenDiagnosticMessageText(d.messageText, "\n")}`),
    ).toEqual([]);
  });
});

describe("index model (sdk.md §2.4)", () => {
  test("every index usable in `where` is backed by the DDL: PK, UNIQUE or an index toDDL creates", () => {
    for (const spec of [richSpec(), forumSpec()]) {
      const created = planMigration(null, spec)
        .steps.filter((s) => s.kind === "add_index")
        .map((s) => `${(s as { entity: string }).entity}:${(s as { fields: string[] }).fields.join(",")}`);
      for (const e of spec.entities) {
        const unique = uniqueFields(e);
        for (const idx of entityIndexes(e)) {
          const backed =
            (idx.length === 1 && (idx[0] === "id" || unique.includes(idx[0] as string))) ||
            created.includes(`${e.name}:${idx.join(",")}`);
          expect(backed, `${e.name}(${idx.join(",")})`).toBe(true);
        }
      }
    }
  });

  test("resolveIndex picks the index whose prefix is the where keys; isRangeValue", () => {
    const task = richSpec().entities[0] as AppSpec["entities"][number];
    expect(entityIndexes(task).slice(0, 3)).toEqual([["state", "points"], ["id"], ["created_at"]]);
    expect(resolveIndex(task, ["points", "state"])).toEqual(["state", "points"]);
    expect(resolveIndex(task, ["state"])).toEqual(["state", "points"]);
    expect(resolveIndex(task, ["points"])).toBeUndefined();
    expect(resolveIndex(task, [])).toBeUndefined();
    expect(isRangeValue({ gte: 1, lt: 2 })).toBe(true);
    expect(isRangeValue({})).toBe(false);
    expect(isRangeValue({ gte: 1, eq: 2 })).toBe(false);
  });
});
