// Template gate (V3-14, D77_v3 (6), specs/agents/builder-v3.md §3 C6 stage template_gate): a model-free metric of how
// much a new public site repeats recent sites — structure of the site model, DOM shapes and perceptual hashes.
export {
  DOM_SKETCH_SCRIPT,
  FULL_PAGE_MAX_HEIGHT,
  type ImageHashes,
  type PageFingerprint,
  type PageView,
  type PatternLookup,
  type SectionShape,
  type SectionToken,
  type SiteFingerprint,
  sectionToken,
  siteStructure,
  TEMPLATE_VIEWPORTS,
  type TemplateSite,
  type TemplateViewportId,
} from "./fingerprint.js";
export {
  dHash,
  grayThumb,
  HASH_BITS,
  hamming,
  hashSimilarity,
  lowDct,
  pHash,
  type RgbaImage,
} from "./image.js";
export {
  alignment,
  DOM_BASELINE,
  HOME_WEIGHT,
  type PageSimilarity,
  pageSimilarity,
  type SiteSimilarity,
  shapeSimilarity,
  siteSimilarity,
  TEMPLATE_STRUCTURE_THRESHOLD,
  TEMPLATE_THRESHOLD,
  TEMPLATE_WEIGHTS,
  type TemplateMatch,
  type TemplateMemoryItem,
  type TemplateVerdict,
  templateVerdict,
  thresholdOf,
  tokenSimilarity,
  VISUAL_WEIGHTS,
  viewVisualSimilarity,
} from "./similarity.js";
