// M2-01 acceptance, CI job `sandbox` only (WIZARD_SANDBOX_E2E=1, WORKERD_BIN): the pod config generated by
// workerd-config.ts runs in a real workerd, and a test system's functions report plain facts about their environment
// (security/isolation.yaml#M2.runtime). Negative-capability assertions only: no Node globals or built-ins, no code
// generation from strings, no Spectre gadgets, no outbound network, frozen clock, per-system globals, wall limit.
import type { CurrentUser } from "@wizard/sdk";
import { toErrorResponse } from "@wizard/sdk/host";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { SandboxRpc, WorkerdExecutor, type WorkerdSystem, workerdPodConfig } from "../../src/index.js";
import { KEY, startRpcServer } from "./helpers.js";
import { NODE_IMPORT_BUNDLE, PROBE_BUNDLE, PROBE_FUNCTIONS } from "./probe-bundle.js";
import {
  freePortRange,
  startWorkerd,
  type WorkerdProcess,
  type WrittenConfig,
  workerdLoadResult,
  writePodConfig,
} from "./workerd-process.js";

const E2E = process.env.WIZARD_SANDBOX_E2E === "1";
const USER = { id: null, role: "visitor", isAdmin: false, attrs: {} } as unknown as CurrentUser;

const probe = (systemId: string, functionsSource = PROBE_BUNDLE): WorkerdSystem => ({
  systemId,
  env: "draft",
  functionsSource,
  entities: ["ticket"],
});

describe.skipIf(!E2E)("workerd with the generated pod config (CI sandbox job)", () => {
  let rpc: SandboxRpc;
  let rpcServer: Awaited<ReturnType<typeof startRpcServer>>;
  const configs: WrittenConfig[] = [];
  const pods: WorkerdProcess[] = [];

  async function startPod(systems: WorkerdSystem[]) {
    const base = await freePortRange(systems.length + 1);
    const written = writePodConfig(
      workerdPodConfig({
        systems,
        rpcAddress: `127.0.0.1:${rpcServer.port}`,
        listenHost: "127.0.0.1",
        healthPort: base,
        basePort: base + 1,
      }),
    );
    configs.push(written);
    const pod = await startWorkerd(written, base);
    pods.push(pod);
    const timeouts: string[] = [];
    const executors = systems.map(
      (s, slot) =>
        new WorkerdExecutor({
          endpoint: `http://127.0.0.1:${base + 1 + slot}`,
          systemId: s.systemId,
          env: s.env,
          rpc,
          onTimeout: () => timeouts.push(s.systemId),
        }),
    );
    return { pod, executors, timeouts };
  }

  const run = (ex: WorkerdExecutor, name: string, timeoutMs = 10_000) =>
    ex.run(name, "query", {}, USER, new Date(), {}, timeoutMs);

  let a: WorkerdExecutor;
  let b: WorkerdExecutor;

  beforeAll(async () => {
    rpc = new SandboxRpc({ key: KEY });
    rpcServer = await startRpcServer(rpc);
    const pod = await startPod([probe("probe_a"), probe("probe_b")]);
    [a, b] = pod.executors as [WorkerdExecutor, WorkerdExecutor];
  }, 60_000);

  afterAll(async () => {
    await Promise.all(pods.map((p) => p.stop()));
    for (const c of configs) c.cleanup();
    await rpcServer?.close();
  });

  it("every system's modules resolve in workerd (main.mjs, functions.mjs, @wizard/sdk, worker-host.mjs, guest.mjs)", async () => {
    expect(Object.keys(await a.functions()).sort()).toEqual([...PROBE_FUNCTIONS].sort());
    expect(Object.keys(await b.functions()).sort()).toEqual([...PROBE_FUNCTIONS].sort());
  });

  it("system code sees no Node globals or built-ins, no code generation, no Spectre gadgets, no outbound network", async () => {
    const facts = (await run(a, "facts")) as Record<string, unknown>;
    expect(facts).toEqual({
      process: "undefined",
      require: "undefined",
      module: "undefined",
      Buffer: "undefined",
      SharedArrayBuffer: "undefined",
      Atomics: "undefined",
      WebAssembly: "undefined",
      fetch: expect.stringMatching(/^(undefined|function)$/),
      WebSocket: "undefined",
      eval: "threw",
      newFunction: "threw",
      importNodeFs: "rejected",
      importNodeChildProcess: "rejected",
      // fetch removed by worker-host.mjs ("absent"); if it survived, globalOutbound deny-all must reject it.
      outboundFetch: expect.stringMatching(/^(absent|rejected)$/),
      clockAdvancedInLoop: false,
      acc: true,
    });
    expect(rpc.size).toBe(0);
  });

  it("a global set by system A is not visible to system B (separate isolates)", async () => {
    const set = (await run(a, "setMarker")) as { global: string; proto: string };
    expect(set.global).toBe("set");
    expect(await run(a, "readMarker")).toEqual({
      global: "string",
      proto: set.proto === "set" ? "string" : "undefined",
    });
    expect(await run(b, "readMarker")).toEqual({ global: "undefined", proto: "undefined" });
  });

  it("a bundle that imports node:child_process is refused at load (no nodejs_compat)", async () => {
    const base = await freePortRange(2);
    const written = writePodConfig(
      workerdPodConfig({
        systems: [probe("probe_node", NODE_IMPORT_BUNDLE)],
        rpcAddress: `127.0.0.1:${rpcServer.port}`,
        listenHost: "127.0.0.1",
        healthPort: base,
        basePort: base + 1,
      }),
    );
    configs.push(written);
    const r = await workerdLoadResult(written, base);
    expect(r.healthy).toBe(false);
    expect(r.exitCode).not.toBe(0);
    expect(r.stderr).toContain("node:child_process");
  }, 30_000);

  it("a hung call → 504 TIMEOUT within the wall limit, the pod is reported for restart", async () => {
    const pod = await startPod([probe("probe_hang")]);
    const ex = pod.executors[0] as WorkerdExecutor;
    const limit = 2000;
    const t0 = Date.now();
    const err = await run(ex, "hang", limit).then(
      () => null,
      (e: unknown) => e,
    );
    const elapsed = Date.now() - t0;
    expect(toErrorResponse(err).status).toBe(504);
    expect(toErrorResponse(err).body.error.code).toBe("TIMEOUT");
    expect(elapsed).toBeGreaterThanOrEqual(limit - 50);
    expect(elapsed).toBeLessThan(limit + 3000);
    expect(pod.timeouts).toEqual(["probe_hang"]);
    expect(rpc.size).toBe(0);
    await pod.pod.stop();
  }, 60_000);
});
