// Generated sites for the calibration of the template gate (V3-14): one-page sites of one niche built from section
// variants (the same section types in the same order — the hard case, as the composer's PAGE_SECTIONS gives every site
// of a niche), rendered as static HTML with the composer's DOM frame (header, <main id="main"> with a <div> per body
// section, footer). A near-duplicate keeps every variant and changes the texts, the palette (a dark one included), the
// fonts and the spacing; a different site changes the variants. Everything is generated by code from a seed.
import type { TemplateSite } from "@wizard/gates";

export const SECTION_ORDER = [
  "header",
  "hero",
  "services",
  "about",
  "testimonials",
  "faq",
  "form",
  "footer",
] as const;
export type FixtureSection = (typeof SECTION_ORDER)[number];

/** Variants of each section type with their layout family (as the ui-kit library tags them). */
export const VARIANTS: Readonly<Record<FixtureSection, Readonly<Record<string, string>>>> = {
  header: { bar: "bar", centered: "centered", "cta-right": "split" },
  hero: { split: "split", centered: "centered", "full-bleed": "full-bleed", editorial: "editorial" },
  services: { cards: "grid", list: "list", zigzag: "split", tiles: "columns" },
  about: { "split-image": "split", stats: "columns", quote: "typographic" },
  testimonials: { cards: "card", single: "centered", wall: "collage" },
  faq: { accordion: "list", "two-col": "split" },
  form: { centered: "centered", split: "split" },
  footer: { columns: "columns", simple: "bar", band: "band" },
};

export type Variants = Record<FixtureSection, string>;

export interface Look {
  bg: string;
  fg: string;
  muted: string;
  accent: string;
  band: string;
  font: string;
  /** Base spacing unit, px. */
  unit: number;
}

export const LOOKS: readonly Look[] = [
  {
    bg: "#ffffff",
    fg: "#1d2433",
    muted: "#5b6577",
    accent: "#2a7f9e",
    band: "#eef4f7",
    font: "Arial, sans-serif",
    unit: 16,
  },
  {
    bg: "#fbf7f0",
    fg: "#2b2118",
    muted: "#6f5f4d",
    accent: "#b04a2f",
    band: "#f1e6d6",
    font: "Georgia, serif",
    unit: 20,
  },
  {
    bg: "#f6f7fb",
    fg: "#14161c",
    muted: "#4b5160",
    accent: "#5b3fd1",
    band: "#e7e9f3",
    font: "Verdana, sans-serif",
    unit: 14,
  },
  {
    bg: "#14171c",
    fg: "#f2f2f2",
    muted: "#b9bec8",
    accent: "#e0a43a",
    band: "#20252d",
    font: "Arial, sans-serif",
    unit: 18,
  },
];

/** A small deterministic generator (mulberry32). */
export function rng(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = a;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const WORDS =
  "запись приём врач клиника лечение зубы консультация чистка имплант брекеты улыбка гигиена диагностика снимок пломба отбеливание скидка семья ребёнок забота спокойно быстро удобно рядом вечером субботу гарантия опыт отзыв".split(
    " ",
  );

function words(r: () => number, min: number, max: number): string {
  const n = min + Math.floor(r() * (max - min + 1));
  const out: string[] = [];
  for (let i = 0; i < n; i++) out.push(WORDS[Math.floor(r() * WORDS.length)] as string);
  const s = out.join(" ");
  return s.charAt(0).toUpperCase() + s.slice(1);
}

const esc = (s: string) => s.replace(/&/g, "&amp;").replace(/</g, "&lt;");

/** A gray «photo» box of the given aspect (the gate serves every photo as the same neutral image). */
const photo = (ratio: string, extra = "") => `<div class="ph" style="aspect-ratio:${ratio};${extra}"></div>`;

function section(type: FixtureSection, variant: string, r: () => number): string {
  const t = (a: number, b: number) => esc(words(r, a, b));
  const btn = (primary = true) => `<a class="btn${primary ? "" : " ghost"}" href="#form">${t(1, 3)}</a>`;
  const nav = () => Array.from({ length: 5 }, () => `<a href="#">${t(1, 1)}</a>`).join("");
  switch (`${type}:${variant}`) {
    case "header:bar":
      return `<header class="wrap row between pad-s"><b class="logo">${t(1, 2)}</b><nav class="row gap nav">${nav()}</nav>${btn()}</header>`;
    case "header:centered":
      return `<header class="wrap col center pad-s"><b class="logo big">${t(1, 2)}</b><nav class="row gap nav">${nav()}</nav></header>`;
    case "header:cta-right":
      return `<header class="wrap row between pad-s"><b class="logo">${t(1, 2)}</b><div class="row gap"><span>+7 843 200-40-50</span>${btn()}<button class="burger" aria-label="Меню">≡</button></div></header>`;
    case "hero:split":
      return `<section class="wrap grid2 pad-l"><div class="col"><h1>${t(4, 8)}</h1><p>${t(14, 26)}</p><div class="row gap">${btn()}${btn(false)}</div></div>${photo("4/3")}</section>`;
    case "hero:centered":
      return `<section class="wrap col center pad-xl narrow"><h1 class="huge">${t(3, 6)}</h1><p>${t(12, 22)}</p>${btn()}</section>`;
    case "hero:full-bleed":
      return `<section class="bleed"><div class="ph cover"></div><div class="over wrap"><h1 class="inv">${t(3, 7)}</h1><p class="inv">${t(10, 18)}</p>${btn()}</div></section>`;
    case "hero:editorial":
      return `<section class="wrap pad-l"><h1 class="mega">${t(2, 4)}</h1><div class="grid3"><p>${t(16, 28)}</p><span></span>${photo("3/2")}</div></section>`;
    case "services:cards":
      return `<section class="wrap pad-l"><h2>${t(2, 4)}</h2><div class="grid3">${Array.from({ length: 6 }, () => `<div class="card"><i class="ico"></i><h3>${t(2, 3)}</h3><p>${t(8, 16)}</p></div>`).join("")}</div></section>`;
    case "services:list":
      return `<section class="wrap pad-l"><h2>${t(2, 4)}</h2><ul class="rows">${Array.from({ length: 6 }, () => `<li class="grid2 line"><h3>${t(2, 3)}</h3><p>${t(10, 18)}</p></li>`).join("")}</ul></section>`;
    case "services:zigzag":
      return `<section class="wrap pad-l"><h2>${t(2, 4)}</h2>${Array.from({ length: 3 }, (_, i) => `<div class="grid2 zig">${i % 2 ? "" : photo("16/10")}<div><h3>${t(2, 4)}</h3><p>${t(16, 26)}</p></div>${i % 2 ? photo("16/10") : ""}</div>`).join("")}</section>`;
    case "services:tiles":
      return `<section class="band pad-l"><div class="wrap"><h2 class="c">${t(2, 4)}</h2><div class="grid4">${Array.from({ length: 8 }, () => `<div class="tile"><i class="ico"></i><h3>${t(1, 2)}</h3></div>`).join("")}</div></div></section>`;
    case "about:split-image":
      return `<section class="wrap grid2 pad-l">${photo("1/1")}<div><h2>${t(3, 5)}</h2><p>${t(30, 50)}</p><p>${t(20, 30)}</p></div></section>`;
    case "about:stats":
      return `<section class="band pad-l"><div class="wrap"><h2>${t(3, 5)}</h2><div class="grid4">${Array.from({ length: 4 }, () => `<div><b class="num">${Math.floor(r() * 900 + 10)}</b><p>${t(2, 4)}</p></div>`).join("")}</div></div></section>`;
    case "about:quote":
      return `<section class="wrap col center pad-xl narrow"><blockquote class="q">${t(16, 26)}</blockquote><p>${t(2, 3)}</p></section>`;
    case "testimonials:cards":
      return `<section class="wrap pad-l"><h2>${t(2, 3)}</h2><div class="grid3">${Array.from({ length: 3 }, () => `<figure class="card"><blockquote>${t(14, 26)}</blockquote><figcaption>${t(2, 2)}</figcaption></figure>`).join("")}</div></section>`;
    case "testimonials:single":
      return `<section class="band pad-xl"><div class="wrap col center narrow"><i class="ava"></i><blockquote class="q">${t(18, 30)}</blockquote><p>${t(2, 2)}</p></div></section>`;
    case "testimonials:wall":
      return `<section class="wrap pad-l"><h2 class="c">${t(2, 3)}</h2><div class="masonry">${Array.from({ length: 7 }, () => `<figure class="card"><blockquote>${t(8, 34)}</blockquote><figcaption>${t(2, 2)}</figcaption></figure>`).join("")}</div></section>`;
    case "faq:accordion":
      return `<section class="wrap pad-l narrow"><h2>${t(2, 3)}</h2><ul class="rows">${Array.from({ length: 6 }, () => `<li class="row between line"><h3>${t(4, 8)}</h3><span>+</span></li>`).join("")}</ul></section>`;
    case "faq:two-col":
      return `<section class="wrap grid2 pad-l"><div><h2>${t(2, 3)}</h2><p>${t(10, 16)}</p></div><dl>${Array.from({ length: 4 }, () => `<dt><b>${t(4, 8)}</b></dt><dd>${t(12, 20)}</dd>`).join("")}</dl></section>`;
    case "form:centered":
      return `<section class="band pad-l" id="form"><div class="wrap col center narrow"><h2>${t(2, 4)}</h2><p>${t(8, 14)}</p><form class="card col"><label>${t(1, 1)}<input></label><label>${t(1, 1)}<input></label><button class="btn">${t(1, 2)}</button></form></div></section>`;
    case "form:split":
      return `<section class="wrap grid2 pad-l" id="form"><div><h2>${t(3, 5)}</h2><p>${t(14, 22)}</p></div><form class="col"><label>${t(1, 1)}<input></label><label>${t(1, 1)}<input></label><label>${t(1, 1)}<textarea></textarea></label><button class="btn">${t(1, 2)}</button></form></section>`;
    case "footer:columns":
      return `<footer class="wrap grid4 pad-l">${Array.from({ length: 4 }, () => `<div class="col"><b>${t(1, 2)}</b>${Array.from({ length: 4 }, () => `<a href="#">${t(1, 2)}</a>`).join("")}</div>`).join("")}</footer>`;
    case "footer:simple":
      return `<footer class="wrap row between pad-s"><b class="logo">${t(1, 2)}</b><span>© 2026 ${t(1, 2)}</span></footer>`;
    case "footer:band":
      return `<footer class="dark pad-xl"><div class="wrap col center"><h2 class="inv">${t(3, 5)}</h2>${btn()}<nav class="row gap nav inv">${nav()}</nav></div></footer>`;
    default:
      throw new Error(`no variant ${type}:${variant}`);
  }
}

const css = (l: Look) => `
:root{--bg:${l.bg};--fg:${l.fg};--muted:${l.muted};--accent:${l.accent};--band:${l.band};--u:${l.unit}px}
*{box-sizing:border-box;margin:0;padding:0}
body{background:var(--bg);color:var(--fg);font-family:${l.font};font-size:16px;line-height:1.5}
.wrap{max-width:1200px;margin:0 auto;padding-left:calc(var(--u)*1.5);padding-right:calc(var(--u)*1.5)}
.narrow{max-width:760px}
.row{display:flex;align-items:center;flex-wrap:wrap}.between{justify-content:space-between}.gap{gap:var(--u)}
.col{display:flex;flex-direction:column;gap:var(--u)}.center{align-items:center;text-align:center}.c{text-align:center}
.pad-s{padding-top:var(--u);padding-bottom:var(--u)}.pad-l{padding-top:calc(var(--u)*4);padding-bottom:calc(var(--u)*4)}
.pad-xl{padding-top:calc(var(--u)*6);padding-bottom:calc(var(--u)*6)}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:calc(var(--u)*2);align-items:center}
.grid3{display:grid;grid-template-columns:repeat(3,1fr);gap:calc(var(--u)*1.5)}
.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:calc(var(--u)*1.5)}
.masonry{columns:3;column-gap:var(--u)}.masonry .card{break-inside:avoid;margin-bottom:var(--u)}
h1{font-size:44px;line-height:1.1}.huge{font-size:64px}.mega{font-size:96px;line-height:1;margin-bottom:calc(var(--u)*2)}
h2{font-size:32px;margin-bottom:calc(var(--u)*1.5)}h3{font-size:19px}
p{color:var(--muted)}.logo{font-size:22px}.logo.big{font-size:30px}.nav a{color:var(--fg);text-decoration:none}
.btn{display:inline-block;background:var(--accent);color:#fff;padding:12px 22px;border-radius:8px;text-decoration:none;border:0;font:inherit}
.btn.ghost{background:transparent;color:var(--accent);border:2px solid var(--accent)}
.burger{font-size:24px;background:none;border:0;color:var(--fg)}
.ph{background:#8c8c8c;width:100%;border-radius:6px}
.bleed{position:relative;min-height:80vh}.cover{position:absolute;inset:0;border-radius:0;height:100%}
.over{position:relative;padding-top:40vh;padding-bottom:calc(var(--u)*3)}.inv{color:#fff}
.card{background:var(--band);padding:calc(var(--u)*1.5);border-radius:10px;display:flex;flex-direction:column;gap:8px}
.band{background:var(--band)}.dark{background:#111;color:#fff}
.ico{display:block;width:40px;height:40px;border-radius:50%;background:var(--accent)}
.tile{display:flex;flex-direction:column;align-items:center;gap:8px;text-align:center}
.rows{list-style:none}.line{border-bottom:1px solid var(--muted);padding:var(--u) 0}
.zig{margin-top:calc(var(--u)*2)}.num{font-size:48px;color:var(--accent)}
.q{font-size:28px;line-height:1.35}.ava{display:block;width:72px;height:72px;border-radius:50%;background:#8c8c8c}
input,textarea{display:block;width:100%;padding:12px;border:1px solid var(--muted);border-radius:6px;font:inherit;margin-top:4px}
dd{margin-bottom:var(--u);color:var(--muted)}
@media (max-width:700px){
  .grid2,.grid3{grid-template-columns:1fr}.grid4{grid-template-columns:1fr 1fr}.masonry{columns:1}
  .nav{display:none}h1{font-size:32px}.huge{font-size:40px}.mega{font-size:52px}h2{font-size:26px}
}`;

export interface FixtureSite {
  name: string;
  variants: Variants;
  html: string;
  site: TemplateSite;
}

/** A one-page site: the given variants, texts from `textSeed`, the look. */
export function fixtureSite(name: string, variants: Variants, textSeed: number, look: Look): FixtureSite {
  const r = rng(textSeed);
  const parts = SECTION_ORDER.map((t) => ({ t, html: section(t, variants[t], r) }));
  const body = parts
    .filter((p) => p.t !== "header" && p.t !== "footer")
    .map((p) => `<div id="${p.t}">${p.html}</div>`)
    .join("\n");
  const html = `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css(look)}</style></head><body><div id="root">${parts[0]?.html}<main id="main">${body}</main>${parts[parts.length - 1]?.html}</div></body></html>`;
  return {
    name,
    variants,
    html,
    site: {
      pages: [
        {
          route: "/",
          sections: SECTION_ORDER.map((t) => ({ id: t, type: t, pattern: `${t}-${variants[t]}` })),
        },
      ],
    },
  };
}

/** Variants picked by a seed (each section type independently). */
export function randomVariants(seed: number): Variants {
  const r = rng(seed);
  const out = {} as Variants;
  for (const t of SECTION_ORDER) {
    const ids = Object.keys(VARIANTS[t]);
    out[t] = ids[Math.floor(r() * ids.length)] as string;
  }
  return out;
}

/** Variants that differ from `base` in every section type that has another variant. */
export function otherVariants(base: Variants, seed: number): Variants {
  const r = rng(seed);
  const out = {} as Variants;
  for (const t of SECTION_ORDER) {
    const ids = Object.keys(VARIANTS[t]).filter((v) => v !== base[t]);
    out[t] = ids[Math.floor(r() * ids.length)] as string;
  }
  return out;
}

/** `base` with `k` of its section types (picked by the seed) in another variant. */
export function mixVariants(base: Variants, k: number, seed: number): Variants {
  const r = rng(seed);
  const other = otherVariants(base, seed);
  const types = [...SECTION_ORDER].sort(() => r() - 0.5).slice(0, k);
  const out = { ...base };
  for (const t of types) out[t] = other[t];
  return out;
}

/** Layout lookup of the fixture patterns (`<type>-<variant>`). */
export function fixtureLookup(
  id: string,
): { sectionType: string; layout: string; variant: string } | undefined {
  for (const t of SECTION_ORDER)
    if (id.startsWith(`${t}-`)) {
      const variant = id.slice(t.length + 1);
      const layout = VARIANTS[t][variant];
      return layout ? { sectionType: t, layout, variant } : undefined;
    }
  return undefined;
}
