// The visual critic of the build v3 (V3-13): rubric, closed edit operations, in-page checks, the stage hook.
export {
  CLS_LIMIT,
  CRITIC_CHECKS_SCRIPT,
  CRITIC_INIT_SCRIPT,
  CRITIC_VIEWPORTS,
  type CriticCheckOptions,
  type CriticCheckResult,
  type CriticViewport,
} from "./checks.js";
export {
  CRITIC_LIMITS,
  type CriticCycle,
  type CriticOptions,
  type CriticReport,
  type CriticStop,
  createCriticHook,
  criticRoutes,
  describeEdit,
  runCritic,
  shotPlan,
} from "./hook.js";
export { editKey, impliedEdit } from "./implied.js";
export {
  applyEdit,
  type CriticState,
  type EditEnv,
  type EditOp,
  type EditResult,
  editOpSchema,
  variantsFor,
} from "./ops.js";
export {
  CRITIC_CALL_TYPE,
  type CritiqueHistory,
  type CritiqueInput,
  critiqueMessages,
  critiqueTool,
  pageOutline,
  shotLegend,
  textPaths,
  tokenOptions,
} from "./prompt.js";
export {
  AXIS_RUBRIC,
  CHECK_CODES,
  CHECK_RUBRIC,
  type CheckCode,
  CRITIC_AXES,
  CRITIC_WIDTHS,
  type CriticAxis,
  type CriticWidth,
  type Critique,
  critiquePasses,
  critiqueSchema,
  critiqueScore,
  type DeterministicProblem,
  type Finding,
  findingSchema,
  parseWhere,
  problemDigest,
  problemKey,
  problemPenalty,
  SEVERITIES,
  type Severity,
  WHERE_RE,
} from "./rubric.js";
export {
  type CriticInspectInput,
  type CriticInspection,
  type CriticInspector,
  type CriticShot,
  type CriticShotRequest,
  imageTokens,
} from "./types.js";
