// Screen «Клиенты и история» of «Клиенты с историей»: the client list, the card with notes and the history — records
// of every other plan module that refer to the client (a ref field to `client`: leads, deals, bookings, packages…).
// The history is read from the compiled spec, so a module that links to the client appears here without changes.
import type { AppSpec } from "@wizard/appspec";
import { columns } from "../screens/cabinet.js";
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";

/** A history section: an entity with a ref field to the client. */
export interface HistorySource {
  entity: string;
  /** The ref field to the client. */
  field: string;
  title: string;
  columns: string[];
  sort: string;
}

const PLURAL: Readonly<Record<string, string>> = {
  Заявка: "Заявки",
  Сделка: "Сделки",
  Запись: "Визиты",
  Абонемент: "Абонементы",
  Выдача: "Выдачи",
};

/** Entities (except the client and its notes) that refer to the client, in the spec's order. */
export function historySources(spec: AppSpec, role: string): HistorySource[] {
  const out: HistorySource[] = [];
  for (const e of spec.entities) {
    if (e.name === "client" || e.name === "client_note") continue;
    const ref = e.fields.find((f) => f.type === "ref" && f.ref?.entity === "client");
    if (!ref) continue;
    const date = e.fields.find((f) => f.name === "starts_at" && (f.type === "datetime" || f.type === "date"));
    const cols = columns(spec, role, e.name)
      .filter((c) => c !== ref.name && c !== date?.name)
      .slice(0, 4);
    out.push({
      entity: e.name,
      field: ref.name,
      title: PLURAL[e.label] ?? e.label,
      columns: [...(date ? [date.name] : []), ...cols, ...(date ? [] : ["created_at"])],
      sort: date?.name ?? "created_at",
    });
  }
  return out;
}

export function clientHistoryPage(ctx: ScreenContext): string {
  const { spec } = ctx;
  const role = ctx.roles[0] ?? "owner";
  const client = spec.entities.find((e) => e.name === "client");
  if (!client) throw new Error("client entity is missing");
  const notes = spec.entities.some((e) => e.name === "client_note");
  const sources = historySources(spec, role);
  const section = (s: HistorySource) =>
    [
      `      {can("read", ${js(s.entity)}) ? (`,
      `        <section aria-label=${js(s.title)}>`,
      `          <h2>{${js(s.title)}}</h2>`,
      `          <DataTable entity=${js(s.entity)} query={{ filter: { ${s.field}: props.id } }} columns={${js(s.columns)}} defaultSort={{ field: ${js(s.sort)}, dir: "desc" }} emptyText="Пока ничего нет" />`,
      "        </section>",
      "      ) : null}",
    ].join("\n");
  const notesBlock = notes
    ? [
        '      {can("read", "client_note") ? (',
        '        <section aria-label="Заметки">',
        "          <h2>Заметки</h2>",
        '          <DataTable entity="client_note" query={{ filter: { client: props.id } }} columns={["text", "created_at"]} defaultSort={{ field: "created_at", dir: "desc" }} emptyText="Заметок пока нет" />',
        '          {can("create", "client_note") ? (',
        "            note ? (",
        '              <RecordForm entity="client_note" mode="create" fields={["text"]} hidden={{ client: props.id }} submitLabel="Сохранить заметку" onSuccess={() => setNote(false)} onCancel={() => setNote(false)} />',
        "            ) : (",
        '              <Button variant="secondary" onClick={() => setNote(true)}>Добавить заметку</Button>',
        "            )",
        "          ) : null}",
        "        </section>",
        "      ) : null}",
      ].join("\n")
    : undefined;
  return [
    "// Generated by the module «Клиенты с историей» (client_card): clients, the card with notes and the history of the",
    "// client's records in the other modules of the system.",
    'import { type ClientDoc, useState } from "@wizard/sdk";',
    'import { Button, DataTable, RecordCard, RecordForm, useCan } from "@wizard/ui-kit";',
    "",
    "export default function ClientCardHistory() {",
    "  const can = useCan();",
    "  const [selected, setSelected] = useState<string | null>(null);",
    '  const [mode, setMode] = useState<"view" | "edit" | "create">("view");',
    "  return (",
    '    <section aria-label="Клиенты">',
    `      <h1>{${js(`${client.label}: карточки и история`)}}</h1>`,
    '      {mode === "create" ? (',
    '        <RecordForm entity="client" mode="create" onSuccess={(r) => { setSelected(r.id); setMode("view"); }} onCancel={() => setMode("view")} />',
    '      ) : can("create", "client") ? (',
    '        <Button variant="primary" onClick={() => { setSelected(null); setMode("create"); }}>Добавить</Button>',
    "      ) : null}",
    `      <DataTable entity="client" columns={${js([...columns(spec, role, "client"), "created_at"])}} defaultSort={{ field: "created_at", dir: "desc" }} searchable onRowClick={(r: ClientDoc<"client">) => { setSelected(r.id); setMode("view"); }} emptyText="Пока никого нет" />`,
    '      {selected && mode !== "create" ? (',
    '        <ClientHistory key={selected} id={selected} edit={mode === "edit"} onEdit={() => setMode("edit")} onView={() => setMode("view")} onClose={() => { setSelected(null); setMode("view"); }} />',
    "      ) : null}",
    "    </section>",
    "  );",
    "}",
    "",
    "function ClientHistory(props: { id: string; edit: boolean; onEdit(): void; onView(): void; onClose(): void }) {",
    "  const can = useCan();",
    notes ? "  const [note, setNote] = useState(false);" : undefined,
    "  return (",
    '    <section aria-label="Карточка">',
    "      {props.edit ? (",
    '        <RecordForm entity="client" mode="edit" id={props.id} onSuccess={props.onView} onCancel={props.onView} />',
    "      ) : (",
    "        <>",
    `          <RecordCard entity="client" id={props.id} actions={can("delete", "client") ? [{ id: "delete", label: "Удалить", tone: "danger", kind: "delete", confirm: "Удалить карточку вместе с заметками?" }] : []} onDeleted={props.onClose} />`,
    '          {can("update", "client") ? <Button variant="secondary" onClick={props.onEdit}>Изменить</Button> : null}',
    '          <Button variant="ghost" onClick={props.onClose}>Закрыть</Button>',
    "        </>",
    "      )}",
    notesBlock,
    ...sources.map(section),
    "    </section>",
    "  );",
    "}",
    "",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
