// Screen «Воронка» of «Воронка сделок»: the kanban of deals by stage on the ui-kit StatusBoard (drag or «Перенести в…»),
// the deal card with stage actions and edit form, a create form and the deal's tasks. Fields come from the compiled
// spec, so the amount, the person in charge, the client and the lead appear only when the plan has them.
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";

export function dealsBoardPage(ctx: ScreenContext): string {
  const { spec } = ctx;
  const deal = spec.entities.find((e) => e.name === "deal");
  if (!deal) throw new Error("deal entity is missing");
  const has = (n: string) => deal.fields.some((f) => f.name === n);
  const tasks = spec.entities.find((e) => e.name === "deal_task");
  const taskCols = (tasks?.fields ?? [])
    .map((f) => f.name)
    .filter((n) => n !== "deal")
    .slice(0, 5);
  const stages = deal.fields.find((f) => f.name === "status")?.enum ?? [];
  const subtitle = has("amount")
    ? 'subtitle: r.amount != null ? r.amount.toLocaleString("ru-RU") + " ₽" : undefined, '
    : "";
  const stageActions = stages
    .map(
      (s) =>
        `{ id: ${js(`to_${s.value}`)}, label: ${js(`Перенести: ${s.label}`)}, kind: "update" as const, patch: { status: ${js(s.value)} }, visible: (r: Doc) => r.status !== ${js(s.value)} }`,
    )
    .join(", ");
  const tasksBlock = tasks
    ? [
        '          {can("read", "deal_task") ? (',
        '            <section aria-label="Задачи">',
        "              <h2>Задачи</h2>",
        `              <DataTable entity="deal_task" query={{ filter: { deal: selected } }} columns={${js(taskCols)}} defaultSort={{ field: "due_at", dir: "asc" }} rowActions={can("update", "deal_task") ? [{ id: "done", label: "Сделано", kind: "update", patch: { done: true }, visible: (t: ClientDoc<"deal_task">) => !t.done }] : []} emptyText="Задач пока нет" />`,
        '              {can("create", "deal_task") ? (',
        "                task ? (",
        `                  <RecordForm entity="deal_task" mode="create" fields={${js(taskCols.filter((n) => n !== "done"))}} hidden={{ deal: selected }} onSuccess={() => setTask(false)} onCancel={() => setTask(false)} />`,
        "                ) : (",
        '                  <Button variant="secondary" onClick={() => setTask(true)}>Добавить задачу</Button>',
        "                )",
        "              ) : null}",
        "            </section>",
        "          ) : null}",
      ].join("\n")
    : undefined;
  return [
    "// Generated by the module «Воронка сделок» (deals): the board of deals by stage, the deal card and its tasks.",
    'import { type ClientDoc, useState } from "@wizard/sdk";',
    'import { Button, DataTable, RecordCard, RecordForm, StatusBoard, useCan } from "@wizard/ui-kit";',
    "",
    'type Doc = ClientDoc<"deal">;',
    "",
    "export default function DealsBoard() {",
    "  const can = useCan();",
    "  const [selected, setSelected] = useState<string | null>(null);",
    '  const [mode, setMode] = useState<"view" | "edit" | "create">("view");',
    tasks ? "  const [task, setTask] = useState(false);" : undefined,
    "  return (",
    '    <section aria-label="Воронка">',
    `      <h1>{${js(`Воронка: ${deal.label}`)}}</h1>`,
    '      {mode === "create" ? (',
    '        <RecordForm entity="deal" mode="create" onSuccess={(r) => { setSelected(r.id); setMode("view"); }} onCancel={() => setMode("view")} />',
    '      ) : can("create", "deal") ? (',
    '        <Button variant="primary" onClick={() => { setSelected(null); setMode("create"); }}>Добавить</Button>',
    "      ) : null}",
    `      <StatusBoard entity="deal" statusField="status" card={(r: Doc) => ({ title: r.title, ${subtitle}})} onCardClick={(r: Doc) => { setSelected(r.id); setMode("view"); }} />`,
    '      {selected && mode === "view" ? (',
    `        <section aria-label=${js(deal.label)}>`,
    `          <RecordCard entity="deal" id={selected} actions={[...(can("update", "deal") ? [${stageActions}] : []), ...(can("delete", "deal") ? [{ id: "delete", label: "Удалить", tone: "danger" as const, kind: "delete" as const, confirm: "Удалить сделку?" }] : [])]} onDeleted={() => setSelected(null)} />`,
    '          {can("update", "deal") ? <Button variant="secondary" onClick={() => setMode("edit")}>Изменить</Button> : null}',
    '          <Button variant="ghost" onClick={() => setSelected(null)}>Закрыть</Button>',
    tasksBlock,
    "        </section>",
    "      ) : null}",
    '      {selected && mode === "edit" ? (',
    '        <RecordForm key={selected} entity="deal" mode="edit" id={selected} onSuccess={() => setMode("view")} onCancel={() => setMode("view")} />',
    "      ) : null}",
    "    </section>",
    "  );",
    "}",
    "",
  ]
    .filter((l) => l !== undefined)
    .join("\n");
}
