// Shared setup of research tests: recorded exchanges (fixtures/exchanges.json, generated by fixtures/gen.mjs), a
// research instance over them and a request spy.
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  createResearch,
  MemoryResearchLog,
  MemoryResearchStore,
  type RecordedExchange,
  type Research,
  type ResearchOptions,
  recordedFetch,
} from "../../src/research/index.js";

export const FIXTURES = join(import.meta.dirname, "fixtures");
export const TEST_KEY = "AQVN-test-key-0000000000000000";
export const TEST_FOLDER = "b1gtestfolder000000";
export const KEY_ENV = { YANDEX_SEARCH_API_KEY: TEST_KEY, YANDEX_FOLDER_ID: TEST_FOLDER };

export function loadExchanges(): RecordedExchange[] {
  return JSON.parse(readFileSync(join(FIXTURES, "exchanges.json"), "utf8")) as RecordedExchange[];
}

export interface SeenRequest {
  url: string;
  method: string;
  headers: Record<string, string>;
  body: string | null;
}

/** Research over the recorded answers; `seen` collects every request (url, method, headers, body). */
export function recordedResearch(o: Partial<ResearchOptions> & { exchanges?: RecordedExchange[] } = {}): {
  research: Research;
  seen: SeenRequest[];
  log: MemoryResearchLog;
  store: MemoryResearchStore;
} {
  const seen: SeenRequest[] = [];
  const log = new MemoryResearchLog();
  const store = (o.store as MemoryResearchStore | undefined) ?? new MemoryResearchStore();
  const fetch = recordedFetch(o.exchanges ?? loadExchanges(), (url, init) => {
    const headers: Record<string, string> = {};
    new Headers(init?.headers).forEach((v, k) => {
      headers[k] = v;
    });
    seen.push({
      url,
      method: init?.method ?? "GET",
      headers,
      body: typeof init?.body === "string" ? init.body : null,
    });
  });
  const research = createResearch({
    env: KEY_ENV,
    mode: "fixture",
    fetch,
    log,
    store,
    context: { runId: "run-1", orgId: "org-1", systemId: "sys-1" },
    ...o,
  });
  return { research, seen, log, store };
}
