// functions/goalMetrics.ts of a compiled system: the query behind the goal panel. It reads each source once for both
// periods under the owner's rights (ctx.db, the panel shows aggregates only) within the row budget and computes the
// data metrics and the reports by entity with the goal-panel library. Result shape — GoalMetricsResult.
import { js } from "../screens/jsx.js";
import type { GenContext } from "../types.js";
import { type PanelModel, type PanelSource, panelModel, ROW_BUDGET } from "./panel.js";

/** Name and file of the query (its roles: the owner). */
export const GOAL_METRICS_FN = "goalMetrics";
export const GOAL_METRICS_FILE = "functions/goalMetrics.ts";
export const LIB_FUNCTIONS_FILE = "functions/lib/goalPanel.ts";
export const LIB_UI_FILE = "ui/lib/goalPanel.ts";

/** What goalMetrics returns ({period}: "week" | "month"); the ids and order follow the panel model. */
export interface GoalMetricsResult {
  period: "week" | "month";
  /** Current period [from, to) as ISO instants. */
  from: string;
  to: string;
  /** base — events of the current period the value stands on (null — unknown; hints need HINT_MIN_EVENTS). */
  metrics: {
    id: string;
    value: number | null;
    previous: number | null;
    base: number | null;
    capped: boolean;
  }[];
  reports: {
    entity: string;
    total: number;
    previous: number;
    byStatus: { value: string; count: number }[];
    capped: boolean;
  }[];
}

/** The paginate call of a source: the range over both periods, or newest first without one. */
function readSource(s: PanelSource): string {
  const where =
    s.mode === "scan"
      ? ""
      : s.dateOnly
        ? `where: { ${s.dateField}: { gte: isoDate(w.previous.from), lte: isoDate(w.current.to) } }, `
        : `where: { ${s.dateField}: { gte: from, lt: to } }, `;
  const order = s.mode === "scan" ? "desc" : "asc";
  return `collect((cursor, numItems) => ctx.db.${s.entity}.paginate({ ${where}order: ${js(order)} }, { cursor, numItems }), budget)`;
}

export function goalMetricsSource(model: PanelModel): string {
  const dated = model.sources.some((s) => s.mode !== "scan" && s.dateOnly);
  const imports = [
    "collect",
    "entityReport",
    ...(dated ? ["isoDate"] : []),
    "type MetricCompute",
    "metricValues",
    "periodWindows",
    "type Row",
  ];
  const ranged = model.sources.some((s) => s.mode !== "scan" && !s.dateOnly);
  const metrics = model.data.map(
    (d) => `  { id: ${js(d.id)}, compute: ${js(d.compute)}, source: ${d.source} },`,
  );
  const reports = model.reports.map(
    (r) =>
      `  { entity: ${js(r.entity)}, status: ${js(r.status)}, statuses: ${js(r.statuses.map((s) => s.value))}, source: ${r.source} },`,
  );
  return [
    "// Generated by the module «Отчёты и панель цели» (B2-17): metrics of the goal panel and reports by entity for the",
    "// owner over both periods (the current one and the one before it); aggregates only, no personal data in the result.",
    'import { query, v } from "@wizard/sdk";',
    `import { ${imports.join(", ")} } from "./lib/goalPanel";`,
    "",
    `const METRICS: { id: string; compute: MetricCompute; source: number }[] = [`,
    ...metrics,
    "];",
    "const REPORTS: { entity: string; status: string | null; statuses: string[]; source: number }[] = [",
    ...reports,
    "];",
    "",
    "export default query({",
    '  args: { period: v.enum("week", "month") },',
    "  handler: async (ctx, args) => {",
    "    const w = periodWindows(args.period, ctx.now.getTime());",
    ...(ranged
      ? [
          "    const from = new Date(w.previous.from).toISOString();",
          "    const to = new Date(w.current.to).toISOString();",
        ]
      : []),
    `    const budget = { left: ${ROW_BUDGET} };`,
    "    const sources: { rows: Row[]; capped: boolean }[] = [];",
    // Ranged reads first: a scan without an index takes what is left of the budget.
    ...model.sources
      .map((s, i) => ({ s, i }))
      .sort((a, b) => Number(a.s.mode === "scan") - Number(b.s.mode === "scan") || a.i - b.i)
      .map(({ s, i }) => `    sources[${i}] = await ${readSource(s)};`),
    "    const empty = { rows: [] as Row[], capped: false };",
    "    return {",
    "      period: args.period,",
    "      from: new Date(w.current.from).toISOString(),",
    "      to: new Date(w.current.to).toISOString(),",
    "      metrics: METRICS.map((m) => {",
    "        const s = sources[m.source] ?? empty;",
    "        return { id: m.id, ...metricValues(m.compute, s.rows, w), capped: s.capped };",
    "      }),",
    "      reports: REPORTS.map((r) => {",
    "        const s = sources[r.source] ?? empty;",
    "        return { entity: r.entity, ...entityReport(s.rows, r.status, r.statuses, w), capped: s.capped };",
    "      }),",
    "    };",
    "  },",
    "});",
    "",
  ].join("\n");
}

/** The FileGenerator of functions/goalMetrics.ts. */
export const goalMetricsFile = (ctx: GenContext): string => goalMetricsSource(panelModel(ctx));
