import { readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";
import { detect, type Finding } from "../src/index.js";
import { CORPUS_PATH, type CorpusLine, corpusJsonl, generateCorpus } from "./gen-corpus.js";

const raw = readFileSync(CORPUS_PATH, "utf8");
const corpus: CorpusLine[] = raw
  .trim()
  .split("\n")
  .map((l) => JSON.parse(l) as CorpusLine);

interface Stat {
  tp: number;
  fp: number;
  fn: number;
}

function evaluate(lines: CorpusLine[]) {
  const perKind: Record<string, Stat> = {};
  const stat = (k: string) => {
    perKind[k] ??= { tp: 0, fp: 0, fn: 0 };
    return perKind[k];
  };
  const errors: string[] = [];
  for (const line of lines) {
    const found: Finding[] = detect(line.text);
    const overlaps = (a: { start: number; end: number }, b: { start: number; end: number }) =>
      a.start < b.end && b.start < a.end;
    for (const g of line.spans) {
      const hit = found.some((f) => f.kind === g.kind && overlaps(f, g));
      stat(g.kind)[hit ? "tp" : "fn"]++;
      if (!hit) errors.push(`FN ${line.id} ${g.kind} «${line.text.slice(g.start, g.end)}» in: ${line.text}`);
    }
    for (const f of found) {
      if (!line.spans.some((g) => g.kind === f.kind && overlaps(f, g))) {
        stat(f.kind).fp++;
        errors.push(`FP ${line.id} ${f.kind} «${line.text.slice(f.start, f.end)}» in: ${line.text}`);
      }
    }
  }
  const total = Object.values(perKind).reduce((a, s) => ({ tp: a.tp + s.tp, fp: a.fp + s.fp, fn: a.fn + s.fn }), {
    tp: 0,
    fp: 0,
    fn: 0,
  });
  return { perKind, total, errors };
}

const ratio = (a: number, b: number) => (b === 0 ? 1 : a / b);

describe("corpus.ru.jsonl (data-boundary.yaml#detectors.quality, M0-05)", () => {
  test("is generated by test/gen-corpus.ts and up to date", () => {
    expect(raw).toBe(corpusJsonl(generateCorpus()));
  });

  test("has ≥ 200 lines incl. ≥ 100 trap lines without PII", () => {
    expect(corpus.length).toBeGreaterThanOrEqual(200);
    const traps = corpus.filter((l) => l.group === "trap");
    expect(traps.length).toBeGreaterThanOrEqual(100);
    expect(traps.every((l) => l.spans.length === 0)).toBe(true);
  });

  test("recall ≥ 0.95 and precision ≥ 0.90 (M0)", () => {
    const { perKind, total, errors } = evaluate(corpus);
    const rows = Object.entries(perKind)
      .sort()
      .map(([k, s]) => `${k.padEnd(18)} P=${ratio(s.tp, s.tp + s.fp).toFixed(3)} R=${ratio(s.tp, s.tp + s.fn).toFixed(3)} tp=${s.tp} fp=${s.fp} fn=${s.fn}`);
    const recall = ratio(total.tp, total.tp + total.fn);
    const precision = ratio(total.tp, total.tp + total.fp);
    console.log([...rows, `TOTAL P=${precision.toFixed(3)} R=${recall.toFixed(3)}`, ...errors.slice(0, 40)].join("\n"));
    expect(recall).toBeGreaterThanOrEqual(0.95);
    expect(precision).toBeGreaterThanOrEqual(0.9);
  });

  test("traps produce no findings", () => {
    const noisy = corpus.filter((l) => l.group === "trap" && detect(l.text).length > 0);
    expect(noisy.map((l) => l.text)).toEqual([]);
  });
});
