// Generated by scripts/sync-fonts.mjs from the @fontsource/* packages — do not edit by hand.
// Platform fonts of design system v2 (ui-kit.yaml#platform_v2.fonts, D64): license and source per family.
import type { FontEntry } from "../tokens/fonts.js";

export const PLATFORM_FONTS: readonly FontEntry[] = [
  {
    family: "Inter",
    id: "inter",
    category: "sans-serif",
    weights: [400, 500, 600],
    license: "OFL-1.1",
    licenseFile: "LICENSE-inter.txt",
    attribution:
      "Copyright 2016 The Inter Project Authors (https://github.com/rsms/inter) Inter-Italic[opsz,wght].ttf: Copyright 2016 The Inter Project Authors (https://github.com/rsms/inter)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/inter@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "inter-cyrillic-400-f0bb5864.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7712,
      },
      {
        weight: 400,
        subset: "latin",
        file: "inter-latin-400-8909904a.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 23664,
      },
      {
        weight: 500,
        subset: "cyrillic",
        file: "inter-cyrillic-500-b77a86ec.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7900,
      },
      {
        weight: 500,
        subset: "latin",
        file: "inter-latin-500-f3779f1e.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 24272,
      },
      {
        weight: 600,
        subset: "cyrillic",
        file: "inter-cyrillic-600-6c2a37f8.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7972,
      },
      {
        weight: 600,
        subset: "latin",
        file: "inter-latin-600-f9a06e79.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 24452,
      },
    ],
  },
  {
    family: "Source Serif 4",
    id: "source-serif-4",
    category: "serif",
    weights: [400, 500],
    license: "OFL-1.1",
    licenseFile: "LICENSE-source-serif-4.txt",
    attribution: "Copyright 2014-2023 Adobe (http://www.adobe.com/), with Reserved Font Name 'Source'",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/source-serif-4@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "source-serif-4-cyrillic-400-4899e714.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 14172,
      },
      {
        weight: 400,
        subset: "latin",
        file: "source-serif-4-latin-400-02194deb.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 20088,
      },
      {
        weight: 500,
        subset: "cyrillic",
        file: "source-serif-4-cyrillic-500-5ee91efe.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 14780,
      },
      {
        weight: 500,
        subset: "latin",
        file: "source-serif-4-latin-500-d3e119de.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 21528,
      },
    ],
  },
];
