// Public pages of «Контент и блог» on the v2 front (screen generators): the list of articles with the rubric links, an
// article, a rubric, the list of the site's pages and a page. Each reads only what the role may (a visitor — published
// entries, the module's rowFilter) and finds an entry by the slug of its address. The body is plain text with
// «## » headings and «- » lists, drawn by React (never as HTML). On the v3 front these screens are the composer's
// (article-* and rubric-* patterns); here they are the plain pages of the ui-kit.
import { js } from "../screens/jsx.js";
import type { GenContext, ScreenContext } from "../types.js";
import { contentOptions, CONTENT_NAMES as N, CONTENT_ROUTES as R } from "./compile.js";

/** Helpers shared by the pages: ui/content/lib.tsx. */
export const CONTENT_LIB_FILE = "ui/content/lib.tsx";

/** Prefix of the pages of entries under a route with :slug («/blog/:slug» → «/blog/»). */
export const entryPrefix = (route: string): string => route.replace(/:slug$/, "");

export function contentLibSource(_ctx: GenContext): string {
  return `// Generated by the module «Контент и блог» (V3-24): helpers of its pages — texts, dates in Russian, the body of an
// entry (paragraphs, «## » headings, «- » lists as React elements) and the list of entries with links to their pages.
import { useParams } from "@wizard/sdk";
import { EmptyState, Loading, type Rec, useDataSource } from "@wizard/ui-kit";

export const text = (v: unknown): string | undefined => (typeof v === "string" && v.trim() !== "" ? v : undefined);

const DAY = new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });
const MOMENT = new Intl.DateTimeFormat("ru-RU", { day: "numeric", month: "long", year: "numeric" });

/** A date field in Russian (a calendar date as is, a moment in the visitor's time zone). */
export function day(v: unknown): string | undefined {
  if (typeof v !== "string" || !v) return undefined;
  const only = /^\\d{4}-\\d{2}-\\d{2}$/.test(v);
  const d = new Date(only ? v + "T00:00:00Z" : v);
  return Number.isNaN(d.getTime()) ? undefined : (only ? DAY : MOMENT).format(d);
}

/** The page of an entry: the prefix and its slug. */
export const entryHref = (prefix: string, slug: unknown): string => prefix + encodeURIComponent(String(slug ?? ""));

/** The slug of the address. */
export function useSlug(): string {
  return useParams<{ slug?: string }>().slug ?? "";
}

/** The entry of \`entity\` with this slug the role may read (null — none). */
export function useBySlug(entity: string, slug: string): { row: Rec | null; isLoading: boolean } {
  const r = useDataSource().useList<Rec>(entity, { filter: { ${N.slug}: slug || "-" }, pageSize: 1 });
  return { row: r.data?.items[0] ?? null, isLoading: r.isLoading };
}

const stack = { display: "grid", gap: 12, maxWidth: "70ch" } as const;
const list = { display: "grid", gap: 24, padding: 0, margin: "24px 0 0", listStyle: "none" } as const;
const chips = { display: "flex", flexWrap: "wrap", gap: 8, padding: 0, margin: "16px 0 0", listStyle: "none" } as const;
const chip = { display: "inline-flex", alignItems: "center", minHeight: 44, padding: "0 16px" } as const;

/** The body of an entry: paragraphs by blank lines, «## »/«### » headings, «- » lists; text only. */
export function Body({ source }: { source: unknown }) {
  const blocks = (text(source) ?? "").replace(/\\r\\n?/g, "\\n").split(/\\n\\s*\\n/).map((b) => b.trim()).filter(Boolean);
  return (
    <div style={stack} data-testid="content-body">
      {blocks.map((b, i) => {
        const key = "b" + String(i);
        const h = /^#{1,6}\\s+(.+)$/.exec(b);
        if (h && !b.includes("\\n")) return <h2 key={key}>{h[1]}</h2>;
        const lines = b.split("\\n");
        if (lines.every((l) => /^\\s*[-*•]\\s+/.test(l)))
          return (
            <ul key={key}>
              {lines.map((l, j) => (
                <li key={"l" + String(j)}>{l.replace(/^\\s*[-*•]\\s+/, "")}</li>
              ))}
            </ul>
          );
        return <p key={key} style={{ whiteSpace: "pre-line", overflowWrap: "anywhere" }}>{b}</p>;
      })}
    </div>
  );
}

/** Links to the rubrics (the current one marked). */
export function RubricLinks({ current, all }: { current?: string; all?: { label: string; href: string } }) {
  const r = useDataSource().useList<Rec>(${js(N.rubric)}, { sort: { field: ${js(N.sortOrder)}, dir: "asc" }, pageSize: 24 });
  const items = (r.data?.items ?? []).filter((x) => text(x.${N.name}) && text(x.${N.slug}));
  if (items.length === 0) return null;
  return (
    <nav aria-label="Рубрики">
      <ul style={chips}>
        {all ? (
          <li>
            <a href={all.href} style={chip} aria-current={current ? undefined : "page"}>{all.label}</a>
          </li>
        ) : null}
        {items.map((x) => (
          <li key={x.id}>
            <a href={entryHref(${js(entryPrefix(R.rubric))}, x.${N.slug})} style={chip} aria-current={x.${N.slug} === current ? "page" : undefined}>
              {text(x.${N.name})}
            </a>
          </li>
        ))}
      </ul>
    </nav>
  );
}

/** Entries of \`entity\` as a list: the date, the title linking to the entry's page, the announcement. */
export function EntryList(props: {
  entity: string;
  prefix: string;
  dateField: string;
  filter?: Record<string, unknown>;
  empty: string;
}) {
  const r = useDataSource().useList<Rec>(props.entity, {
    ...(props.filter ? { filter: props.filter } : {}),
    sort: { field: props.dateField, dir: "desc" },
    pageSize: 48,
  });
  if (r.isLoading) return <Loading />;
  const items = r.data?.items ?? [];
  if (items.length === 0) return <EmptyState text={props.empty} />;
  return (
    <ul style={list} data-testid="content-list">
      {items.map((x) => (
        <li key={x.id}>
          {day(x[props.dateField]) ? <p><time>{day(x[props.dateField])}</time></p> : null}
          <h2>
            <a href={entryHref(props.prefix, x.${N.slug})}>{text(x.${N.title}) ?? "Без названия"}</a>
          </h2>
          {text(x.${N.excerpt}) ? <p>{text(x.${N.excerpt})}</p> : null}
        </li>
      ))}
    </ul>
  );
}
`;
}

const MISSING = "Возможно, её убрали или адрес набран с ошибкой.";

/** /blog: the list of published articles with the rubric links. */
export function blogPage(ctx: ScreenContext): string {
  const o = contentOptions(ctx.params);
  return `// Generated by the module «Контент и блог» (V3-24): the list of articles.
import { LandingSection } from "@wizard/ui-kit";
import { EntryList${o.withRubrics ? ", RubricLinks" : ""} } from "../content/lib";

export default function ContentBlog() {
  return (
    <main>
      <LandingSection title=${js(o.blogTitle)} main>
${o.withRubrics ? `        <RubricLinks all={${js({ label: "Все", href: R.blog })}} />\n` : ""}        <EntryList entity=${js(N.article)} prefix=${js(entryPrefix(R.article))} dateField=${js(N.date)} empty="Статей пока нет — загляните позже" />
      </LandingSection>
    </main>
  );
}
`;
}

/** An entry page: the title as the h1, the date and the rubric (articles), the cover, the announcement and the body. */
function entryPage(ctx: ScreenContext, kind: "article" | "page"): string {
  const o = contentOptions(ctx.params);
  const article = kind === "article";
  const entity = article ? N.article : N.page;
  const back = article ? { label: o.blogTitle, href: R.blog } : { label: "Все страницы", href: R.pages };
  const rubric = article && o.withRubrics;
  return `// Generated by the module «Контент и блог» (V3-24): ${article ? "an article" : "a page of the site"} by the slug of the address.
import { EmptyState, LandingSection, Loading, type Rec, useDataSource } from "@wizard/ui-kit";
import { Body, day, entryHref, text, useBySlug, useSlug } from "../content/lib";

${
  rubric
    ? `function Rubric({ id }: { id: unknown }) {
  const r = useDataSource().useList<Rec>(${js(N.rubric)}, { pageSize: 24 });
  const row = (r.data?.items ?? []).find((x) => x.id === id);
  if (!row || !text(row.${N.name})) return null;
  return <a href={entryHref(${js(entryPrefix(R.rubric))}, row.${N.slug})}>{text(row.${N.name})}</a>;
}

`
    : ""
}export default function Content${article ? "Article" : "Page"}() {
  const slug = useSlug();
  const { row, isLoading } = useBySlug(${js(entity)}, slug);
  const files = useDataSource().useFiles();
  if (isLoading) return <main><Loading /></main>;
  if (!row || !text(row.${N.title}))
    return (
      <main>
        <LandingSection title="Страница не найдена" main>
          <EmptyState text=${js(MISSING)} action={<a href=${js(back.href)}>${back.label}</a>} />
        </LandingSection>
      </main>
    );
  const cover = text(row.${N.cover});
  return (
    <main>
      <LandingSection title={text(row.${N.title}) ?? ""} intro={text(row.${N.excerpt})} main>
        <article data-testid="content-entry">
${
  article
    ? `          <p>
            {day(row.${N.date}) ? <time>{day(row.${N.date})}</time> : null}
${rubric ? `            {" "}\n            <Rubric id={row.${N.rubricRef}} />\n` : ""}          </p>
`
    : ""
}          {cover ? <img src={files.imageSrc(cover, 960)} alt="" aria-hidden="true" style={{ width: "100%", height: "auto" }} /> : null}
          <Body source={row.${N.body}} />
          <p>
            <a href=${js(back.href)}>${back.label}</a>
          </p>
        </article>
      </LandingSection>
    </main>
  );
}
`;
}

export const articlePage = (ctx: ScreenContext): string => entryPage(ctx, "article");
export const sitePage = (ctx: ScreenContext): string => entryPage(ctx, "page");

/** /blog/rubric/:slug: the rubric's name and description, its articles and the other rubrics. */
export function rubricPage(ctx: ScreenContext): string {
  const o = contentOptions(ctx.params);
  return `// Generated by the module «Контент и блог» (V3-24): the articles of a rubric.
import { EmptyState, LandingSection, Loading } from "@wizard/ui-kit";
import { EntryList, RubricLinks, text, useBySlug, useSlug } from "../content/lib";

export default function ContentRubric() {
  const slug = useSlug();
  const { row, isLoading } = useBySlug(${js(N.rubric)}, slug);
  if (isLoading) return <main><Loading /></main>;
  if (!row || !text(row.${N.name}))
    return (
      <main>
        <LandingSection title="Рубрика не найдена" main>
          <EmptyState text=${js(MISSING)} action={<a href=${js(R.blog)}>${o.blogTitle}</a>} />
        </LandingSection>
      </main>
    );
  return (
    <main>
      <LandingSection title={text(row.${N.name}) ?? ""} intro={text(row.${N.description})} main>
        <RubricLinks current={slug} all={${js({ label: "Все", href: R.blog })}} />
        <EntryList entity=${js(N.article)} prefix=${js(entryPrefix(R.article))} dateField=${js(N.date)} filter={{ ${N.rubricRef}: row.id }} empty="В этой рубрике пока нет статей" />
      </LandingSection>
    </main>
  );
}
`;
}

/** /pages: the published pages of the site. */
export function pagesPage(_ctx: ScreenContext): string {
  return `// Generated by the module «Контент и блог» (V3-24): the pages of the site.
import { LandingSection } from "@wizard/ui-kit";
import { EntryList } from "../content/lib";

export default function ContentPages() {
  return (
    <main>
      <LandingSection title="Информация" main>
        <EntryList entity=${js(N.page)} prefix=${js(entryPrefix(R.page))} dateField=${js(N.updated)} empty="Страниц пока нет" />
      </LandingSection>
    </main>
  );
}
`;
}
