// Cabinet and start page generators (moved from the D75 template, packages/agents builder/template.ts, which now
// imports them): ui-kit components bind to entities through the data API under the role's permissions, so the pages
// need no server functions — a table, a card with status actions and create/edit forms per entity the role may read.
import type { AppSpec, Permission, PermissionOp } from "@wizard/appspec";
import { js, jsxEl, pascal } from "./jsx.js";

/** Permission of a role on an entity. */
export function permOf(spec: AppSpec, role: string, entity: string): Permission | undefined {
  return (spec.permissions ?? []).find((p) => p.role === role && p.entity === entity);
}

/** The role has the operation on the entity. */
export const can = (spec: AppSpec, role: string, entity: string, op: PermissionOp): boolean =>
  (permOf(spec, role, entity)?.ops ?? []).includes(op);

/** Fields the role sees in a list (not hidden, not qr_token or json), at most 6. */
export function columns(spec: AppSpec, role: string, entity: string): string[] {
  const e = spec.entities.find((x) => x.name === entity);
  const hidden = new Set(permOf(spec, role, entity)?.hiddenFields ?? []);
  return (e?.fields ?? [])
    .filter((f) => !hidden.has(f.name) && f.type !== "qr_token" && f.type !== "json")
    .map((f) => f.name)
    .slice(0, 6);
}

/** The status field of an entity: `status` of type enum, else the first enum field. */
export function statusField(spec: AppSpec, entity: string) {
  const e = spec.entities.find((x) => x.name === entity);
  const enums = (e?.fields ?? []).filter((f) => f.type === "enum" && f.enum?.length);
  return enums.find((f) => f.name === "status") ?? enums[0];
}

/** Cabinet page of a role: CabinetLayout with a section per entity (table, card with status actions, forms). */
export function cabinetPage(
  spec: AppSpec,
  role: string,
  roleLabel: string,
  entities: readonly string[],
): string {
  const parts: string[] = [];
  const sections: string[] = [];
  for (const name of entities) {
    const e = spec.entities.find((x) => x.name === name);
    if (!e) continue;
    const comp = `${pascal(name)}Section`;
    const cols = columns(spec, role, name);
    const st = can(spec, role, name, "update") ? statusField(spec, name) : undefined;
    const ro = new Set(permOf(spec, role, name)?.readonlyFields ?? []);
    const actions: string[] = [];
    if (st && !ro.has(st.name))
      for (const opt of st.enum ?? [])
        actions.push(
          `{ id: ${js(`to_${opt.value}`)}, label: ${js(opt.label)}, kind: "update", patch: { ${st.name}: ${js(opt.value)} }, visible: (r: Doc) => r.${st.name} !== ${js(opt.value)} }`,
        );
    if (can(spec, role, name, "delete"))
      actions.push(
        `{ id: "delete", label: "Удалить", tone: "danger", kind: "delete", confirm: "Удалить запись?" }`,
      );
    const canCreate = can(spec, role, name, "create");
    const canEdit = can(spec, role, name, "update");
    parts.push(
      [
        `function ${comp}() {`,
        `  type Doc = ClientDoc<${js(name)}>;`,
        "  const [selected, setSelected] = useState<string | null>(null);",
        '  const [mode, setMode] = useState<"view" | "edit" | "create">("view");',
        "  return (",
        "    <>",
        `      <DataTable entity={${js(name)}} columns={${js([...cols, "created_at"])}} defaultSort={{ field: "created_at", dir: "desc" }} searchable onRowClick={(r: Doc) => { setSelected(r.id); setMode("view"); }} emptyText="Записей пока нет" />`,
        `      {selected && mode === "view" ? (`,
        "        <>",
        `          <RecordCard entity={${js(name)}} id={selected} actions={[${actions.join(", ")}]} onDeleted={() => setSelected(null)} />`,
        canEdit
          ? '          <Button variant="secondary" onClick={() => setMode("edit")}>Изменить</Button>'
          : "",
        '          <Button variant="ghost" onClick={() => setSelected(null)}>Закрыть</Button>',
        "        </>",
        "      ) : null}",
        canEdit
          ? `      {selected && mode === "edit" ? (\n        <RecordForm key={selected} entity={${js(name)}} mode="edit" id={selected} onSuccess={() => setMode("view")} onCancel={() => setMode("view")} />\n      ) : null}`
          : "",
        canCreate
          ? `      {mode === "create" ? (\n        <RecordForm entity={${js(name)}} mode="create" onSuccess={() => setMode("view")} onCancel={() => setMode("view")} />\n      ) : (\n        <Button variant="primary" onClick={() => { setSelected(null); setMode("create"); }}>Добавить</Button>\n      )}`
          : "",
        "    </>",
        "  );",
        "}",
      ]
        .filter((l) => l !== "")
        .join("\n"),
    );
    sections.push(`{ id: ${js(name)}, label: ${js(e.label)}, content: <${comp} /> }`);
  }
  return [
    "// Generated by the template (D75): a cabinet of the role — table, card with status actions, create and edit forms.",
    'import { type ClientDoc, useState } from "@wizard/sdk";',
    'import { Button, CabinetLayout, DataTable, RecordCard, RecordForm } from "@wizard/ui-kit";',
    "",
    "export default function Cabinet() {",
    "  return (",
    `    <CabinetLayout title={${js(`Кабинет: ${roleLabel}`)}} defaultSection={${js(entities[0])}} sections={[${sections.join(", ")}]} />`,
    "  );",
    "}",
    "",
    ...parts.flatMap((p) => [p, ""]),
  ].join("\n");
}

/** Start page of a system without a landing: a Hero with the title and a button into the first cabinet. */
export function startPage(title: string, subtitle: string | undefined, cabinet: string | undefined): string {
  return [
    "// Generated by the template (D75): the start page of a system without a public role.",
    'import { Hero } from "@wizard/ui-kit";',
    "",
    "export default function Home() {",
    "  return (",
    `    ${jsxEl("Hero", [
      ["title", title],
      ["subtitle", subtitle],
      ["primary", cabinet ? { label: "Открыть кабинет", href: cabinet } : undefined],
      ["variant", "centered", "lit"],
    ])}`,
    "  );",
    "}",
    "",
  ].join("\n");
}

/** Route and file of the cabinet of a login role: the first (owner) — /cabinet, the others — /cabinet-<role>. */
export function cabinetRoute(role: string, first: boolean): { route: string; file: string } {
  return first
    ? { route: "/cabinet", file: "ui/pages/Cabinet.tsx" }
    : { route: `/cabinet-${role.replace(/_/g, "-")}`, file: `ui/pages/Cabinet${pascal(role)}.tsx` };
}
