// Generated by scripts/sync-fonts.mjs from the @fontsource/* packages — do not edit by hand.
// Theme fonts served by the runtime from /_wizard/fonts (ui-kit.yaml#tokens.fonts, D64): license and source per family.
import type { FontEntry } from "./fonts.js";

export const FONT_CATALOG: readonly FontEntry[] = [
  {
    family: "Onest",
    id: "onest",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-onest.txt",
    attribution: "Copyright 2021 The Onest Project Authors (https://github.com/simpals/onest)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/onest@5.3.1",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "onest-cyrillic-400-51adb4c8.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 6680,
      },
      {
        weight: 400,
        subset: "latin",
        file: "onest-latin-400-93dfb945.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 14748,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "onest-cyrillic-700-0fcb8fa2.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 6800,
      },
      {
        weight: 700,
        subset: "latin",
        file: "onest-latin-700-d48e1aee.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 15488,
      },
    ],
  },
  {
    family: "Inter Tight",
    id: "inter-tight",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-inter-tight.txt",
    attribution:
      "Copyright 2022 The Inter Project Authors (https://github.com/rsms/inter-tight) InterTight-Italic[wght].ttf: Copyright 2022 The Inter Project Authors (https://github.com/rsms/inter-tight)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/inter-tight@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "inter-tight-cyrillic-400-dacf424a.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 6784,
      },
      {
        weight: 400,
        subset: "latin",
        file: "inter-tight-latin-400-6f32da94.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 22016,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "inter-tight-cyrillic-700-c0449c8a.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 6992,
      },
      {
        weight: 700,
        subset: "latin",
        file: "inter-tight-latin-700-9c4f02f3.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 22748,
      },
    ],
  },
  {
    family: "Manrope",
    id: "manrope",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-manrope.txt",
    attribution: "Copyright 2019 The Manrope Project Authors (https://github.com/sharanda/manrope)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/manrope@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "manrope-cyrillic-400-5a987d14.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7840,
      },
      {
        weight: 400,
        subset: "latin",
        file: "manrope-latin-400-849290ef.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 14108,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "manrope-cyrillic-700-2ad647b9.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7852,
      },
      {
        weight: 700,
        subset: "latin",
        file: "manrope-latin-700-d2a12c85.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 14212,
      },
    ],
  },
  {
    family: "PT Sans",
    id: "pt-sans",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-pt-sans.txt",
    attribution:
      "Copyright © 2009 ParaType Ltd. All rights reserved. PT_Sans-Web-Italic.ttf: Copyright © 2009 ParaType Ltd. All rights reserved. PT_Sans-Web-Bold.ttf: Copyright © 2009 ParaType Ltd. All rights reserved. PT_Sans-Web-BoldItalic.ttf: Copyright © 2009 ParaType Ltd. All rights reserved.",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/pt-sans@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "pt-sans-cyrillic-400-f283e584.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 28548,
      },
      {
        weight: 400,
        subset: "latin",
        file: "pt-sans-latin-400-2dea6190.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 45532,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "pt-sans-cyrillic-700-05795f79.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 30164,
      },
      {
        weight: 700,
        subset: "latin",
        file: "pt-sans-latin-700-05ea99a4.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 47180,
      },
    ],
  },
  {
    family: "IBM Plex Sans",
    id: "ibm-plex-sans",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-ibm-plex-sans.txt",
    attribution:
      "Copyright 2019 IBM Corp. All rights reserved. IBMPlexSans-Italic[wdth,wght].ttf: Copyright 2019 IBM Corp. All rights reserved.",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/ibm-plex-sans@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "ibm-plex-sans-cyrillic-400-69afad88.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 14800,
      },
      {
        weight: 400,
        subset: "latin",
        file: "ibm-plex-sans-latin-400-3b646991.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 22588,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "ibm-plex-sans-cyrillic-700-40540598.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 14572,
      },
      {
        weight: 700,
        subset: "latin",
        file: "ibm-plex-sans-latin-700-42e7b0c1.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 22832,
      },
    ],
  },
  {
    family: "Golos Text",
    id: "golos-text",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-golos-text.txt",
    attribution: "Copyright 2019 The Golos Text Project Authors (https://github.com/googlefonts/golos-text)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/golos-text@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "golos-text-cyrillic-400-15a5cbad.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 6960,
      },
      {
        weight: 400,
        subset: "latin",
        file: "golos-text-latin-400-c8246f55.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 11992,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "golos-text-cyrillic-700-42db867d.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 7108,
      },
      {
        weight: 700,
        subset: "latin",
        file: "golos-text-latin-700-1ac7742b.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 12380,
      },
    ],
  },
  {
    family: "PT Serif",
    id: "pt-serif",
    category: "serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-pt-serif.txt",
    attribution:
      "Copyright © 2010 ParaType Ltd. All rights reserved. PT_Serif-Web-Italic.ttf: Copyright © 2010 ParaType Ltd. All rights reserved. PT_Serif-Web-Bold.ttf: Copyright © 2010 ParaType Ltd. All rights reserved. PT_Serif-Web-BoldItalic.ttf: Copyright © 2010 ParaType Ltd. All rights reserved.",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/pt-serif@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "pt-serif-cyrillic-400-050aee25.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 22128,
      },
      {
        weight: 400,
        subset: "latin",
        file: "pt-serif-latin-400-4271064a.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 33116,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "pt-serif-cyrillic-700-bec4e724.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 20916,
      },
      {
        weight: 700,
        subset: "latin",
        file: "pt-serif-latin-700-bf23a7a4.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 29588,
      },
    ],
  },
  {
    family: "Lora",
    id: "lora",
    category: "serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-lora.txt",
    attribution:
      'Copyright 2011 The Lora Project Authors (https://github.com/cyrealtype/Lora-Cyrillic), with Reserved Font Name "Lora". Lora-Italic[wght].ttf: Copyright 2011 The Lora Project Authors (https://github.com/cyrealtype/Lora-Cyrillic), with Reserved Font Name "Lora".',
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/lora@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "lora-cyrillic-400-d1f41090.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 11480,
      },
      {
        weight: 400,
        subset: "latin",
        file: "lora-latin-400-ac079950.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 21148,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "lora-cyrillic-700-f0550b4d.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 11388,
      },
      {
        weight: 700,
        subset: "latin",
        file: "lora-latin-700-c05fd528.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 21044,
      },
    ],
  },
  {
    family: "Unbounded",
    id: "unbounded",
    category: "sans-serif",
    weights: [400, 700],
    license: "OFL-1.1",
    licenseFile: "LICENSE-unbounded.txt",
    attribution: "Copyright 2022 The Unbounded Project Authors (https://github.com/googlefonts/unbounded)",
    source: "Google Fonts (https://github.com/google/fonts), npm @fontsource/unbounded@5.3.0",
    files: [
      {
        weight: 400,
        subset: "cyrillic",
        file: "unbounded-cyrillic-400-31c19470.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 12208,
      },
      {
        weight: 400,
        subset: "latin",
        file: "unbounded-latin-400-b0a91553.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 19980,
      },
      {
        weight: 700,
        subset: "cyrillic",
        file: "unbounded-cyrillic-700-fdc2a845.woff2",
        unicodeRange: "U+0301,U+0400-045F,U+0490-0491,U+04B0-04B1,U+2116",
        bytes: 12812,
      },
      {
        weight: 700,
        subset: "latin",
        file: "unbounded-latin-700-477fa230.woff2",
        unicodeRange:
          "U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD",
        bytes: 21092,
      },
    ],
  },
];
