// Archetypes of the v3 art director (D77 (6), builder-v3.md#C2): 14 directions as data. Each one states why it exists,
// what rut it avoids, its font pairs from the self-hosted catalog (D64, design-agent-catalog.md#A6), palette rules
// (OKLCH from the brand colour, palette.ts), type scale, radius, density, grid, motion and imagery, and the niches,
// goals and system classes it fits (pickArchetype). Tokens are computed from this by code (system.ts), never by a model.
import type { DESIGN_VOICES } from "@wizard/appspec";

export type DesignVoice = (typeof DESIGN_VOICES)[number];

export const ARCHETYPE_IDS = [
  "editorial",
  "swiss",
  "luxury",
  "soft_organic",
  "warm_craft",
  "tech_minimal",
  "bold_poster",
  "calm_medical",
  "playful_kids",
  "neat_brutalism",
  "classic_business",
  "glossy_magazine",
  "natural",
  "night_contrast",
] as const;
export type ArchetypeId = (typeof ARCHETYPE_IDS)[number];

/** What the system is for (goals of the brief, recognised by GOAL_STEMS in pick.ts). */
export type GoalTag = "leads" | "booking" | "sales" | "content" | "trust" | "operations" | "events";
/** Output classes of v3 (D77 (12)): business site, services with booking, CRM/admin, online shop. */
export type SystemClass = "site" | "booking" | "admin" | "shop";

export type TypeScaleId = "calm" | "classic" | "dramatic";
export type RadiusSetId = "sharp" | "crisp" | "soft" | "round";
export type Density = "compact" | "regular" | "airy";
export type GridLayout = "symmetric" | "asymmetric" | "modular" | "centered" | "split";
export type MotionProfile = "still" | "calm" | "lively";
/** Entrance of the hero (only one per page, catalog M01): none, fade, rise (opacity + 12 px), clip (reveal by mask). */
export type MotionEntrance = "none" | "fade" | "rise" | "clip";
export type MotionHover = "none" | "lift" | "underline" | "tint";
export type ImageTreatment = "natural" | "warm-grade" | "soft-grade" | "high-contrast" | "monochrome";
export type ImageRatio = "3:2" | "4:5" | "1:1" | "16:9";
export type ImageFrame = "full-bleed" | "framed" | "rounded";
/** How the brand colour is used: signal — CTA and highlights only; fill — large accent surfaces; band — one accent band. */
export type AccentUse = "signal" | "fill" | "band";
/** Surface depth (catalog E2): flat — air only, outline — 1–2 px lines, soft — a light shadow tinted by ink. */
export type Depth = "flat" | "outline" | "soft";
/** Alternate band (surface-alt): a tint of the accent, a deeper neutral, or a clearly deeper neutral. */
export type BandRule = "tint" | "neutral" | "deep";
export type Accent2Rule = "none" | "analogous" | "complement" | "split";

export interface FontPair {
  display: string;
  text: string;
  /** Why this face (required when either is a model default, fonts.ts NEEDS_REASON_FONTS); not «niche → serif». */
  why?: string;
}

export interface PaletteRules {
  /** Hues (OKLCH degrees) of the accent when the client has no brand colour; the seed picks one. */
  hues: readonly number[];
  /** Lightness and chroma range of that accent (fill in the archetype's own scheme). */
  accentL: readonly [number, number];
  accentC: readonly [number, number];
  /** Hue of the neutrals: "brand" — tinted by the accent hue, a number — a fixed hue. */
  neutralHue: "brand" | number;
  /** Chroma of the neutrals (page, surfaces, ink); the light page is never cream (catalog C02). */
  neutralC: number;
  /** Page lightness in the light and dark schemes. */
  bgL: { light: number; dark: number };
  band: BandRule;
  accent2: Accent2Rule;
  /** Scheme the page starts in. */
  scheme: "light" | "dark";
  accentUse: AccentUse;
  depth: Depth;
}

export interface Archetype {
  id: ArchetypeId;
  /** Russian name shown to the owner («три направления», V3-09). */
  name: string;
  /** Why the direction exists and what it does — the passport line for the owner and the critic. */
  why: string;
  /** The rut of the niche it deliberately avoids (catalog D3, B). */
  avoid: string;
  fontPairs: readonly FontPair[];
  /** Display weight (the catalog ships 400 and 700 only: no synthetic weights, catalog T12). */
  displayWeight: 400 | 700;
  /** Headings in capitals (short display lines only, catalog T10). */
  upper: boolean;
  /** Display tracking: tight −0.02 em, normal −0.01 em (capitals: +0.01 em). */
  tracking: "tight" | "normal";
  scales: readonly TypeScaleId[];
  radius: readonly RadiusSetId[];
  /** Controls (buttons, inputs) as pills or with the radius of the set. */
  controls: "pill" | "match";
  density: readonly Density[];
  /** Grid: columns, container, text measure (ch) and the layouts the seed picks from. */
  grid: { columns: number; maxWidth: number; measure: number; layouts: readonly GridLayout[] };
  motion: { profile: MotionProfile; entrance: MotionEntrance; hover: MotionHover };
  imagery: { style: string; treatment: ImageTreatment; ratio: ImageRatio; frame: ImageFrame };
  palette: PaletteRules;
  /** Lower-case Russian stems of niches it fits (matched as substrings of the niche). */
  niches: readonly string[];
  goals: readonly GoalTag[];
  classes: readonly SystemClass[];
  /** Voices of texts that suit it, the first is the default. */
  voices: readonly DesignVoice[];
}

export const ARCHETYPES: readonly Archetype[] = [
  {
    id: "editorial",
    name: "Редакционный",
    why: "Доверие через содержание: книжная антиква в заголовках, узкая колонка для чтения, спокойная асимметричная сетка, цвет только как сигнал.",
    avoid: "подписи над каждым заголовком, три карточки с иконками, курсив в первом экране",
    fontPairs: [
      { display: "Literata", text: "Commissioner" },
      { display: "Literata", text: "Source Sans 3" },
      { display: "Alegreya", text: "Onest" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic", "dramatic"],
    radius: ["sharp", "crisp"],
    controls: "match",
    density: ["airy", "regular"],
    grid: { columns: 12, maxWidth: 1200, measure: 68, layouts: ["asymmetric", "centered"] },
    motion: { profile: "calm", entrance: "fade", hover: "underline" },
    imagery: {
      style:
        "документальные кадры без постановки: люди за работой, детали, естественный свет; подписи под фото",
      treatment: "natural",
      ratio: "3:2",
      frame: "framed",
    },
    palette: {
      hues: [255, 28, 150],
      accentL: [0.42, 0.52],
      accentC: [0.08, 0.13],
      neutralHue: "brand",
      neutralC: 0.006,
      bgL: { light: 0.985, dark: 0.17 },
      band: "neutral",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "flat",
    },
    niches: [
      "блог",
      "медиа",
      "журнал",
      "издател",
      "книг",
      "консалт",
      "исследован",
      "аналитик",
      "нко",
      "фонд",
      "подписк",
      "автор",
      "эксперт",
      "психолог",
      "лектор",
      "архитект",
      "юрист",
      "юридич",
      "адвокат",
      "школ",
    ],
    goals: ["content", "trust", "leads"],
    classes: ["site"],
    voices: ["calm", "formal", "refined"],
  },
  {
    id: "swiss",
    name: "Швейцарская сетка",
    why: "Порядок и ясность: строгая модульная сетка, один гротеск разной насыщенности, крупный кегль и асимметрия; характер несёт один сигнальный цвет.",
    avoid: "мягкие тени, градиенты, скругления ради скруглений",
    fontPairs: [
      { display: "Onest", text: "Onest" },
      { display: "Commissioner", text: "Commissioner" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "tight",
    scales: ["dramatic"],
    radius: ["sharp"],
    controls: "match",
    density: ["regular", "compact"],
    grid: { columns: 12, maxWidth: 1360, measure: 62, layouts: ["modular", "asymmetric"] },
    motion: { profile: "still", entrance: "none", hover: "tint" },
    imagery: {
      style: "предметная и архитектурная съёмка, чистый фон, геометрия кадра, без людей в постановке",
      treatment: "high-contrast",
      ratio: "4:5",
      frame: "full-bleed",
    },
    palette: {
      hues: [27, 255, 145],
      accentL: [0.5, 0.58],
      accentC: [0.17, 0.21],
      neutralHue: 250,
      neutralC: 0.002,
      bgL: { light: 0.99, dark: 0.15 },
      band: "neutral",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "flat",
    },
    niches: [
      "архитект",
      "дизайн",
      "студи",
      "агентств",
      "бюро",
      "продакшн",
      "разработк",
      "it-",
      "веб",
      "типограф",
      "полиграф",
      "b2b",
      "инжиниринг",
      "клиник",
      "стоматолог",
      "юрист",
      "юридич",
      "недвижим",
      "одежд",
      "керамик",
      "мебел",
    ],
    goals: ["leads", "trust"],
    classes: ["site", "admin"],
    voices: ["formal", "refined", "bold"],
  },
  {
    id: "luxury",
    name: "Люкс с антиквой",
    why: "Дорого без золота и курсива: высококонтрастная антиква крупным кеглем, много воздуха, тонкие линии и глубокий сдержанный цвет.",
    avoid: "крем с золотом, курсивная антиква в первом экране, рукописные шрифты",
    fontPairs: [
      {
        display: "Cormorant Garamond",
        text: "Commissioner",
        why: "контраст штрихов Cormorant раскрывается только на крупном кегле: он стоит лишь в заголовках от 32 px, прямым начертанием; текст — на спокойном гротеске",
      },
      {
        display: "Cormorant Garamond",
        text: "Onest",
        why: "контраст штрихов Cormorant раскрывается только на крупном кегле: он стоит лишь в заголовках от 32 px, прямым начертанием; текст — на нейтральном гротеске",
      },
    ],
    displayWeight: 400,
    upper: false,
    tracking: "normal",
    scales: ["dramatic"],
    radius: ["sharp"],
    controls: "match",
    density: ["airy"],
    grid: { columns: 12, maxWidth: 1200, measure: 60, layouts: ["centered", "split"] },
    motion: { profile: "calm", entrance: "fade", hover: "underline" },
    imagery: {
      style: "студийный рассеянный свет, крупные планы фактур и деталей, спокойный однотонный фон",
      treatment: "soft-grade",
      ratio: "4:5",
      frame: "framed",
    },
    palette: {
      hues: [355, 165, 240],
      accentL: [0.3, 0.4],
      accentC: [0.06, 0.11],
      neutralHue: "brand",
      neutralC: 0.006,
      bgL: { light: 0.975, dark: 0.14 },
      band: "neutral",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "flat",
    },
    niches: [
      "ювелир",
      "украшен",
      "свадеб",
      "торжеств",
      "бутик",
      "премиум",
      "парфюм",
      "фотограф",
      "видеограф",
      "дизайнер одежд",
      "отель",
      "винн",
      "часов",
      "ателье",
      "салон",
      "интерьер",
      "недвижим",
      "маникюр",
      "космет",
    ],
    goals: ["trust", "sales", "booking"],
    classes: ["site", "shop", "booking"],
    voices: ["refined", "calm"],
  },
  {
    id: "soft_organic",
    name: "Мягкий органический",
    why: "Спокойствие и забота о теле: плавные формы, большие скругления, приглушённые природные тона и мягкие тени.",
    avoid: "пастельная радуга, фото на природе вместо работы, эмодзи и иконки-листики",
    fontPairs: [
      {
        display: "Lora",
        text: "Wix Madefor Text",
        why: "округлые мягкие засечки Lora поддерживают скруглённые формы интерфейса; Lora только в заголовках, текст — на разборчивом гротеске",
      },
      { display: "Alegreya", text: "Wix Madefor Text" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["calm", "classic"],
    radius: ["round"],
    controls: "pill",
    density: ["airy"],
    grid: { columns: 12, maxWidth: 1200, measure: 64, layouts: ["split", "centered"] },
    motion: { profile: "calm", entrance: "rise", hover: "lift" },
    imagery: {
      style: "мягкий дневной свет, натуральные материалы, руки и процесс без крупных лиц",
      treatment: "warm-grade",
      ratio: "4:5",
      frame: "rounded",
    },
    palette: {
      hues: [150, 40, 195],
      accentL: [0.45, 0.55],
      accentC: [0.05, 0.09],
      neutralHue: "brand",
      neutralC: 0.01,
      bgL: { light: 0.975, dark: 0.17 },
      band: "tint",
      accent2: "analogous",
      scheme: "light",
      accentUse: "signal",
      depth: "soft",
    },
    niches: [
      "спа",
      "массаж",
      "йог",
      "пилатес",
      "косметолог",
      "нутрициолог",
      "психолог",
      "ретрит",
      "ароматер",
      "мыловар",
      "велнес",
      "wellness",
      "дул",
      "натуральн",
      "маникюр",
      "бров",
      "ресниц",
      "космет",
      "клиник",
      "развивающ",
      "монтессори",
    ],
    goals: ["booking", "trust"],
    classes: ["booking", "site", "shop"],
    voices: ["calm", "warm"],
  },
  {
    id: "warm_craft",
    name: "Тёплый ремесленный",
    why: "Сделано руками: тёплая антиква с характером, фактурные фото процесса и сочный цвет; хочется зайти и попробовать.",
    avoid: "кремовый фон с рукописным шрифтом, стоковые торты и кофе с сердечком",
    fontPairs: [
      { display: "Piazzolla", text: "Source Sans 3" },
      { display: "Piazzolla", text: "Commissioner" },
      { display: "Alegreya", text: "Alegreya Sans" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic", "calm"],
    radius: ["soft", "round"],
    controls: "match",
    density: ["regular", "airy"],
    grid: { columns: 12, maxWidth: 1200, measure: 64, layouts: ["asymmetric", "split"] },
    motion: { profile: "calm", entrance: "rise", hover: "lift" },
    imagery: {
      style: "процесс и руки мастера, продукт крупным планом, дневной свет из окна, живые фактуры",
      treatment: "warm-grade",
      ratio: "3:2",
      frame: "rounded",
    },
    palette: {
      hues: [35, 60, 145],
      accentL: [0.45, 0.55],
      accentC: [0.1, 0.15],
      neutralHue: "brand",
      neutralC: 0.008,
      bgL: { light: 0.98, dark: 0.17 },
      band: "tint",
      accent2: "analogous",
      scheme: "light",
      accentUse: "fill",
      depth: "soft",
    },
    niches: [
      "пекарн",
      "кондитер",
      "торт",
      "выпечк",
      "кафе",
      "кофейн",
      "кофе",
      "ремесл",
      "хендмейд",
      "ручн",
      "гончар",
      "керамик",
      "сыровар",
      "пивовар",
      "столяр",
      "мебел",
      "шоколад",
    ],
    goals: ["sales", "leads", "booking"],
    classes: ["site", "shop"],
    voices: ["warm", "friendly"],
  },
  {
    id: "tech_minimal",
    name: "Технологичный минимализм",
    why: "Быстро и понятно: ровный гротеск, точная сетка, табличные цифры и холодные нейтральные тона без украшений; подходит рабочим экранам и сервисам.",
    avoid: "фиолетовые градиенты, 3D-шары и изометрия, моноширинный как костюм технологичности",
    fontPairs: [
      { display: "Commissioner", text: "Golos Text" },
      {
        display: "IBM Plex Sans",
        text: "Onest",
        why: "IBM Plex Sans держит экраны с числами: табличные цифры и инженерная ровность, а не образ «технологий»",
      },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "tight",
    scales: ["classic", "calm"],
    radius: ["crisp", "soft"],
    controls: "match",
    density: ["compact", "regular"],
    grid: { columns: 12, maxWidth: 1280, measure: 64, layouts: ["modular", "symmetric"] },
    motion: { profile: "calm", entrance: "fade", hover: "tint" },
    imagery: {
      style: "реальные экраны продукта и рабочие места, нейтральный свет, без 3D-шаров и изометрии",
      treatment: "natural",
      ratio: "16:9",
      frame: "framed",
    },
    palette: {
      hues: [250, 215, 150],
      accentL: [0.48, 0.56],
      accentC: [0.12, 0.17],
      neutralHue: 250,
      neutralC: 0.008,
      bgL: { light: 0.985, dark: 0.16 },
      band: "neutral",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "outline",
    },
    niches: [
      "crm",
      "срм",
      "saas",
      "сервис",
      "учёт",
      "учет",
      "логист",
      "склад",
      "автоматизац",
      "финтех",
      "диспетчер",
      "админ",
      "аналитик",
      "телеком",
      "it-",
      "айти",
      "недвижим",
      "клиник",
    ],
    goals: ["operations", "leads"],
    classes: ["admin", "site"],
    voices: ["formal", "friendly"],
  },
  {
    id: "bold_poster",
    name: "Смелый плакатный",
    why: "Как афиша события: узкие плакатные заголовки огромным кеглем, капс до трёх слов, резкие углы, плотный ритм и цвет на целую полосу.",
    avoid: "тёмный фон с неоном и глитчем, бегущие строки и счётчики",
    fontPairs: [
      { display: "Alumni Sans", text: "Literata" },
      { display: "Sofia Sans Extra Condensed", text: "Onest" },
      {
        display: "Unbounded",
        text: "Onest",
        why: "широкий громкий гротеск оправдан только в коротких заголовках событий до четырёх слов; чередуется с узкими плакатными",
      },
    ],
    displayWeight: 700,
    upper: true,
    tracking: "normal",
    scales: ["dramatic"],
    radius: ["sharp"],
    controls: "match",
    density: ["compact", "regular"],
    grid: { columns: 12, maxWidth: 1360, measure: 60, layouts: ["asymmetric", "modular"] },
    motion: { profile: "lively", entrance: "clip", hover: "tint" },
    imagery: {
      style: "сцена, публика и движение, вечерний контрастный свет, крупный план",
      treatment: "high-contrast",
      ratio: "16:9",
      frame: "full-bleed",
    },
    palette: {
      hues: [28, 230, 145],
      accentL: [0.5, 0.6],
      accentC: [0.16, 0.21],
      neutralHue: "brand",
      neutralC: 0.006,
      bgL: { light: 0.97, dark: 0.14 },
      band: "deep",
      accent2: "complement",
      scheme: "light",
      accentUse: "fill",
      depth: "flat",
    },
    niches: [
      "мероприят",
      "событи",
      "фестивал",
      "концерт",
      "вечеринк",
      "квиз",
      "афиш",
      "конференц",
      "форум",
      "турнир",
      "единоборств",
      "бокс",
      "кроссфит",
      "фитнес",
      "спорт",
      "театр",
      "одежд",
      "стритвир",
      "детск",
    ],
    goals: ["events", "sales", "leads"],
    classes: ["site", "shop"],
    voices: ["bold"],
  },
  {
    id: "calm_medical",
    name: "Спокойный медицинский",
    why: "Спокойно и надёжно: разборчивое суперсемейство, прохладные чистые тона, мягкие формы, крупные цены и лицензии на виду.",
    avoid: "белый с голубым и стоковый врач, иконки-сердечки и крестики",
    fontPairs: [
      { display: "Wix Madefor Display", text: "Wix Madefor Text" },
      { display: "Wix Madefor Display", text: "Source Sans 3" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic", "calm"],
    radius: ["soft", "round"],
    controls: "match",
    density: ["airy", "regular"],
    grid: { columns: 12, maxWidth: 1200, measure: 66, layouts: ["symmetric", "split"] },
    motion: { profile: "calm", entrance: "fade", hover: "tint" },
    imagery: {
      style: "светлые кабинеты, специалист за работой, оборудование крупным планом, без медицинских штампов",
      treatment: "natural",
      ratio: "3:2",
      frame: "rounded",
    },
    palette: {
      hues: [190, 230, 160],
      accentL: [0.42, 0.5],
      accentC: [0.07, 0.11],
      neutralHue: "brand",
      neutralC: 0.008,
      bgL: { light: 0.985, dark: 0.16 },
      band: "tint",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "soft",
    },
    niches: [
      "клиник",
      "стоматолог",
      "врач",
      "медицин",
      "медцентр",
      "ветеринар",
      "ветклиник",
      "лаборатор",
      "анализ",
      "остеопат",
      "реабилит",
      "аптек",
      "оптик",
      "педиатр",
      "психотерап",
    ],
    goals: ["booking", "trust"],
    classes: ["booking", "site"],
    voices: ["calm", "formal"],
  },
  {
    id: "playful_kids",
    name: "Игривый детский",
    why: "Радостно без пастельной радуги: крупные округлые заголовки, насыщенные цвета на светлом фоне, большие скругления и живое движение.",
    avoid: "пастельная радуга, мультяшные персонажи, клей-морфизм",
    fontPairs: [
      {
        display: "Unbounded",
        text: "Onest",
        why: "широкие округлые формы Unbounded читаются как игра и детьми, и родителями; только короткие заголовки",
      },
      { display: "Alegreya Sans", text: "Onest" },
      {
        display: "Unbounded",
        text: "Wix Madefor Text",
        why: "широкие округлые формы Unbounded читаются как игра и детьми, и родителями; только короткие заголовки",
      },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic"],
    radius: ["round"],
    controls: "pill",
    density: ["regular"],
    grid: { columns: 12, maxWidth: 1200, measure: 62, layouts: ["split", "modular"] },
    motion: { profile: "lively", entrance: "rise", hover: "lift" },
    imagery: {
      style: "занятия и игра крупным планом, яркий дневной свет, без постановочных стоковых улыбок",
      treatment: "natural",
      ratio: "1:1",
      frame: "rounded",
    },
    palette: {
      hues: [35, 145, 250],
      accentL: [0.5, 0.6],
      accentC: [0.15, 0.19],
      neutralHue: "brand",
      neutralC: 0.01,
      bgL: { light: 0.985, dark: 0.17 },
      band: "tint",
      accent2: "split",
      scheme: "light",
      accentUse: "fill",
      depth: "soft",
    },
    niches: [
      "детск",
      "детей",
      "дети",
      "ребён",
      "ребен",
      "кружок",
      "кружк",
      "детский сад",
      "лагер",
      "развивающ",
      "батут",
      "праздник",
      "аниматор",
      "логопед",
      "игров",
    ],
    goals: ["booking", "leads"],
    classes: ["booking", "site"],
    voices: ["friendly", "warm"],
  },
  {
    id: "neat_brutalism",
    name: "Аккуратный брутализм",
    why: "Честная конструкция: видимая сетка, толстые линии, прямые углы и плотный узкий гротеск; аккуратный — значит с выверенными отступами и контрастом.",
    avoid: "оранжевый с серым и каска, чёрный с красным и неон",
    fontPairs: [
      { display: "Sofia Sans Extra Condensed", text: "Sofia Sans" },
      {
        display: "Alumni Sans",
        text: "IBM Plex Sans",
        why: "IBM Plex Sans в тексте даёт инженерную сухость и табличные цифры, нужные прайсам и сметам",
      },
    ],
    displayWeight: 700,
    upper: true,
    tracking: "normal",
    scales: ["dramatic"],
    radius: ["sharp"],
    controls: "match",
    density: ["compact"],
    grid: { columns: 12, maxWidth: 1360, measure: 60, layouts: ["modular", "asymmetric"] },
    motion: { profile: "still", entrance: "none", hover: "tint" },
    imagery: {
      style: "рабочий процесс и инструменты, фактуры металла, дерева и бетона, жёсткий боковой свет",
      treatment: "monochrome",
      ratio: "3:2",
      frame: "framed",
    },
    palette: {
      hues: [85, 40, 135],
      accentL: [0.7, 0.82],
      accentC: [0.15, 0.19],
      neutralHue: 90,
      neutralC: 0.003,
      bgL: { light: 0.965, dark: 0.15 },
      band: "deep",
      accent2: "none",
      scheme: "light",
      accentUse: "fill",
      depth: "outline",
    },
    niches: [
      "ремонт",
      "отделк",
      "строит",
      "стройк",
      "автосервис",
      "шиномонтаж",
      "барбер",
      "мастерск",
      "производств",
      "металл",
      "сварк",
      "грузоперевоз",
      "электрик",
      "сантехник",
      "демонтаж",
      "смет",
      "архитект",
      "логист",
    ],
    goals: ["leads", "operations", "sales"],
    classes: ["site", "admin", "shop"],
    voices: ["bold", "formal"],
  },
  {
    id: "classic_business",
    name: "Классический деловой",
    why: "Строго и документально: надёжная антиква в заголовках, спокойный гротеск в тексте, глубокий сдержанный цвет и чёткая сетка.",
    avoid: "тёмно-синий с золотом, Фемида и рукопожатия на стоке",
    fontPairs: [
      { display: "PT Serif", text: "Source Sans 3" },
      { display: "PT Serif", text: "Golos Text" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic", "calm"],
    radius: ["crisp", "sharp"],
    controls: "match",
    density: ["regular", "compact"],
    grid: { columns: 12, maxWidth: 1200, measure: 66, layouts: ["symmetric", "asymmetric"] },
    motion: { profile: "calm", entrance: "fade", hover: "underline" },
    imagery: {
      style: "реальные офисы и документы, команда только по её фото, нейтральный дневной свет",
      treatment: "natural",
      ratio: "3:2",
      frame: "framed",
    },
    palette: {
      hues: [165, 245, 20],
      accentL: [0.36, 0.45],
      accentC: [0.06, 0.11],
      neutralHue: 250,
      neutralC: 0.006,
      bgL: { light: 0.985, dark: 0.16 },
      band: "neutral",
      accent2: "none",
      scheme: "light",
      accentUse: "signal",
      depth: "outline",
    },
    niches: [
      "юрист",
      "юридич",
      "адвокат",
      "нотари",
      "бухгалт",
      "финанс",
      "страхов",
      "аудит",
      "консалт",
      "банк",
      "недвижим",
      "оценк",
      "налог",
      "кадров",
      "b2b",
      "грузоперевоз",
      "логист",
      "клиник",
    ],
    goals: ["trust", "leads", "operations"],
    classes: ["site", "admin"],
    voices: ["formal"],
  },
  {
    id: "glossy_magazine",
    name: "Журнальный глянец",
    why: "Мода и красота через кадр: крупные фото во всю ширину, антиква с контрастом против строгого гротеска, асимметричные развороты как в журнале.",
    avoid: "розово-золотой, Playfair курсивом, стоковые модели",
    fontPairs: [
      {
        display: "Lora",
        text: "Commissioner",
        why: "мягкий контраст Lora в крупных заголовках поверх фото держит журнальную интонацию без штампа Playfair",
      },
      { display: "Alegreya", text: "Commissioner" },
    ],
    displayWeight: 400,
    upper: false,
    tracking: "tight",
    scales: ["dramatic", "classic"],
    radius: ["sharp", "crisp"],
    controls: "match",
    density: ["regular", "airy"],
    grid: { columns: 12, maxWidth: 1440, measure: 60, layouts: ["asymmetric", "split"] },
    motion: { profile: "lively", entrance: "clip", hover: "lift" },
    imagery: {
      style: "смелое кадрирование, крупные детали и работы мастеров, контрастный свет",
      treatment: "high-contrast",
      ratio: "4:5",
      frame: "full-bleed",
    },
    palette: {
      hues: [5, 22, 335],
      accentL: [0.5, 0.58],
      accentC: [0.14, 0.19],
      neutralHue: "brand",
      neutralC: 0.006,
      bgL: { light: 0.99, dark: 0.14 },
      band: "deep",
      accent2: "analogous",
      scheme: "light",
      accentUse: "signal",
      depth: "flat",
    },
    niches: [
      "салон",
      "красот",
      "маникюр",
      "ногт",
      "парикмах",
      "бров",
      "ресниц",
      "визаж",
      "стилист",
      "мода",
      "одежд",
      "косметик",
      "бьюти",
      "шоурум",
      "шоу-рум",
      "кондитер",
      "торт",
      "ювелир",
    ],
    goals: ["booking", "sales"],
    classes: ["booking", "shop", "site"],
    voices: ["refined", "bold"],
  },
  {
    id: "natural",
    name: "Природный",
    why: "Близко к земле: глубокие лесные и земляные цвета, гуманистичная пара из одного семейства, свободный ритм и живые материалы.",
    avoid: "бежевый крафт, листики-иконки и зелёный «эко» по умолчанию",
    fontPairs: [
      { display: "Alegreya", text: "Alegreya Sans" },
      { display: "Alegreya Sans", text: "Alegreya" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "normal",
    scales: ["classic", "calm"],
    radius: ["soft", "round"],
    controls: "match",
    density: ["airy", "regular"],
    grid: { columns: 12, maxWidth: 1280, measure: 64, layouts: ["split", "asymmetric"] },
    motion: { profile: "calm", entrance: "fade", hover: "lift" },
    imagery: {
      style: "пейзажи и растения, природный свет, материалы крупным планом, люди на природе без постановки",
      treatment: "warm-grade",
      ratio: "3:2",
      frame: "full-bleed",
    },
    palette: {
      hues: [145, 60, 205],
      accentL: [0.4, 0.5],
      accentC: [0.07, 0.12],
      neutralHue: "brand",
      neutralC: 0.008,
      bgL: { light: 0.98, dark: 0.16 },
      band: "tint",
      accent2: "analogous",
      scheme: "light",
      accentUse: "band",
      depth: "soft",
    },
    niches: [
      "эко-",
      "экологич",
      "фермер",
      "сад",
      "растен",
      "цвет",
      "флорист",
      "букет",
      "питомник",
      "турбаз",
      "глэмпинг",
      "туризм",
      "поход",
      "экскурс",
      "гостев",
      "загород",
      "пасек",
      "пчел",
      "пекарн",
      "хлеб",
      "керамик",
      "гончар",
      "натуральн",
      "развивающ",
      "монтессори",
    ],
    goals: ["booking", "sales", "leads"],
    classes: ["booking", "shop", "site"],
    voices: ["warm", "calm"],
  },
  {
    id: "night_contrast",
    name: "Ночной контрастный",
    why: "Вечер, сцена, техника: тёмная страница по умолчанию, светлый текст, один яркий сигнальный цвет и резкие переходы.",
    avoid: "неон и свечение, фиолетовые градиенты, циан на тёмном",
    fontPairs: [
      {
        display: "Unbounded",
        text: "Golos Text",
        why: "широкий гротеск держит короткие заголовки на тёмном фоне, где тонкие начертания разваливаются",
      },
      { display: "Sofia Sans Extra Condensed", text: "Onest" },
    ],
    displayWeight: 700,
    upper: false,
    tracking: "tight",
    scales: ["dramatic"],
    radius: ["crisp", "sharp"],
    controls: "match",
    density: ["regular", "compact"],
    grid: { columns: 12, maxWidth: 1360, measure: 62, layouts: ["asymmetric", "modular"] },
    motion: { profile: "lively", entrance: "rise", hover: "tint" },
    imagery: {
      style: "вечерние и ночные сцены, свет фар и прожекторов, техника и детали в темноте",
      treatment: "high-contrast",
      ratio: "16:9",
      frame: "full-bleed",
    },
    palette: {
      hues: [95, 45, 145],
      accentL: [0.78, 0.86],
      accentC: [0.14, 0.18],
      neutralHue: 255,
      neutralC: 0.01,
      bgL: { light: 0.975, dark: 0.15 },
      band: "neutral",
      accent2: "none",
      scheme: "dark",
      accentUse: "signal",
      depth: "flat",
    },
    niches: [
      "коктейл",
      "паб",
      "лаунж",
      "кальян",
      "караоке",
      "киберспорт",
      "компьютерн",
      "электрон",
      "тюнинг",
      "детейлинг",
      "тату",
      "кинотеатр",
      "ночн",
      "стрит",
      "автозвук",
      "одежд",
    ],
    goals: ["events", "booking", "sales"],
    classes: ["site", "booking", "shop"],
    voices: ["bold", "refined"],
  },
];

/** Archetype by id, or undefined. */
export function archetype(id: string | undefined | null): Archetype | undefined {
  return id ? ARCHETYPES.find((a) => a.id === id) : undefined;
}

export const isArchetypeId = (id: unknown): id is ArchetypeId =>
  typeof id === "string" && (ARCHETYPE_IDS as readonly string[]).includes(id);
