// Backend mode of the engine (V3-10, specs/agents/builder-v3.md §3 C5; product.yaml#decisions.D77_v3 (5)): modules are
// back-end recipes — the public front (site, client cabinet) is generated by v3 on the client's design system, staff
// cabinets stay from the library. Here: which screens are left to the v3 front, which public data actions its pages must
// provide (each served by a headless hook of @wizard/ui-kit/v3/headless, C4), and how goal scenarios find them.
import type { AppSpec, GoalScenario, PermissionOp } from "@wizard/appspec";
import { SERVICE_CONTRACT } from "../booking/compile.js";
import { type ScheduleSpec, scheduleOf } from "../booking/schedule.js";
import { CATALOG_NAMES } from "../catalog/compile.js";
import { SHOP_NAMES } from "../shop/compile.js";
import { checkoutConfig } from "../shop/pages.js";

/** What front the engine compiles: v2 — module pages as before; backend — no public pages (v3 generates them). */
export type FrontMode = "v2" | "backend";

/** Screen audiences of the public front (left to v3 in backend mode): the site and the client cabinet. */
export const PUBLIC_AUDIENCES: ReadonlySet<string> = new Set(["public", "visitor"]);

/**
 * Headless hooks of @wizard/ui-kit/v3/headless (C4) that serve the public data actions; useShop (V3-23) — the goods of
 * «Интернет-магазин» with the cart, the checkout and the order (useShopCatalog, useCart, useCheckout, useOrder).
 */
export type PublicHook = "useLeadForm" | "useBooking" | "useCatalog" | "useContent" | "useShop";

/** The checkout of «Интернет-магазин» (V3-23): what the v3 shop patterns pass to useCheckout and useOrder. */
export interface ShopFrontConfig {
  methods: { value: "pickup" | "cdek" | "courier"; label: string }[];
  online: boolean;
  courierPrice?: number;
  pointEntity: string;
  placeFn: string;
  cdekFn: string;
  payment?: { integration: string; binding: string };
  orderPath: string;
  /** Field of the stock of a product; null — the shop keeps no stock. */
  stockField: string | null;
  categoryEntity?: string;
}

/** A module screen the backend mode leaves to the v3 front. */
export interface PublicScreen {
  module: string;
  id: string;
  audience: "public" | "visitor";
  route: string;
  title: string;
  /** Concrete roles of the screen. */
  roles: string[];
}

/** Booking configuration of useBooking: the module's schedule and the names of the catalog contract. */
export interface BookingFrontConfig {
  schedule: ScheduleSpec;
  serviceEntity: string;
  /** Service field with the booking length in minutes, when the catalog has it. */
  durationField?: string;
  /** Resource the visitor picks (with_specialists). */
  specialistEntity?: string;
  /** Booking field «Согласен получать служебные сообщения», when the module has it. */
  consentMessagesField?: string;
}

/** A public data action the v3 pages must provide: the hook, its entity and the public functions it calls. */
export interface PublicAction {
  hook: PublicHook;
  module: string;
  entity: string;
  /** Roles of the public front that perform it (the public role, roles with self sign-up) and their ops. */
  roles: string[];
  ops: PermissionOp[];
  /** Public functions of the module the action calls (busySlots, packageCheck…). */
  functions?: string[];
  booking?: BookingFrontConfig;
  shop?: ShopFrontConfig;
}

/** A public function the pages of the front may call (POST /api/fn) with one of the front's roles. */
export interface PublicFunction {
  name: string;
  kind: "query" | "mutation" | "action";
  module: string;
  roles: string[];
}

/** The public front of a backend-mode system: module screens left to v3, the actions and functions its pages use. */
export interface PublicFront {
  screens: PublicScreen[];
  actions: PublicAction[];
  functions: PublicFunction[];
}

/** Modules whose plan-screen notes are about the v2 public pages (lead form and showcase on the landing). */
export const V2_FRONT_NOTES: ReadonlySet<string> = new Set(["leads", "catalog"]);

/** Where a goal scenario runs in backend mode: on public pages of the v3 front, or only in the staff cabinets. */
export type ScenarioSurface = "public" | "cabinet";

const PUBLIC_ACTORS: ReadonlySet<string> = new Set(["visitor", "client"]);

/** Roles of the public front: the public role and the roles with self sign-up (clients). */
const frontRoles = (spec: AppSpec) =>
  new Set(spec.roles.filter((r) => r.access === "public" || r.selfSignup).map((r) => r.name));

/** Public functions a role of the front may call, with their modules. */
export function publicFunctions(spec: AppSpec, functionOwner: ReadonlyMap<string, string>): PublicFunction[] {
  const front = frontRoles(spec);
  return (spec.functions ?? [])
    .filter((f) => f.public && (f.roles ?? []).some((r) => front.has(r)))
    .map((f) => ({
      name: f.name,
      kind: f.kind,
      module: functionOwner.get(f.name) ?? "",
      roles: (f.roles ?? []).filter((r) => front.has(r)),
    }));
}

/** The public data actions of a compiled spec: what the public role and the self sign-up roles may do, by module. */
export function publicActions(
  spec: AppSpec,
  entityOwner: ReadonlyMap<string, string>,
  functionOwner: ReadonlyMap<string, string>,
  params: Readonly<Record<string, Readonly<Record<string, unknown>>>>,
): PublicAction[] {
  const front = frontRoles(spec);
  const fns = publicFunctions(spec, functionOwner);
  const out: PublicAction[] = [];
  for (const e of spec.entities) {
    const grants = spec.permissions.filter((p) => p.entity === e.name && front.has(p.role));
    if (!grants.length) continue;
    const module = entityOwner.get(e.name) ?? "";
    const ops = [...new Set(grants.flatMap((p) => p.ops))] as PermissionOp[];
    const roles = grants.map((p) => p.role);
    const hook: PublicHook = ops.includes("create")
      ? module === "booking"
        ? "useBooking"
        : "useLeadForm"
      : module === "catalog" && e.name === CATALOG_NAMES.item
        ? "useCatalog"
        : module === "shop" && e.name === SHOP_NAMES.product
          ? "useShop"
          : "useContent";
    const functions = fns.filter((f) => f.module === module).map((f) => f.name);
    out.push({
      hook,
      module,
      entity: e.name,
      roles,
      ops,
      ...(functions.length ? { functions } : {}),
      ...(hook === "useBooking" ? { booking: bookingConfig(spec, params.booking ?? {}) } : {}),
      ...(hook === "useShop" ? { shop: shopConfig(spec, params.shop ?? {}) } : {}),
    });
  }
  return out;
}

function shopConfig(spec: AppSpec, params: Readonly<Record<string, unknown>>): ShopFrontConfig {
  const product = spec.entities.find((e) => e.name === SHOP_NAMES.product);
  return {
    ...checkoutConfig(params),
    stockField: product?.fields.some((f) => f.name === "stock") ? "stock" : null,
    ...(spec.entities.some((e) => e.name === SHOP_NAMES.category)
      ? { categoryEntity: SHOP_NAMES.category }
      : {}),
  };
}

function bookingConfig(spec: AppSpec, params: Readonly<Record<string, unknown>>): BookingFrontConfig {
  const fields = (entity: string) => spec.entities.find((e) => e.name === entity)?.fields ?? [];
  const has = (entity: string, field: string) => fields(entity).some((f) => f.name === field);
  return {
    schedule: scheduleOf(params, spec.app.timezone),
    serviceEntity: SERVICE_CONTRACT.entity,
    ...(has(SERVICE_CONTRACT.entity, SERVICE_CONTRACT.duration)
      ? { durationField: SERVICE_CONTRACT.duration }
      : {}),
    ...(params.with_specialists === true ? { specialistEntity: "specialist" } : {}),
    ...(has("booking", "consent_messages") ? { consentMessagesField: "consent_messages" } : {}),
  };
}

/**
 * Surface of a goal scenario: public when a visitor or a client acts (their pages come from the v3 front), else the
 * staff cabinets compiled here; the hooks of the public actions of its modules (the scenario's and withModules).
 */
export function scenarioFront(
  s: GoalScenario & { module: string },
  actions: readonly PublicAction[],
): { surface: ScenarioSurface; hooks?: PublicHook[] } {
  if (!s.steps.some((x) => PUBLIC_ACTORS.has(x.actor))) return { surface: "cabinet" };
  const modules = new Set([s.module, ...(s.withModules ?? [])]);
  const hooks = [...new Set(actions.filter((a) => modules.has(a.module)).map((a) => a.hook))];
  return { surface: "public", ...(hooks.length ? { hooks } : {}) };
}

const IMPORT_RE =
  /(?:import|export)\s[^"']*?from\s*["'](\.{1,2}\/[^"']+)["']|import\s*\(\s*["'](\.{1,2}\/[^"']+)["']/g;

function resolve(from: string, spec: string, files: ReadonlyMap<string, string>): string | undefined {
  const parts = from.split("/").slice(0, -1);
  for (const seg of spec.split("/")) {
    if (seg === "..") parts.pop();
    else if (seg !== ".") parts.push(seg);
  }
  const base = parts.join("/");
  return [base, `${base}.tsx`, `${base}.ts`, `${base}/index.tsx`, `${base}/index.ts`].find((p) =>
    files.has(p),
  );
}

/** ui/** files no page reaches through relative imports (helpers of the pages left to v3); functions/** stay. */
export function orphanUiFiles(files: ReadonlyMap<string, string>, pages: readonly string[]): string[] {
  const seen = new Set<string>();
  const queue = pages.filter((p) => files.has(p));
  while (queue.length) {
    const file = queue.pop() as string;
    if (seen.has(file)) continue;
    seen.add(file);
    for (const m of (files.get(file) ?? "").matchAll(IMPORT_RE)) {
      const target = resolve(file, m[1] ?? m[2] ?? "", files);
      if (target && !seen.has(target)) queue.push(target);
    }
  }
  return [...files.keys()].filter((f) => f.startsWith("ui/") && !seen.has(f));
}
