#!/usr/bin/env node
// Generates packages/gates/data/{abuse.json,brands.ru.json} and packages/appspec/src/pii-names.data.ts (the ПДн-name
// patterns and homoglyphs shared by G2-PII-02 and module extra fields, B2-46) from specs/security/abuse.yaml#patterns
// (abuse.yaml#patterns.location). Prose entries are parsed by fixed anchors: a changed wording fails loudly.
// brands.ru.json — own compilation from abuse.yaml#patterns.brands (CC0); domains are our own list.
// Run: node packages/gates/scripts/gen-g2-data.mjs   (test/g2-data.test.ts checks the output is fresh)
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseYamlFiles } from "../../../tools/specs/validate.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
export const DATA_DIR = resolve(HERE, "../data");
export const APPSPEC_PII_FILE = resolve(HERE, "../../appspec/src/pii-names.data.ts");
const ABUSE = resolve(HERE, "../../../specs/security/abuse.yaml");

function must(m, what) {
  if (!m) throw new Error(`gen-g2-data: abuse.yaml changed, cannot parse ${what}`);
  return m;
}

const list = (s) =>
  s
    .split(",")
    .map((x) => x.trim())
    .filter(Boolean);

// Translit for brand ids.
const TR = {
  а: "a",
  б: "b",
  в: "v",
  г: "g",
  д: "d",
  е: "e",
  ё: "e",
  ж: "zh",
  з: "z",
  и: "i",
  й: "y",
  к: "k",
  л: "l",
  м: "m",
  н: "n",
  о: "o",
  п: "p",
  р: "r",
  с: "s",
  т: "t",
  у: "u",
  ф: "f",
  х: "h",
  ц: "c",
  ч: "ch",
  ш: "sh",
  щ: "sch",
  ъ: "",
  ы: "y",
  ь: "",
  э: "e",
  ю: "yu",
  я: "ya",
};
const slug = (s) =>
  [...s.toLowerCase()]
    .map((c) => TR[c] ?? c)
    .join("")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");

/** Official domains (own list; used by AF-05/scoring as "brand domain" hints). */
const DOMAINS = {
  Сбербанк: ["sberbank.ru", "sber.ru"],
  Сбер: ["sber.ru"],
  ВТБ: ["vtb.ru"],
  "Т-Банк": ["tbank.ru"],
  Тинькофф: ["tinkoff.ru"],
  "Альфа-Банк": ["alfabank.ru"],
  Газпромбанк: ["gazprombank.ru"],
  ЮMoney: ["yoomoney.ru"],
  ЮKassa: ["yookassa.ru"],
  Госуслуги: ["gosuslugi.ru"],
  ФНС: ["nalog.gov.ru"],
  Налоговая: ["nalog.gov.ru"],
  Ozon: ["ozon.ru"],
  Озон: ["ozon.ru"],
  Wildberries: ["wildberries.ru", "wb.ru"],
  Авито: ["avito.ru"],
  "Почта России": ["pochta.ru"],
  СДЭК: ["cdek.ru"],
  МТС: ["mts.ru"],
  Билайн: ["beeline.ru"],
  МегаФон: ["megafon.ru"],
  Ростелеком: ["rt.ru"],
  ВКонтакте: ["vk.com"],
  VK: ["vk.com"],
  Telegram: ["telegram.org", "t.me"],
  "Мос.ру": ["mos.ru"],
};

export function buildData() {
  const y = parseYamlFiles([ABUSE])[ABUSE];
  if (!y || y.error !== undefined) throw new Error(`YAML ${ABUSE}: ${y?.error}`);
  const p = y.ok.patterns;
  const s = y.ok.scoring;

  const pairs = must(/\(([^)]*\/[^)]*)\)/.exec(p.normalize), "normalize pairs")[1]
    .split(",")
    .map((x) => x.trim().split("/"));
  const formsCtx = must(/данных карты: (.+?); имена/.exec(p.brands.match.forms), "brands.match.forms")[1];
  const formsWindow = Number(must(/в окне (\d+) символов/.exec(p.brands.match.forms), "forms window")[1]);
  const amb = must(
    /Имена-слова (.+?) — .*?со словом (\S+) в окне (\d+) символов/.exec(p.brands.match.ambiguous),
    "brands.match.ambiguous",
  );
  const allow = {};
  for (const part of p.brands.connector_allowlist.split(":").slice(1).join(":").split(";")) {
    const m = must(/(.+?)→(.+)/.exec(part), "connector_allowlist");
    const names = list(m[2]);
    for (const key of m[1].matchAll(/integrations\[(\w+)\]|loginMethods (\w+)/g)) {
      const k = key[1] ? `integration:${key[1]}` : `login:${key[2]}`;
      allow[k] = names;
    }
  }
  const fileDocs = must(/ИЛИ с (.+?) — тот же блок/.exec(p.gov_ids.file_fields), "gov_ids.file_fields")[1];
  const ent = p.secrets.entropy;
  const entropy = {
    minLength: Number(must(/≥ (\d+) символов/.exec(ent), "entropy length")[1]),
    minBits: Number(must(/≥ ([\d.]+) бит/.exec(ent), "entropy bits")[1]),
    window: Number(must(/в окне (\d+) символов/.exec(ent), "entropy window")[1]),
    context: must(/от (\S+)$/.exec(ent), "entropy context")[1],
  };
  const p2p = p.p2p_payment.text;
  const p2pWords = must(/«([^»]+)»/.exec(p2p), "p2p words")[1];
  const p2pWindow = Number(must(/в окне (\d+) символов/.exec(p2p), "p2p window")[1]);
  const cryptoCode = p.crypto_codes.code;
  const cryptoCalls = [...cryptoCode.matchAll(/(\w+)\(/g)].map((m) => m[1]);
  const cryptoTokens = list(cryptoCode.split(";")[0]).filter((t) => !t.endsWith("("));
  const cryptoStrings = must(/строки (.+)$/.exec(cryptoCode), "crypto strings")[1].split("|");

  const abuse = {
    $source: "specs/security/abuse.yaml#patterns (generated by scripts/gen-g2-data.mjs)",
    homoglyphs: pairs,
    card: { names: p.card_collection.names, autocomplete: p.card_collection.autocomplete },
    credentials: { names: p.credentials.names },
    govIds: { names: p.gov_ids.names, fileDocs },
    brands: {
      shortLength: 5,
      formsContext: formsCtx,
      formsWindow,
      ambiguous: list(amb[1]),
      ambiguousContext: amb[2],
      ambiguousWindow: Number(amb[3]),
      connectorAllowlist: allow,
    },
    p2p: { words: p2pWords, window: p2pWindow },
    crypto: { names: p.crypto_codes.names, tokens: cryptoTokens, calls: cryptoCalls, strings: cryptoStrings },
    secrets: {
      regex: p.secrets.regex.map((r) => r.replace(/ \([^)]*\)$/, "")),
      entropy,
    },
    piiNames: {
      strong: p.pii_field_names.strong,
      weak: p.pii_field_names.weak,
      weakExceptions: p.pii_field_names.weak_exceptions,
    },
    special: { names: p.special_categories.names },
    scoring: { signals: s.signals, urgentWords: s.urgent_words, threshold: s.threshold },
    messages: y.ok.messages_ru,
  };

  const brands = [];
  const ambiguous = new Set(abuse.brands.ambiguous.map((n) => n.toLowerCase()));
  for (const category of ["banks", "government", "marketplaces", "delivery", "telecom_social", "platform"]) {
    for (const name of p.brands[category] ?? []) {
      if (/^<.*>$/.test(name)) continue; // placeholder (final platform name, E-NAME)
      const b = { id: slug(name), names: [name], domains: DOMAINS[name] ?? [], category };
      if (ambiguous.has(name.toLowerCase())) b.ambiguous = true;
      brands.push(b);
    }
  }
  return { abuse, brands };
}

/** packages/appspec/src/pii-names.data.ts: abuse.yaml#patterns.pii_field_names and #normalize, biome-formatted. */
export function piiNamesSource(abuse) {
  const q = (v) => JSON.stringify(v);
  return [
    "// Generated by packages/gates/scripts/gen-g2-data.mjs from specs/security/abuse.yaml#patterns — do not edit.",
    "export const PII_NAMES_DATA = {",
    "  homoglyphs: [",
    ...abuse.homoglyphs.map(([c, l]) => `    [${q(c)}, ${q(l)}],`),
    "  ],",
    `  strong: ${q(abuse.piiNames.strong)},`,
    `  weak: ${q(abuse.piiNames.weak)},`,
    "  weakExceptions:",
    `    ${q(abuse.piiNames.weakExceptions)},`,
    "};",
    "",
  ].join("\n");
}

export function writeData(dir = DATA_DIR) {
  const { abuse, brands } = buildData();
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "abuse.json"), `${JSON.stringify(abuse, null, 2)}\n`);
  writeFileSync(join(dir, "brands.ru.json"), `${JSON.stringify(brands, null, 2)}\n`);
  if (dir === DATA_DIR) writeFileSync(APPSPEC_PII_FILE, piiNamesSource(abuse));
  return { abuse, brands };
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { brands } = writeData();
  console.log(`g2 data: ${brands.length} brands → ${DATA_DIR}`);
}
