// V3-23: the СДЭК client the module «Интернет-магазин» ships (packages/modules/src/shop/cdek-client.ts) is exactly the
// V3-20 client of the СДЭК passport in mock mode — the passport's mock answers (its examples), the same names and call
// signature as the live client the integration layer puts in its place once the shop's key passes its check. The
// requests the shop's delivery makes are the passport's operations. Regenerate after a passport or codegen change:
// WIZARD_UPDATE_SHOP_CDEK=1 npx vitest run packages/agents/test/integrations/shop-cdek.test.ts
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { CDEK_CLIENT_FILES, CDEK_CLIENT_REF } from "@wizard/modules";
import { describe, expect, test } from "vitest";
import {
  buildRequest,
  cdek,
  contractHash,
  contractRef,
  integrationCode,
  mockTransport,
  passportContract,
} from "../../src/integrations/index.js";

const root = join(fileURLToPath(new URL(".", import.meta.url)), "../../../..");
const target = join(root, "packages/modules/src/shop/cdek-client.ts");
const contract = passportContract(cdek);
const ref = contractRef(contract.id, 1, contractHash(contract));
const code = integrationCode(contract, "mock", ref);
/** The client the module ships: types, the passport's mock answers and the mock client (no actions of its own). */
const wanted = Object.fromEntries(
  ["types", "mock", "client"].map((f) => {
    const p = `functions/integrations/cdek/${f}.ts`;
    return [p, code.files[p] as string];
  }),
);

if (process.env.WIZARD_UPDATE_SHOP_CDEK === "1") {
  writeFileSync(
    target,
    [
      "// GENERATED by packages/agents/test/integrations/shop-cdek.test.ts (WIZARD_UPDATE_SHOP_CDEK=1) — do not edit.",
      "// The СДЭК client of the passport (V3-22) in mock mode as the V3-20 codegen writes it: the module «Интернет-магазин»",
      "// ships it, the integration layer replaces it with the live client after the key check (same names and calls).",
      "",
      `/** contract://… of the passport contract the files were generated from. */`,
      `export const CDEK_CLIENT_REF = ${JSON.stringify(ref)};`,
      "",
      "/** System files by path: functions/integrations/cdek/{types,mock,client}.ts. */",
      `export const CDEK_CLIENT_FILES: Readonly<Record<string, string>> = ${JSON.stringify(wanted, null, 2)};`,
      "",
    ].join("\n"),
  );
  const biome = spawnSync(join(root, "node_modules/.bin/biome"), ["format", "--write", target], {
    encoding: "utf8",
  });
  if (biome.status !== 0) throw new Error(`biome format: ${biome.stderr}`);
}

describe("the shop's СДЭК client", () => {
  test("is the V3-20 mock client of the СДЭК passport (regenerate with WIZARD_UPDATE_SHOP_CDEK=1)", () => {
    expect(CDEK_CLIENT_REF).toBe(ref);
    expect(CDEK_CLIENT_FILES).toEqual(wanted);
  });

  test("mock and live clients share names and the (ctx, input) signature the shop calls", () => {
    const live = integrationCode(contract, "live", ref).files[
      "functions/integrations/cdek/client.ts"
    ] as string;
    const mock = wanted["functions/integrations/cdek/client.ts"] as string;
    for (const op of ["listCities", "listDeliveryPoints", "calculateTariff"]) {
      expect(mock).toMatch(new RegExp(`export async function ${op}\\(_ctx: ActionCtx, _input: `));
      expect(live).toMatch(new RegExp(`export async function ${op}\\(ctx: ActionCtx, input: `));
    }
    expect(mock).toContain('export const MODE = "mock" as const;');
    expect(mock).not.toMatch(/http\.fetch|secret:\/\//);
  });

  test("the shop's requests are operations of the passport: the mock answers them", async () => {
    const send = mockTransport(contract);
    const call = async (op: string, input: Record<string, unknown>) => {
      const res = await send(buildRequest(contract, op, input));
      expect(res.status, `${op}: ${res.text}`).toBeLessThan(300);
      return JSON.parse(res.text) as unknown;
    };
    const cities = (await call("listCities", { countryCodes: "RU", city: "Москва", size: 1 })) as {
      code: number;
    }[];
    expect(cities[0]?.code).toBe(44);
    const points = (await call("listDeliveryPoints", {
      cityCode: 44,
      type: "PVZ",
      countryCode: "RU",
      size: 50,
    })) as { code: string }[];
    expect(points.map((p) => p.code)).toEqual(["MSK123"]);
    const tariff = (await call("calculateTariff", {
      body: {
        type: 1,
        tariff_code: 136,
        from_location: { code: 44 },
        to_location: { code: 44 },
        packages: [{ weight: 1500 }],
      },
    })) as { total_sum: number };
    expect(tariff.total_sum).toBe(390);
  });
});
