// Runtime functions of «Учёт выдачи и ресурсов» (sources generated from the parameters, sdk.md):
// - issueResource (workflow resource_issued): a new issue gets the issue time, the due time by default_days and the
//   client's contacts (with «Клиенты с историей»); an issue already past its due time is overdue at once; the item
//   becomes «Выдан» (or its count in stock drops);
// - returnResource (workflow resource_returned): the return time, the open slot released, the item back in stock.
import type { GenContext } from "../types.js";

export const ISSUE_RESOURCE_FILE = "functions/resources/issueResource.ts";
export const RETURN_RESOURCE_FILE = "functions/resources/returnResource.ts";

/** Recount of an item by its open issues (shared text of both functions). */
function syncSource(ctx: GenContext): string {
  const q = ctx.params.with_quantity === true;
  return `type Row = Record<string, unknown>;
const text = (v: unknown): string | null => (typeof v === "string" && v.trim() !== "" ? v.trim() : null);

/** The item's state by its issues that are not returned yet${q ? " (pieces in stock = all − on hand)" : ""}. */
async function syncItem(db: MutationCtx["db"], id: unknown): Promise<void> {
  const item = (await db.resource.get(id as never)) as unknown as Row | null;
  if (!item) return;
  const issues = (await db.resource_issue.list({ where: { resource: id as never }, limit: 1000 })) as unknown as Row[];
  const open = issues.filter((r) => r.status !== "returned");${
    q
      ? `
  const out = open.reduce((n, r) => n + (typeof r.quantity === "number" ? r.quantity : 1), 0);
  const total = typeof item.quantity === "number" ? item.quantity : 0;
  const inStock = Math.max(0, total - out);
  const status = item.status === "unavailable" ? "unavailable" : inStock > 0 ? "available" : "issued";
  if (item.in_stock !== inStock || item.status !== status)
    await db.resource.patch(id as never, { in_stock: inStock, status } as never);`
      : `
  const status = open.length > 0 ? "issued" : item.status === "unavailable" ? "unavailable" : "available";
  if (item.status !== status) await db.resource.patch(id as never, { status } as never);`
  }
}
`;
}

export function issueResourceSource(ctx: GenContext): string {
  const days = typeof ctx.params.default_days === "number" ? ctx.params.default_days : 7;
  const clients = ctx.present.has("client_card");
  return `// Generated by the module «Учёт выдачи и ресурсов» (B2-18): an issue gets its times, contacts and the item's state.
import { type MutationCtx, mutation, v } from "@wizard/sdk";

const DEFAULT_DAYS = ${days};
${syncSource(ctx)}
export default mutation({
  args: { id: v.id("resource_issue") },
  handler: async (ctx, args) => {
    const issue = (await ctx.db.resource_issue.get(args.id)) as unknown as Row | null;
    if (!issue) return { ok: false };
    const now = ctx.now.getTime();
    const patch: Row = {};
    const issued = Date.parse(String(issue.issued_at ?? ""));
    const from = Number.isNaN(issued) ? now : issued;
    if (Number.isNaN(issued)) patch.issued_at = new Date(from).toISOString();
    let due = Date.parse(String(issue.due_at ?? ""));
    if (Number.isNaN(due)) {
      due = from + DEFAULT_DAYS * 86_400_000;
      patch.due_at = new Date(due).toISOString();
    }
    if (issue.status === "issued" && due <= now) {
      patch.status = "overdue";
      patch.was_overdue = true;
    }${
      clients
        ? `
    if (issue.client && !text(issue.email) && !text(issue.phone)) {
      const client = (await ctx.db.client.get(issue.client as never)) as unknown as Row | null;
      if (text(client?.email)) patch.email = text(client?.email)?.toLowerCase();
      if (text(client?.phone)) patch.phone = text(client?.phone);
    }`
        : ""
    }
    if (Object.keys(patch).length) await ctx.db.resource_issue.patch(args.id, patch as never);
    await syncItem(ctx.db, issue.resource);
    return { ok: true };
  },
});
`;
}

export function returnResourceSource(ctx: GenContext): string {
  const q = ctx.params.with_quantity === true;
  return `// Generated by the module «Учёт выдачи и ресурсов» (B2-18): a return closes the issue and puts the item back.
import { type MutationCtx, mutation, v } from "@wizard/sdk";

${syncSource(ctx)}
export default mutation({
  args: { id: v.id("resource_issue") },
  handler: async (ctx, args) => {
    const issue = (await ctx.db.resource_issue.get(args.id)) as unknown as Row | null;
    if (!issue || issue.status !== "returned") return { ok: false };
    const patch: Row = {};
    if (!issue.returned_at) patch.returned_at = ctx.now.toISOString();${q ? "" : "\n    if (issue.open !== null) patch.open = null;"}
    if (Object.keys(patch).length) await ctx.db.resource_issue.patch(args.id, patch as never);
    await syncItem(ctx.db, issue.resource);
    return { ok: true };
  },
});
`;
}
