// The page «Загрузка списка» of «Учёт выдачи и ресурсов» (screen generator, parameter bulk_import): the owner pastes
// rows copied from a spreadsheet (Excel, Google Таблицы: cells by tabs, or a CSV line by «;» or «,»), sees what will be
// added and adds the items through the data API — no file upload and no server function.
import type { Field } from "@wizard/appspec";
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";
import { RESOURCE_NAMES } from "./compile.js";

/** Field types a pasted cell can fill. */
const CELL_TYPES = new Set<Field["type"]>([
  "string",
  "text",
  "int",
  "decimal",
  "money",
  "bool",
  "date",
  "enum",
  "email",
  "phone",
  "url",
]);
/** Rows per import: the data API allows 300 requests a minute per session. */
export const IMPORT_MAX_ROWS = 200;

/** Columns of the pasted table in order: the name, the plan's extra fields, the inventory number, the count. */
export function importColumns(
  ctx: Pick<ScreenContext, "spec" | "params">,
): { name: string; label: string; type: string; options?: { value: string; label: string }[] }[] {
  const e = ctx.spec.entities.find((x) => x.name === RESOURCE_NAMES.item);
  const extra = ((ctx.params.extra_fields as { name: string }[] | undefined) ?? []).map((f) => f.name);
  const names = [
    "name",
    ...extra,
    "inventory_no",
    ...(ctx.params.with_quantity === true ? ["quantity"] : []),
  ];
  return names.flatMap((n) => {
    const f = e?.fields.find((x) => x.name === n);
    if (!f || !CELL_TYPES.has(f.type)) return [];
    return [
      {
        name: f.name,
        label: f.label,
        type: f.type,
        ...(f.enum ? { options: f.enum.map((o) => ({ ...o })) } : {}),
      },
    ];
  });
}

export function importPage(ctx: ScreenContext): string {
  const cols = importColumns(ctx);
  const label = String(ctx.params.resource_label ?? "Инвентарь");
  const text = {
    title: `Загрузка списка: ${label}`,
    intro: `Скопируйте строки из таблицы (Excel, Google Таблицы) и вставьте сюда. Каждая строка — одна позиция, колонки по порядку: ${cols.map((c) => c.label).join(", ")}. Строку с заголовками можно оставить — она пропустится. За раз — до ${IMPORT_MAX_ROWS} строк.`,
    paste: "Строки из таблицы",
    preview: "Будет добавлено",
    add: "Добавить",
    adding: "Добавляем…",
    done: "Добавлено",
    failed: "Не добавлено",
    empty: "Вставьте строки — здесь появится, что будет добавлено",
    tooMany: `Больше ${IMPORT_MAX_ROWS} строк — разбейте список на части`,
  };
  return `// Generated by the module «Учёт выдачи и ресурсов» (B2-18): items pasted from a spreadsheet, added through the data API.
import { type Insert, useEntityMutation, useMemo, useState } from "@wizard/sdk";
import { Button, EmptyState } from "@wizard/ui-kit";

const TEXT = ${js(text)};
type Column = { name: string; label: string; type: string; options?: { value: string; label: string }[] };
const COLUMNS: Column[] = ${js(cols)};
const MAX_ROWS = ${IMPORT_MAX_ROWS};
const box = { width: "100%", minHeight: 160, boxSizing: "border-box", font: "inherit", padding: 8 } as const;
const scroll = { overflowX: "auto", maxWidth: "100%" } as const;

/** A cell → the field's value; undefined — leave the field empty. */
function cell(c: Column, raw: string): unknown {
  const s = raw.trim();
  if (s === "") return undefined;
  switch (c.type) {
    case "int":
    case "decimal":
    case "money": {
      const n = Number(s.replace(/\\s/g, "").replace(",", "."));
      if (!Number.isFinite(n)) return undefined;
      return c.type === "int" ? Math.round(n) : n;
    }
    case "bool":
      return /^(да|yes|true|1|\\+)$/i.test(s);
    case "date": {
      const ru = /^(\\d{1,2})\\.(\\d{1,2})\\.(\\d{4})$/.exec(s);
      if (ru) return \`\${ru[3]}-\${ru[2]?.padStart(2, "0")}-\${ru[1]?.padStart(2, "0")}\`;
      return /^\\d{4}-\\d{2}-\\d{2}$/.test(s) ? s : undefined;
    }
    case "enum":
      return c.options?.find((o) => o.label.toLowerCase() === s.toLowerCase() || o.value === s)?.value;
    default:
      return s;
  }
}

/** Pasted text → rows of values (a header row equal to the column names is skipped). */
function parse(text: string): Record<string, unknown>[] {
  const lines = text.split(/\\r?\\n/).filter((l) => l.trim() !== "");
  const sep = lines.some((l) => l.includes("\\t")) ? "\\t" : lines.some((l) => l.includes(";")) ? ";" : ",";
  const rows: Record<string, unknown>[] = [];
  for (const [i, line] of lines.entries()) {
    const cells = line.split(sep);
    if (i === 0 && (cells[0] ?? "").trim().toLowerCase() === (COLUMNS[0]?.label ?? "").toLowerCase()) continue;
    const row: Record<string, unknown> = {};
    COLUMNS.forEach((c, k) => {
      const v = cell(c, cells[k] ?? "");
      if (v !== undefined) row[c.name] = v;
    });
    if (typeof row.name === "string" && row.name !== "") rows.push(row);
  }
  return rows;
}

const show = (v: unknown) => (v === undefined || v === null ? "" : typeof v === "boolean" ? (v ? "да" : "нет") : String(v));

export default function ResourcesImport() {
  const mutations = useEntityMutation("resource");
  const [text, setText] = useState("");
  const [busy, setBusy] = useState(false);
  const [result, setResult] = useState<{ added: number; failed: number } | null>(null);
  const rows = useMemo(() => parse(text), [text]);

  const add = async () => {
    setBusy(true);
    let added = 0;
    let failed = 0;
    for (const row of rows) {
      try {
        await mutations.create(row as unknown as Insert<"resource">);
        added += 1;
      } catch {
        failed += 1;
      }
    }
    setBusy(false);
    setResult({ added, failed });
    if (failed === 0) setText("");
  };

  return (
    <main data-testid="resources-import">
      <h1>{TEXT.title}</h1>
      <p>{TEXT.intro}</p>
      <label htmlFor="resources-import-text">{TEXT.paste}</label>
      <textarea id="resources-import-text" style={box} value={text} onChange={(e) => { setText(e.target.value); setResult(null); }} />
      {result ? (
        <p role="status">{TEXT.done}: {result.added}{result.failed ? \` · \${TEXT.failed}: \${result.failed}\` : ""}</p>
      ) : null}
      {rows.length === 0 ? (
        <EmptyState text={TEXT.empty} />
      ) : rows.length > MAX_ROWS ? (
        <p role="alert">{TEXT.tooMany}</p>
      ) : (
        <section aria-label={TEXT.preview}>
          <h2>{TEXT.preview}: {rows.length}</h2>
          <div style={scroll}>
            <table>
              <thead>
                <tr>{COLUMNS.map((c) => <th key={c.name}>{c.label}</th>)}</tr>
              </thead>
              <tbody>
                {rows.slice(0, 20).map((r, i) => (
                  <tr key={i}>{COLUMNS.map((c) => <td key={c.name}>{show(r[c.name])}</td>)}</tr>
                ))}
              </tbody>
            </table>
          </div>
          <Button variant="primary" loading={busy} onClick={() => void add()}>
            {busy ? TEXT.adding : \`\${TEXT.add}: \${rows.length}\`}
          </Button>
        </section>
      )}
    </main>
  );
}
`;
}
