// themeForNiche (themes.yaml#selection): the agent picks one of the ten presets from the niche of the brief.
// Keyword stems over the lower-cased Russian text; the preset with most matches wins (ties — the order of PICK_ORDER);
// no match → strict (safe for any business).
import type { ThemePresetId } from "./presets.js";

const STEMS: Record<ThemePresetId, readonly string[]> = {
  warm: [
    "салон",
    "красот",
    "маникюр",
    "педикюр",
    "ногт",
    "парикмах",
    "брови",
    "ресниц",
    "косметолог",
    "цвет",
    "флорист",
    "букет",
    "подар",
    "ателье",
    "швейн",
    "рукодел",
    "хендмейд",
    "гостев",
    "гостиниц",
    "отель",
    "хостел",
    "груминг",
    "зоосалон",
  ],
  bright: [
    "фитнес",
    "спорт",
    "трениров",
    "танц",
    "хореограф",
    "детск",
    "детей",
    "дети",
    "кружок",
    "кружк",
    "лагер",
    "квест",
    "развлеч",
    "игр",
    "батут",
    "молодеж",
    "молодёж",
  ],
  calm: [
    "психолог",
    "психотерап",
    "коуч",
    "йог",
    "медитац",
    "архитект",
    "интерьер",
    "галере",
    "нутрициолог",
    "ретрит",
    "арт-",
  ],
  strict: [
    "юрист",
    "юридич",
    "адвокат",
    "нотари",
    "бухгалт",
    "финанс",
    "страхов",
    "консалт",
    "аудит",
    "b2b",
    "производств",
    "завод",
    "логист",
    "склад",
    "грузоперевоз",
    "недвижим",
    "crm",
    "заявк",
    "учет",
    "учёт",
  ],
  boutique: [
    "свадеб",
    "торжеств",
    "фотограф",
    "видеограф",
    "ювелир",
    "украшен",
    "стилист",
    "визаж",
    "бутик",
    "дизайнер одежд",
    "премиум",
    "парфюм",
  ],
  bistro: [
    "кафе",
    "ресторан",
    "бистро",
    "кофейн",
    "кофе",
    "пекарн",
    "кондитер",
    "торт",
    "выпечк",
    "еды",
    "кулинар",
    "фермер",
    "пиццер",
  ],
  workshop: [
    "барбер",
    "ремонт",
    "отделк",
    "строит",
    "автосервис",
    "шиномонтаж",
    "автомойк",
    "мастерск",
    "мебел",
    "сантехник",
    "электрик",
    "единоборств",
    "бокс",
  ],
  academy: [
    "репетитор",
    "курс",
    "онлайн-школ",
    "школ",
    "обучени",
    "язык",
    "английск",
    "экзамен",
    "егэ",
    "огэ",
    "развивающ",
    "преподава",
  ],
  poster: [
    "мероприят",
    "событи",
    "фестивал",
    "концерт",
    "форум",
    "конференц",
    "театр",
    "площадк",
    "музей",
    "выставк",
    "афиш",
    "вечеринк",
    "квиз",
  ],
  care: [
    "клиник",
    "стоматолог",
    "врач",
    "медицин",
    "медцентр",
    "остеопат",
    "ветеринар",
    "ветклиник",
    "массаж",
    "реабилит",
    "анализ",
    "лаборатор",
    "аптек",
    "оптик",
  ],
};

/** Tie order: the narrower looks first, strict last (it is also the fallback). */
const PICK_ORDER: readonly ThemePresetId[] = [
  "care",
  "bistro",
  "boutique",
  "workshop",
  "poster",
  "academy",
  "warm",
  "bright",
  "calm",
  "strict",
];

/** Preset id for a niche description («студия маникюра», «юридическая консультация»); strict when nothing matches. */
export function themeForNiche(niche: string): ThemePresetId {
  const text = niche.toLowerCase();
  let best: ThemePresetId = "strict";
  let score = 0;
  for (const id of PICK_ORDER) {
    const s = STEMS[id].filter((stem) => text.includes(stem)).length;
    if (s > score) {
      best = id;
      score = s;
    }
  }
  return best;
}
