// Theme presets added by themes v2 (B2-36, specs/ui/themes.yaml#presets): six looks for niches the first four served
// with a compromise. Font pairs — docs/research/design-agent-catalog.md#A6; neutrals keep ink and muted ≥ 4.5:1 on
// every background (themes test).
import type { ThemePreset } from "./presets.js";

export const V2_PRESETS: readonly ThemePreset[] = [
  {
    id: "boutique",
    name: "Изысканная",
    description:
      "Высококонтрастная антиква, строгие прямые углы, много воздуха и тонкие линии. Дорого и спокойно.",
    niches: [
      "свадьбы и организаторы торжеств",
      "фотографы и видеографы",
      "ювелиры и украшения",
      "стилисты и визажисты",
      "бутики и дизайнеры одежды",
      "салоны премиум-класса",
    ],
    defaults: {
      accent: "#6B2440",
      font: "Commissioner",
      headingFont: "Cormorant Garamond",
      radius: 0,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#F6F5F3",
        surface: "#FFFFFF",
        surfaceAlt: "#EFECE8",
        ink: "#1A1819",
        muted: "#5E5859",
        line: "#E2DDD8",
      },
      dark: {
        bg: "#131112",
        surface: "#1C191A",
        surfaceAlt: "#231F20",
        ink: "#F1ECEB",
        muted: "#B2A8A9",
        line: "#352F30",
      },
    },
    depth: "flat",
    heading: { weight: 700, tracking: "0", size: "large" },
    space: "airy",
    photoStyle: "студийный рассеянный свет, крупные планы деталей, спокойный однотонный фон",
    graphic: "arcs",
    draft: true,
  },
  {
    id: "bistro",
    name: "Аппетитная",
    description:
      "Тёплая книжная антиква в заголовках, сочный цвет, мягкие карточки. Хочется зайти и попробовать.",
    niches: [
      "кафе и рестораны",
      "пекарни и кондитерские",
      "кофейни",
      "доставка еды",
      "фермерские продукты",
      "кулинарные студии",
    ],
    defaults: {
      accent: "#B3361D",
      font: "Source Sans 3",
      headingFont: "Piazzolla",
      radius: 12,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#FBFAF7",
        surface: "#FFFFFF",
        surfaceAlt: "#F3EFE8",
        ink: "#1C1714",
        muted: "#5D5550",
        line: "#E8E2DA",
      },
      dark: {
        bg: "#151210",
        surface: "#1E1A17",
        surfaceAlt: "#26211D",
        ink: "#F4EEE8",
        muted: "#B9AEA5",
        line: "#39322C",
      },
    },
    depth: "soft",
    heading: { weight: 700, tracking: "-0.01em" },
    space: "regular",
    photoStyle: "блюда и выпечка крупным планом, дневной свет из окна, живые столы и руки",
    graphic: "dots",
    draft: true,
  },
  {
    id: "workshop",
    name: "Мастерская",
    description: "Узкие плотные заголовки капсом, чёткие линии, почти прямые углы. Крепко и по делу.",
    niches: [
      "барбершопы",
      "ремонт и отделка",
      "автосервис и шиномонтаж",
      "строительство",
      "мастерские и производство на заказ",
      "единоборства",
    ],
    defaults: {
      accent: "#B53C0B",
      font: "Sofia Sans",
      headingFont: "Sofia Sans Extra Condensed",
      radius: 4,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#F3F3F1",
        surface: "#FFFFFF",
        surfaceAlt: "#E9E9E6",
        ink: "#16181B",
        muted: "#4F545B",
        line: "#D8D9D5",
      },
      dark: {
        bg: "#121416",
        surface: "#1A1D20",
        surfaceAlt: "#202427",
        ink: "#F0F0EC",
        muted: "#A9ADB4",
        line: "#2E3338",
      },
    },
    depth: "flat",
    heading: { weight: 700, tracking: "0.01em", size: "large", upper: true },
    space: "regular",
    photoStyle: "рабочий процесс и инструменты, фактуры металла и дерева, контрастный боковой свет",
    graphic: "stripes",
    draft: true,
  },
  {
    id: "academy",
    name: "Дружелюбная",
    description: "Тёплый гуманистичный шрифт, спокойный зелёный, крупные скругления. Понятно и без давления.",
    niches: [
      "репетиторы",
      "языковые школы и курсы",
      "онлайн-обучение",
      "развивающие центры",
      "подготовка к экзаменам",
      "клубы по интересам",
    ],
    defaults: {
      accent: "#1F5C46",
      font: "Alegreya",
      headingFont: "Alegreya Sans",
      radius: 12,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#F6F7F4",
        surface: "#FFFFFF",
        surfaceAlt: "#EBF0EA",
        ink: "#13201A",
        muted: "#4C5A52",
        line: "#DCE3DC",
      },
      dark: {
        bg: "#0F1513",
        surface: "#17201C",
        surfaceAlt: "#1D2823",
        ink: "#E8F0EB",
        muted: "#A3B3AA",
        line: "#2A3731",
      },
    },
    depth: "soft",
    heading: { weight: 700, tracking: "0" },
    space: "regular",
    photoStyle: "занятия и общение, светлые классы, открытые лица без постановки",
    graphic: "wash",
    draft: true,
  },
  {
    id: "poster",
    name: "Афиша",
    description: "Высокие плакатные заголовки капсом, книжный текст, резкие углы. Как афиша события.",
    niches: [
      "мероприятия и конференции",
      "концерты и фестивали",
      "театры и площадки",
      "музеи и выставки",
      "медиа и клубы по подписке",
      "квизы и вечеринки",
    ],
    defaults: {
      accent: "#2234A8",
      font: "Literata",
      headingFont: "Alumni Sans",
      radius: 0,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#F2F1EC",
        surface: "#FFFFFF",
        surfaceAlt: "#E7E5DD",
        ink: "#111216",
        muted: "#55534C",
        line: "#D8D5CC",
      },
      dark: {
        bg: "#111216",
        surface: "#1A1C24",
        surfaceAlt: "#20232D",
        ink: "#F3F0E7",
        muted: "#ABA79C",
        line: "#2C2F3A",
      },
    },
    depth: "lifted",
    heading: { weight: 700, tracking: "0.01em", size: "large", upper: true },
    space: "regular",
    photoStyle: "сцена и публика, вечерний свет, контраст и движение",
    graphic: "stripes",
    draft: true,
  },
  {
    id: "care",
    name: "Заботливая",
    description: "Мягкий разборчивый шрифт, прохладные чистые тона, плавные формы. Спокойно и надёжно.",
    niches: [
      "частные клиники и медцентры",
      "стоматология",
      "ветеринарные клиники",
      "массаж и реабилитация",
      "лаборатории и анализы",
      "аптеки и оптики",
    ],
    defaults: {
      accent: "#1C5F5A",
      font: "Wix Madefor Text",
      headingFont: "Wix Madefor Display",
      radius: 16,
      density: "regular",
    },
    palette: {
      light: {
        bg: "#F1F6F5",
        surface: "#FFFFFF",
        surfaceAlt: "#E5EFED",
        ink: "#10201E",
        muted: "#475A57",
        line: "#D6E3E0",
      },
      dark: {
        bg: "#0D1514",
        surface: "#141E1D",
        surfaceAlt: "#1A2725",
        ink: "#E6F0EE",
        muted: "#9FB3AF",
        line: "#263533",
      },
    },
    depth: "soft",
    heading: { weight: 700, tracking: "-0.01em" },
    space: "airy",
    photoStyle: "светлые кабинеты, внимательный специалист, чистые нейтральные тона без медицинских штампов",
    graphic: "arcs",
    draft: true,
  },
];
