#!/usr/bin/env node
// Generates packages/modules/src/draft.ts from specs/modules/modules.yaml#catalog: the manifests of the beta v2
// catalog as the spec states them. Modules with code (src/<id>/) replace their draft in src/catalog.ts; the catalog
// test checks this file is up to date. Run after changing the catalog: node packages/modules/scripts/gen-draft.mjs
import { spawnSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseYamlFiles } from "../../../tools/specs/validate.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "../../..");
const spec = join(root, "specs/modules/modules.yaml");
const loaded = parseYamlFiles([spec])[spec];
if (!loaded?.ok) throw new Error(`modules.yaml: ${loaded?.error}`);
const out = join(here, "../src/draft.ts");
writeFileSync(
  out,
  [
    "// GENERATED by packages/modules/scripts/gen-draft.mjs from specs/modules/modules.yaml#catalog — do not edit.",
    "// Draft manifests of the beta v2 catalog; modules with code replace their entry in catalog.ts.",
    'import type { ModuleManifest } from "@wizard/appspec";',
    "",
    `export const DRAFT_MANIFESTS: ModuleManifest[] = ${JSON.stringify(loaded.ok.catalog, null, 2)};`,
    "",
  ].join("\n"),
);
const biome = spawnSync(join(root, "node_modules/.bin/biome"), ["format", "--write", out], {
  encoding: "utf8",
});
if (biome.status !== 0) throw new Error(`biome format: ${biome.stderr}`);
console.log(`draft.ts: ${loaded.ok.catalog.length} manifests`);
