// Runtime functions of «Абонементы и пакеты» (sources generated from the parameters, sdk.md). The fields a package has
// depend on what is sold (visits, a term or both), so the sources read records through plain objects:
// - packageSold (workflows package_sold, package_dates): a new package takes the term, the visits and the price of its
//   tariff and the client's contacts (a booking and the visitor cabinet find the package by them); the moment of the
//   end (`ends_at`) follows «Действует до»;
// - applyUsage (workflow package_usage_apply): a visit written off or given back by hand changes the remaining visits
//   once (the flag `applied` protects against a double count);
// - writeOffVisit / returnVisit (workflows of the booking link): a booking takes a visit off a valid package of the
//   same phone (and e-mail, when the package has one); a visitor's booking without one is cancelled at once; a
//   cancelled booking gives its visit back;
// - packageCheck (public mutation of the booking page): «is there a valid package for these contacts on this day» —
//   only yes or no, without names, terms or remaining visits;
// - unfreezePackage (workflow package_unfrozen): the days a package was frozen move its end date;
// - myMaterials (query of the page «Материалы»): the members' materials for a client with a valid package.
import type { GenContext } from "../types.js";
import { packageKind, writesOff } from "./compile.js";

export const PACKAGE_SOLD_FILE = "functions/packages/packageSold.ts";
export const APPLY_USAGE_FILE = "functions/packages/applyUsage.ts";
export const WRITE_OFF_FILE = "functions/packages/writeOffVisit.ts";
export const RETURN_VISIT_FILE = "functions/packages/returnVisit.ts";
export const PACKAGE_CHECK_FILE = "functions/packages/packageCheck.ts";
export const UNFREEZE_FILE = "functions/packages/unfreezePackage.ts";
export const MY_MATERIALS_FILE = "functions/packages/myMaterials.ts";

/** Days in Moscow time (the runtime's default zone): dates of packages are calendar days of the business. */
const DAYS = `const DAY = 86_400_000;
const MSK = 3 * 3_600_000;
/** The Moscow calendar day of an instant: 'YYYY-MM-DD'. */
const dayOf = (t: number): string => new Date(t + MSK).toISOString().slice(0, 10);
const addDays = (day: string, n: number): string =>
  new Date(Date.parse(\`\${day}T00:00:00Z\`) + n * DAY).toISOString().slice(0, 10);
type Row = Record<string, unknown>;
const text = (v: unknown): string | null => (typeof v === "string" && v.trim() !== "" ? v.trim() : null);
`;

/** The valid-package search shared by packageCheck and writeOffVisit (needs DAYS). */
function findSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  return `/**
 * A package valid on \`day\` for the contacts: status active, the same phone, the same e-mail when the package has one,
 * started by that day${k.period ? ", not ended before it" : ""}${k.visits ? ", with visits left" : ""}; the one that ends first.
 */
async function findPackage(db: MutationCtx["db"], phone: string | null, email: string | null, day: string): Promise<Row | null> {
  if (!phone) return null;
  const mail = email?.toLowerCase() ?? null;
  const rows = (await db.client_package.list({ where: { phone }, limit: 50 })) as unknown as Row[];
  const valid = rows.filter((r) => {
    if (r.status !== "active") return false;
    const own = text(r.email)?.toLowerCase() ?? null;
    if (own && own !== mail) return false;
    if (typeof r.starts_on === "string" && r.starts_on > day) return false;${
      k.period ? `\n    if (typeof r.expires_on === "string" && r.expires_on < day) return false;` : ""
    }${k.visits ? `\n    if (typeof r.visits_left === "number" && r.visits_left <= 0) return false;` : ""}
    return true;
  });
  valid.sort((a, b) => String(a.expires_on ?? "9999").localeCompare(String(b.expires_on ?? "9999")) || String(a.created_at).localeCompare(String(b.created_at)));
  return valid[0] ?? null;
}
`;
}

export function packageSoldSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  const validity = typeof ctx.params.validity_days === "number" ? ctx.params.validity_days : 30;
  return `// Generated by the module «Абонементы и пакеты» (B2-18): a sold package takes its tariff's term, visits and price.
import { mutation, v } from "@wizard/sdk";

${DAYS}
export default mutation({
  args: { id: v.id("client_package") },
  handler: async (ctx, args) => {
    const pkg = (await ctx.db.client_package.get(args.id)) as unknown as Row | null;
    if (!pkg) return { ok: false };
    const plan = (await ctx.db.package_plan.get(pkg.plan as never)) as unknown as Row | null;
    const client = (await ctx.db.client.get(pkg.client as never)) as unknown as Row | null;
    const patch: Row = {};
    const start = text(pkg.starts_on) ?? dayOf(ctx.now.getTime());
    if (!text(pkg.starts_on)) patch.starts_on = start;${
      k.period
        ? `
    if (!text(pkg.expires_on)) {
      const days = typeof plan?.days === "number" ? plan.days : ${validity};
      patch.expires_on = addDays(start, Math.max(1, days) - 1);
    }
    // The moment of the end: the end of the last day in Moscow time (the expiry and the reminder go by it).
    const end = text(patch.expires_on) ?? text(pkg.expires_on);
    if (end) {
      const endsAt = new Date(Date.parse(\`\${end}T00:00:00Z\`) + DAY - MSK).toISOString();
      if (pkg.ends_at !== endsAt) patch.ends_at = endsAt;
    }`
        : ""
    }${
      k.visits
        ? `
    const visits = typeof plan?.visits === "number" ? plan.visits : null;
    if (typeof pkg.visits_total !== "number" && visits !== null) patch.visits_total = visits;
    if (typeof pkg.visits_left !== "number" && visits !== null) patch.visits_left = visits;`
        : ""
    }
    if (typeof pkg.price !== "number" && typeof plan?.price === "number") patch.price = plan.price;
    if (!text(pkg.phone) && text(client?.phone)) patch.phone = text(client?.phone);
    if (!text(pkg.email) && text(client?.email)) patch.email = text(client?.email)?.toLowerCase();
    if (Object.keys(patch).length) await ctx.db.client_package.patch(args.id, patch as never);
    return { ok: true };
  },
});
`;
}

export function applyUsageSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  return `// Generated by the module «Абонементы и пакеты» (B2-18): a visit written off or given back by hand, counted once.
import { mutation, v } from "@wizard/sdk";

type Row = Record<string, unknown>;

export default mutation({
  args: { id: v.id("package_usage") },
  handler: async (ctx, args) => {
    const usage = (await ctx.db.package_usage.get(args.id)) as unknown as Row | null;
    if (!usage || usage.applied === true) return { ok: false };
    const patch: Row = { applied: true };
    if (!usage.used_at) patch.used_at = ctx.now.toISOString();
    await ctx.db.package_usage.patch(args.id, patch as never);${
      k.visits
        ? `
    const pkg = (await ctx.db.client_package.get(usage.client_package as never)) as unknown as Row | null;
    if (!pkg || typeof pkg.visits_left !== "number") return { ok: true };
    const left = Math.max(0, pkg.visits_left + (usage.kind === "return" ? 1 : -1));
    const status = left === 0 && pkg.status === "active" ? "used_up" : left > 0 && pkg.status === "used_up" ? "active" : pkg.status;
    await ctx.db.client_package.patch(pkg.id as never, { visits_left: left, status } as never);`
        : ""
    }
    return { ok: true };
  },
});
`;
}

export function writeOffSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  return `// Generated by the module «Абонементы и пакеты» (B2-18): a booking takes a visit off a valid package.
// A visitor's booking without one is cancelled at once (the time is released); a booking made by the team keeps its
// time and is marked «Нет действующего абонемента». Idempotent: a marked booking is left as is.
import { type MutationCtx, mutation, v } from "@wizard/sdk";

${DAYS}
${findSource(ctx)}
export default mutation({
  args: { id: v.id("booking") },
  handler: async (ctx, args) => {
    const booking = (await ctx.db.booking.get(args.id)) as unknown as Row | null;
    if (!booking || booking.package_status || booking.status === "cancelled") return { ok: false };
    const at = Date.parse(String(booking.starts_at));
    const pkg = await findPackage(ctx.db, text(booking.phone), text(booking.email), dayOf(Number.isNaN(at) ? ctx.now.getTime() : at));
    if (!pkg) {
      await ctx.db.booking.patch(
        args.id,
        (booking.created_by ? { package_status: "no_package" } : { package_status: "no_package", status: "cancelled", seat: null }) as never,
      );
      return { ok: false };
    }
    await ctx.db.package_usage.insert({
      client_package: pkg.id,
      kind: "write_off",
      used_at: ctx.now.toISOString(),
      booking: args.id,
      applied: true,
    } as never);${
      k.visits
        ? `
    if (typeof pkg.visits_left === "number") {
      const left = Math.max(0, pkg.visits_left - 1);
      await ctx.db.client_package.patch(pkg.id as never, { visits_left: left, ...(left === 0 ? { status: "used_up" } : {}) } as never);
    }`
        : ""
    }
    await ctx.db.booking.patch(args.id, { client_package: pkg.id, package_status: "written_off" } as never);
    return { ok: true };
  },
});
`;
}

export function returnVisitSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  return `// Generated by the module «Абонементы и пакеты» (B2-18): a cancelled booking gives its visit back, once.
import { mutation, v } from "@wizard/sdk";

type Row = Record<string, unknown>;

export default mutation({
  args: { id: v.id("booking") },
  handler: async (ctx, args) => {
    const booking = (await ctx.db.booking.get(args.id)) as unknown as Row | null;
    if (!booking || booking.package_status !== "written_off" || !booking.client_package) return { ok: false };
    const pkg = (await ctx.db.client_package.get(booking.client_package as never)) as unknown as Row | null;
    await ctx.db.booking.patch(args.id, { package_status: "returned" } as never);
    if (!pkg) return { ok: false };
    await ctx.db.package_usage.insert({
      client_package: pkg.id,
      kind: "return",
      used_at: ctx.now.toISOString(),
      booking: args.id,
      applied: true,
    } as never);${
      k.visits
        ? `
    if (typeof pkg.visits_left === "number")
      await ctx.db.client_package.patch(pkg.id as never, {
        visits_left: pkg.visits_left + 1,
        ...(pkg.status === "used_up" ? { status: "active" } : {}),
      } as never);`
        : ""
    }
    return { ok: true };
  },
});
`;
}

export function packageCheckSource(ctx: GenContext): string {
  return `// Generated by the module «Абонементы и пакеты» (B2-18): the booking page asks whether these contacts have a valid
// package on the day of the visit. The answer is only yes or no — no names, terms or remaining visits.
import { type MutationCtx, mutation, v } from "@wizard/sdk";

${DAYS}
${findSource(ctx)}
export default mutation({
  args: { phone: v.string({ max: 32 }), email: v.optional(v.string({ max: 254 })), starts_at: v.datetime() },
  handler: async (ctx, args) => {
    const pkg = await findPackage(ctx.systemDb, text(args.phone), text(args.email ?? null), dayOf(Date.parse(args.starts_at)));
    return { ok: pkg !== null };
  },
});
`;
}

export function unfreezeSource(): string {
  return `// Generated by the module «Абонементы и пакеты» (B2-18): the days a package was frozen move its end date.
import { mutation, v } from "@wizard/sdk";

${DAYS}
export default mutation({
  args: { id: v.id("client_package") },
  handler: async (ctx, args) => {
    const pkg = (await ctx.db.client_package.get(args.id)) as unknown as Row | null;
    const since = pkg ? Date.parse(String(pkg.frozen_at ?? "")) : Number.NaN;
    if (!pkg || Number.isNaN(since)) return { ok: false };
    const days = Math.max(0, Math.ceil((ctx.now.getTime() - since) / DAY));
    const end = text(pkg.expires_on);
    await ctx.db.client_package.patch(args.id, { frozen_at: null, ...(end ? { expires_on: addDays(end, days) } : {}) } as never);
    return { ok: true, days };
  },
});
`;
}

/**
 * myMaterials: the team (roles that read package_material) gets every material; a visitor gets the active ones only
 * with a valid package of his own (his rows of client_package by the cabinet's rowFilter).
 */
export function myMaterialsSource(ctx: GenContext): string {
  const k = packageKind(ctx.params);
  const team = ctx.spec.permissions
    .filter((p) => p.entity === "package_material" && p.ops.includes("read"))
    .map((p) => p.role)
    .sort();
  return `// Generated by the module «Абонементы и пакеты» (B2-18): the members' materials of a client with a valid package.
import { query } from "@wizard/sdk";

${DAYS}
const TEAM: readonly string[] = ${JSON.stringify(team)};

export default query({
  args: {},
  handler: async (ctx) => {
    const team = TEAM.includes(ctx.user.role);
    if (!team) {
      if (ctx.user.id === null) return { access: false, items: [] };
      const today = dayOf(ctx.now.getTime());
      // The visitor's own packages (rowFilter by his login contact); a role without the right sees none.
      const own = (await ctx.db.client_package.list({ limit: 100 }).catch(() => [])) as unknown as Row[];
      const valid = own.some(
        (r) =>
          r.status === "active" &&
          !(typeof r.starts_on === "string" && r.starts_on > today)${
            k.period ? ` &&\n          !(typeof r.expires_on === "string" && r.expires_on < today)` : ""
          },
      );
      if (!valid) return { access: false, items: [] };
    }
    const db = team ? ctx.db : ctx.systemDb;
    const rows = (await db.package_material.list({ limit: 100 })) as unknown as Row[];
    const items = rows
      .filter((r) => r.active !== false)
      .sort((a, b) => Number(a.sort_order ?? 0) - Number(b.sort_order ?? 0) || String(a.title).localeCompare(String(b.title)))
      .map((r) => ({ id: String(r.id), title: String(r.title ?? ""), description: text(r.description), link: text(r.link) }));
    return { access: true, items };
  },
});
`;
}

/** Whether the booking link's functions are compiled (for tests and the page). */
export const bookingLinked = (ctx: GenContext): boolean => writesOff(ctx);
