// The page «Материалы» of «Абонементы и пакеты» (screen generator, parameter materials): video lessons, files and
// links for clients with a valid package. The list comes from the query myMaterials: the team sees everything, a
// signed-in client — only with a valid package of his own; nobody else reads the materials.
import { js } from "../screens/jsx.js";
import type { ScreenContext } from "../types.js";

export function materialsPage(ctx: ScreenContext): string {
  const label = String(ctx.params.material_label ?? "Материал");
  const pkg = String(ctx.params.package_label ?? "Абонемент").toLowerCase();
  const text = {
    title: "Материалы",
    intro: `${label}: доступно клиентам с действующим ${pkg === "абонемент" ? "абонементом" : `«${pkg}»`}.`,
    empty: "Материалов пока нет",
    noAccess: `Материалы откроются, когда у вас будет действующий ${pkg === "абонемент" ? "абонемент" : `«${pkg}»`}. Если вы его уже купили, войдите с той же почтой или телефоном, что оставили при покупке.`,
    open: "Открыть",
  };
  return `// Generated by the module «Абонементы и пакеты» (B2-18): the members' materials of a client with a valid package.
import { useQuery } from "@wizard/sdk";
import { EmptyState, Loading } from "@wizard/ui-kit";

const TEXT = ${js(text)};
const list = { display: "grid", gap: 16, padding: 0, listStyle: "none" } as const;
const card = { border: "1px solid var(--wz-color-border, #ddd)", borderRadius: 12, padding: 16, overflowWrap: "anywhere" } as const;

export default function Materials() {
  const r = useQuery("myMaterials", {});
  return (
    <main data-testid="package-materials">
      <h1>{TEXT.title}</h1>
      <p>{TEXT.intro}</p>
      {r.isLoading ? (
        <Loading />
      ) : !r.data?.access ? (
        <EmptyState text={TEXT.noAccess} />
      ) : r.data.items.length === 0 ? (
        <EmptyState text={TEXT.empty} />
      ) : (
        <ul style={list}>
          {r.data.items.map((m) => (
            <li key={m.id} style={card}>
              <h2>{m.title}</h2>
              {m.description ? <p>{m.description}</p> : null}
              {m.link ? (
                <a href={m.link} target="_blank" rel="noopener noreferrer">
                  {TEXT.open}
                </a>
              ) : null}
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}
`;
}
