// Test harness: unique DB role + schemas per test file, forum spec, request builder, value generators.
import { randomBytes, randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import {
  type AppSpec,
  dropSystemRoleDDL,
  type Entity,
  type Field,
  quoteIdent,
  USERS_ENTITY,
} from "@wizard/appspec";
import postgres from "postgres";
import {
  createRuntimeApp,
  MemoryRegistry,
  migrateSystem,
  type RuntimeApp,
  type RuntimeAppOptions,
  type RuntimeEnv,
  schemaName,
} from "../src/index.js";

export const DB_URL =
  process.env.WIZARD_DB_URL ?? process.env.DATABASE_URL ?? "postgres://wizard@localhost:5433/wizard";

export const repoRoot = join(import.meta.dirname, "..", "..", "..");

export function forumSpec(): AppSpec {
  return JSON.parse(readFileSync(join(repoRoot, "specs/appspec/examples/forum.json"), "utf8")) as AppSpec;
}

export const devEnv: RuntimeEnv = {
  authModeDev: true,
  devLogin: true,
  unsafeLocalExec: false,
  publicScheme: "http",
  platformOrigin: "http://localhost:5173",
  systemsDomain: "localhost",
  nodeEnv: "test",
  kubernetes: false,
};

/** 12-char system key [a-z0-9] unique per call. */
export const newKey = () => randomBytes(6).toString("hex");

export interface Harness {
  sql: postgres.Sql;
  role: string;
  rt: RuntimeApp;
  keys: string[];
  /** Migrates the spec into app_<key>_draft and pins it at <slug>--draft.localhost. */
  system(slug: string, spec: AppSpec, env?: "draft" | "prod"): Promise<{ key: string; schema: string }>;
  close(): Promise<void>;
}

export async function harness(
  env: Partial<RuntimeEnv> = {},
  app: Partial<RuntimeAppOptions> = {},
): Promise<Harness> {
  const sql = postgres(DB_URL, { max: 6, onnotice: () => {} });
  const role = `wz_rt_test_${randomBytes(4).toString("hex")}`;
  await sql.unsafe(`CREATE ROLE ${quoteIdent(role)} NOLOGIN NOSUPERUSER NOBYPASSRLS`);
  const rt = createRuntimeApp({
    db: sql,
    registry: new MemoryRegistry(),
    dbRole: role,
    env: { ...devEnv, ...env },
    ...app,
  });
  const keys: string[] = [];
  const schemas: string[] = [];
  return {
    sql,
    role,
    rt,
    keys,
    async system(slug, spec, sysEnv = "draft") {
      const key = newKey();
      keys.push(key);
      schemas.push(schemaName(key, sysEnv));
      await migrateSystem(sql, { systemId: key, env: sysEnv, spec, runtimeRole: role });
      await rt.loadSystem({ systemKey: key, env: sysEnv, spec, slug });
      return { key, schema: schemaName(key, sysEnv) };
    },
    async close() {
      for (const s of schemas) await sql.unsafe(`DROP SCHEMA IF EXISTS ${quoteIdent(s)} CASCADE`);
      for (const s of schemas) for (const st of dropSystemRoleDDL(s)) await sql.unsafe(st);
      await sql.unsafe(`DROP OWNED BY ${quoteIdent(role)}`).catch(() => {});
      await sql.unsafe(`DROP ROLE IF EXISTS ${quoteIdent(role)}`);
      await sql.end();
    },
  };
}

export interface ReqOptions {
  cookie?: string | null;
  body?: unknown;
  headers?: Record<string, string>;
  /** Adds Origin + X-Wizard-Request for non-GET (default true). */
  csrf?: boolean;
}

/** Request to 127.0.0.1:4100 with the given Host (platform/deploy.yaml#local.hosts.note). */
export function request(method: string, host: string, path: string, o: ReqOptions = {}): Request {
  const headers: Record<string, string> = { host, ...o.headers };
  if (o.cookie) headers.cookie = o.cookie;
  if (method !== "GET" && method !== "HEAD" && o.csrf !== false) {
    headers.origin = `http://${host}`;
    headers["x-wizard-request"] = "1";
  }
  let body: string | undefined;
  if (o.body !== undefined) {
    body = typeof o.body === "string" ? o.body : JSON.stringify(o.body);
    headers["content-type"] = "application/json";
  }
  return new Request(`http://127.0.0.1:4100${path}`, { method, headers, body });
}

/** dev-login as a role; returns the Cookie header value. */
export async function login(rt: RuntimeApp, host: string, role: string): Promise<string> {
  const res = await rt.fetch(request("GET", host, `/_wizard/dev-login?role=${role}`));
  if (res.status !== 302) throw new Error(`dev-login ${role}: ${res.status}`);
  const set = res.headers.get("set-cookie") ?? "";
  return set.split(";")[0] as string;
}

// ------------------------------------------------------------------------------------------------
// value generation (satisfies the CHECK/UNIQUE constraints generated by toDDL)

let seq = 0;

export function valueFor(f: Field): unknown {
  seq += 1;
  const uniq = `${seq}${randomBytes(3).toString("hex")}`;
  switch (f.type) {
    case "int":
      return Math.max(f.min ?? 1, 1) + (seq % 5);
    case "decimal":
    case "money":
      return Math.max(f.min ?? 1, 1) + 0.5;
    case "bool":
      return true;
    case "date":
      return "2026-10-01";
    case "datetime":
      return "2026-10-01T10:00:00.000Z";
    case "enum":
      return f.enum?.[0]?.value;
    case "json":
      return { n: seq };
    case "email":
      return `u${uniq}@example.ru`;
    case "phone":
      return `+7999${String(1_000_000 + (seq % 8_999_999)).padStart(7, "0")}`;
    case "url":
      return `https://example.ru/${uniq}`;
    case "qr_token":
      return `qr_${uniq}`;
    default:
      return `v${uniq}`.slice(0, f.maxLength ?? 255);
  }
}

/** Inserts a row as the superuser (bypasses RLS); refs to entities are seeded recursively. */
export async function seedRow(
  sql: postgres.Sql,
  schema: string,
  spec: AppSpec,
  entity: string,
  overrides: Record<string, unknown> = {},
  userId?: string,
): Promise<string> {
  const e = spec.entities.find((x) => x.name === entity) as Entity;
  const row: Record<string, unknown> = { id: randomUUID() };
  for (const f of e.fields) {
    if (Object.hasOwn(overrides, f.name)) {
      row[f.name] = overrides[f.name];
      continue;
    }
    if (f.type === "ref") {
      const target = f.ref?.entity ?? "";
      if (target === USERS_ENTITY) row[f.name] = userId ?? (await seedUser(sql, schema, "organizer"));
      else if (f.required) row[f.name] = await seedRow(sql, schema, spec, target, {}, userId);
      continue;
    }
    row[f.name] = f.type === "json" ? JSON.stringify(valueFor(f)) : valueFor(f);
  }
  const cols = Object.keys(row);
  await sql.unsafe(
    `insert into ${quoteIdent(schema)}.${quoteIdent(entity)} (${cols.map(quoteIdent).join(", ")}) values (${cols
      .map((_, i) => `$${i + 1}`)
      .join(", ")})`,
    cols.map((c) => row[c]) as never[],
  );
  return row.id as string;
}

export async function seedUser(sql: postgres.Sql, schema: string, role: string): Promise<string> {
  const id = randomUUID();
  await sql.unsafe(`insert into ${quoteIdent(schema)}."users" (id, role, display_name) values ($1, $2, $3)`, [
    id,
    role,
    `seed-${role}`,
  ]);
  return id;
}

export async function userIdOf(sql: postgres.Sql, schema: string, role: string): Promise<string> {
  const rows = await sql.unsafe(`select id from ${quoteIdent(schema)}."users" where email = $1`, [
    `dev-${role}@dev.localhost`,
  ]);
  return String(rows[0]?.id);
}
