// M0-24 fixtures: forum bundle built by @wizard/build into a temp artifacts root, a registry pointing at it,
// and a runtime with a fixed QR keyring. Uses the DB harness conventions of ./helpers.ts.
import { mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type AppSpec, quoteIdent } from "@wizard/appspec";
import { buildSystem, writeArtifact } from "@wizard/build";
import { newQrKeyring, type QrKeyring, serializeQrKeyring, staticSecretReader } from "@wizard/connectors";
import postgres from "postgres";
import {
  createRuntimeApp,
  MemoryRegistry,
  migrateSystem,
  type RegistryEntry,
  type RuntimeApp,
  type RuntimeEnv,
  schemaName,
} from "../src/index.js";
import { DB_URL, devEnv, forumSpec, newKey, repoRoot } from "./helpers.js";

const EXAMPLES = join(repoRoot, "specs/runtime/examples");
const GENERATED = join(import.meta.dirname, "..", ".generated");

export function forumFiles(): Map<string, string> {
  const files = new Map<string, string>();
  for (const top of ["ui", "functions"]) {
    for (const f of readdirSync(join(EXAMPLES, top), { recursive: true, encoding: "utf8" }).sort()) {
      if (/\.tsx?$/.test(f))
        files.set(`${top}/${f.split("\\").join("/")}`, readFileSync(join(EXAMPLES, top, f), "utf8"));
    }
  }
  return files;
}

/** Stand-in for @wizard/ui-kit exporting every component the forum pages import (M0-25 pending). */
export function uiKitStub(): string {
  const names = new Set<string>();
  for (const src of forumFiles().values()) {
    for (const m of src.matchAll(/import\s*\{([^}]*)\}\s*from\s*"@wizard\/ui-kit"/g)) {
      for (const n of (m[1] ?? "").split(",")) {
        const name = n.replace(/^\s*type\s+/, "").trim();
        if (name) names.add(name);
      }
    }
  }
  const dir = join(GENERATED, "ui-kit-stub");
  mkdirSync(dir, { recursive: true });
  const body = [
    "// generated by test/preview-helpers.ts",
    "type P = { wzId?: string; children?: unknown; [k: string]: unknown };",
    ...[...names]
      .sort()
      .map(
        (n) =>
          `export const ${n} = (p: P) => <div data-wz-component="${n}" data-wz-id={p.wzId ?? "demo:${n}:0"}>{p.children as never}</div>;`,
      ),
    // The client entry template mounts WzProvider (ui-kit.yaml#data_binding.provider).
    "export const WzProvider = (p: P) => p.children as never;",
    "",
  ].join("\n");
  const file = join(dir, "index.tsx");
  writeFileSync(file, body);
  return file;
}

export const PLATFORM = "http://localhost:5173";

export interface PreviewFixture {
  root: string;
  sql: postgres.Sql;
  role: string;
  rt: RuntimeApp;
  ring: QrKeyring;
  registry: MemoryRegistry;
  /** Builds the forum for `env`, writes revision `revision` and registers <slug>--<env>. */
  publish(o: {
    slug: string;
    env: "draft" | "prod";
    revision: number;
    key?: string;
    spec?: AppSpec;
    migrate?: boolean;
    /** Build with the real @wizard/ui-kit instead of the stub (browser tests). */
    realUiKit?: boolean;
  }): Promise<RegistryEntry>;
  close(): Promise<void>;
}

export async function previewFixture(env: Partial<RuntimeEnv> = {}): Promise<PreviewFixture> {
  const root = mkdtempSync(join(tmpdir(), "wz-rt-preview-"));
  const sql = postgres(DB_URL, { max: 8, onnotice: () => {} });
  const role = `wz_rt_prev_${newKey()}`;
  await sql.unsafe(`CREATE ROLE ${quoteIdent(role)} NOLOGIN NOSUPERUSER NOBYPASSRLS`);
  const ring = newQrKeyring();
  const registry = new MemoryRegistry();
  const rt = createRuntimeApp({
    db: sql,
    registry,
    dbRole: role,
    artifactsRoot: join(root, "artifacts"),
    env: { ...devEnv, platformOrigin: PLATFORM, ...env },
    secrets: () => staticSecretReader({ qr_signing_key: serializeQrKeyring(ring) }),
  });
  const schemas: string[] = [];
  const uiKit = uiKitStub();
  return {
    root,
    sql,
    role,
    rt,
    ring,
    registry,
    async publish({
      slug,
      env: sysEnv,
      revision,
      key = newKey(),
      spec = forumSpec(),
      migrate = false,
      realUiKit = false,
    }) {
      const built = await buildSystem({
        spec,
        files: forumFiles(),
        env: sysEnv,
        platformOrigin: PLATFORM,
        ...(realUiKit ? {} : { hostModules: { uiKit } }),
      });
      if (!built.ok) throw new Error(JSON.stringify(built.errors));
      const written = writeArtifact(join(root, "artifacts"), key, revision, built);
      if (migrate) {
        await migrateSystem(sql, { systemId: key, env: sysEnv, spec, runtimeRole: role });
        schemas.push(schemaName(key, sysEnv));
      }
      const entry: RegistryEntry = {
        systemId: key,
        slug,
        env: sysEnv,
        revision,
        specHash: written.manifest.specHash,
        bundleKey: written.bundleKey,
        publishedAt: new Date().toISOString(),
        suspended: false,
        features: { phoneOtp: false },
      };
      registry.list.push(entry);
      return entry;
    },
    async close() {
      for (const s of schemas) await sql.unsafe(`DROP SCHEMA IF EXISTS ${quoteIdent(s)} CASCADE`);
      await sql.unsafe(`DROP OWNED BY ${quoteIdent(role)}`).catch(() => {});
      await sql.unsafe(`DROP ROLE IF EXISTS ${quoteIdent(role)}`);
      await sql.end();
      rmSync(root, { recursive: true, force: true });
    },
  };
}
