// M0-24: qr_token issued by the runtime (qr.yaml#token) and POST /_wizard/qr/check (qr.yaml#endpoints,
// #checkin_algorithm) over HTTP — forum AC4: second check → duplicate; 20 parallel checks → exactly one ok.
import { randomUUID } from "node:crypto";
import type { AppSpec } from "@wizard/appspec";
import { type QrCheckResponse, signQrToken, verifyQrToken } from "@wizard/connectors";
import { afterAll, beforeAll, describe, expect, test } from "vitest";
import { SYSTEM_SUBJECT } from "../src/index.js";
import { forumSpec, login, request, seedRow, seedUser, userIdOf } from "./helpers.js";
import { type PreviewFixture, previewFixture } from "./preview-helpers.js";

const TOKEN_RE = /^WZ1\.\d+\.[A-Z2-7]{26}\.[A-Za-z0-9_-]{16}$/;
let fx: PreviewFixture;
let key: string;
let schema: string;
const HOST = "forumqr--draft.localhost:4100";

/** Forum with create on ticket for participants: lets the data API path of qr_token be exercised. */
function specWithParticipantCreate(): AppSpec {
  const spec = forumSpec();
  const p = spec.permissions.find((x) => x.role === "participant" && x.entity === "ticket");
  if (p) p.ops = ["read", "create"];
  return spec;
}

async function newTicket(status = "paid", holder?: string): Promise<{ id: string; token: string }> {
  const sys = await fx.rt.systems.resolve("forumqr", "draft");
  if (!sys) throw new Error("system not loaded");
  const stream = await seedRow(fx.sql, schema, sys.spec, "stream", { name: "Технологии" });
  const type = await seedRow(fx.sql, schema, sys.spec, "ticket_type", { name: "VIP" });
  const user = holder ?? (await seedUser(fx.sql, schema, "participant"));
  const id = await sys.data.transaction("default", SYSTEM_SUBJECT, (tx) =>
    tx.system.insert("ticket", {
      ticket_type: type,
      stream,
      holder_user: user,
      holder_name: "Иван Петров",
      holder_email: `t${randomUUID().slice(0, 8)}@example.ru`,
      status,
      amount: 1500,
      event_starts_at: "2026-11-01T09:00:00.000Z",
    }),
  );
  const rows = await fx.sql.unsafe(`select qr_token from "${schema}"."ticket" where id = $1`, [id]);
  return { id, token: String(rows[0]?.qr_token) };
}

const check = (cookie: string | null, body: unknown, o: { csrf?: boolean } = {}) =>
  fx.rt.fetch(request("POST", HOST, "/_wizard/qr/check", { cookie, body, ...o }));

beforeAll(async () => {
  fx = await previewFixture();
  const entry = await fx.publish({
    slug: "forumqr",
    env: "draft",
    revision: 1,
    spec: specWithParticipantCreate(),
    migrate: true,
  });
  key = entry.systemId;
  schema = `app_${key}_draft`;
}, 60_000);
afterAll(() => fx?.close());

describe("qr_token is generated by the runtime", () => {
  test("system insert gets a signed WZ1 payload of this system and env", async () => {
    const { token } = await newTicket();
    expect(token).toMatch(TOKEN_RE);
    expect(verifyQrToken(token, fx.ring, { systemId: key, env: "draft" }, new Date()).ok).toBe(true);
    expect(verifyQrToken(token, fx.ring, { systemId: key, env: "prod" }, new Date()).ok).toBe(false);
  });

  test("data API: qr_token in the create body → 422 FIELD_READONLY; without it the runtime issues one", async () => {
    const cookie = await login(fx.rt, HOST, "participant");
    const me = await userIdOf(fx.sql, schema, "participant");
    const spec = (await (await fx.rt.fetch(request("GET", HOST, "/_wizard/spec", { cookie }))).json()) as {
      compliance: { policyVersion: string; consentTextHash: string };
    };
    const sys = await fx.rt.systems.resolve("forumqr", "draft");
    const body = {
      ticket_type: await seedRow(fx.sql, schema, sys?.spec as AppSpec, "ticket_type"),
      stream: await seedRow(fx.sql, schema, sys?.spec as AppSpec, "stream"),
      holder_user: me,
      holder_name: "Анна",
      holder_email: `a${randomUUID().slice(0, 8)}@example.ru`,
      status: "pending_payment",
      amount: 100,
      event_starts_at: "2026-11-01T09:00:00.000Z",
      _consent: { policyVersion: spec.compliance.policyVersion, textHash: spec.compliance.consentTextHash },
    };
    const bad = await fx.rt.fetch(
      request("POST", HOST, "/api/data/ticket", { cookie, body: { ...body, qr_token: "WZ1.1.FAKE.x" } }),
    );
    expect(bad.status).toBe(422);
    const err = (await bad.json()) as { error: { code: string; details: { fields?: { field: string }[] } } };
    expect(JSON.stringify(err)).toContain("FIELD_READONLY");
    expect(JSON.stringify(err)).toContain("qr_token");

    const ok = await fx.rt.fetch(request("POST", HOST, "/api/data/ticket", { cookie, body }));
    expect(ok.status).toBe(201);
    const { item } = (await ok.json()) as { item: { id: string; qr_token: string } };
    expect(item.qr_token).toMatch(TOKEN_RE);
    expect(verifyQrToken(item.qr_token, fx.ring, { systemId: key, env: "draft" }, new Date()).ok).toBe(true);
  });
});

describe("POST /_wizard/qr/check", () => {
  test("AC4: first scan ok with ticket title, second → duplicate with the first scan time and gate", async () => {
    const { token } = await newTicket("paid");
    const cookie = await login(fx.rt, HOST, "volunteer");
    const first = await check(cookie, { payload: token, deviceId: "dev-1", checkpoint: "Главный вход" });
    expect(first.status).toBe(200);
    const a = (await first.json()) as QrCheckResponse;
    expect(a).toMatchObject({ status: "ok", ticketTitle: "VIP", details: "Технологии" });
    expect(JSON.stringify(a)).not.toContain("Иван");
    const second = await check(cookie, { payload: token, deviceId: "dev-2" });
    const b = (await second.json()) as QrCheckResponse;
    expect(b.status).toBe("duplicate");
    expect(b.firstCheckpoint).toBe("Главный вход");
    expect(Date.parse(b.firstScannedAt ?? "")).toBe(Date.parse(a.scannedAt));
  });

  test("AC4: 20 parallel checks of one payload → exactly one ok", async () => {
    const { token } = await newTicket("issued");
    const cookie = await login(fx.rt, HOST, "organizer");
    const results = await Promise.all(
      Array.from({ length: 20 }, (_, i) =>
        check(cookie, { payload: token, deviceId: `dev-${i}` }).then(async (r) => {
          expect(r.status).toBe(200);
          return ((await r.json()) as QrCheckResponse).status;
        }),
      ),
    );
    expect(results.filter((s) => s === "ok")).toHaveLength(1);
    expect(results.filter((s) => s === "duplicate")).toHaveLength(19);
    const rows = await fx.sql.unsafe(`select count(*)::int as n from "${schema}"."checkin"`);
    expect(Number(rows[0]?.n)).toBeGreaterThanOrEqual(1);
  });

  test("invalid payloads: tampered → bad_signature, unknown → not_found, wrong status → not_valid_status", async () => {
    const cookie = await login(fx.rt, HOST, "volunteer");
    const { token } = await newTicket("paid");
    const last = token.at(-1) === "A" ? "B" : "A";
    const tampered = `${token.slice(0, -1)}${last}`;
    const body = async (payload: string) =>
      (await (await check(cookie, { payload, deviceId: "d" })).json()) as QrCheckResponse;
    expect(await body(tampered)).toMatchObject({ status: "invalid", reason: "bad_signature" });
    expect(await body("garbage")).toMatchObject({ status: "invalid", reason: "bad_signature" });
    const foreign = signQrToken(fx.ring, { systemId: "otherkey0000", env: "draft" });
    expect(await body(foreign)).toMatchObject({ status: "invalid", reason: "bad_signature" });
    const unknown = signQrToken(fx.ring, { systemId: key, env: "draft" });
    expect(await body(unknown)).toMatchObject({ status: "invalid", reason: "not_found" });
    const pending = await newTicket("pending_payment");
    expect(await body(pending.token)).toMatchObject({ status: "invalid", reason: "not_valid_status" });
  });

  test("roles outside scannerRoles → 403; the public role too", async () => {
    const { token } = await newTicket("paid");
    const participant = await login(fx.rt, HOST, "participant");
    expect((await check(participant, { payload: token, deviceId: "d" })).status).toBe(403);
    expect((await check(null, { payload: token, deviceId: "d" })).status).toBe(403);
  });

  test("CSRF: without Origin/X-Wizard-Request → 403", async () => {
    const cookie = await login(fx.rt, HOST, "volunteer");
    const { token } = await newTicket("paid");
    expect((await check(cookie, { payload: token, deviceId: "d" }, { csrf: false })).status).toBe(403);
  });

  test("body validation → 422; unknown integration → 404; manifest/sync → 501 until M2", async () => {
    const cookie = await login(fx.rt, HOST, "volunteer");
    expect((await check(cookie, { payload: "x" })).status).toBe(422);
    expect((await check(cookie, [1, 2])).status).toBe(422);
    const other = await fx.rt.fetch(
      request("POST", HOST, "/_wizard/qr/check?integration=nope", {
        cookie,
        body: { payload: "x", deviceId: "d" },
      }),
    );
    expect(other.status).toBe(404);
    expect((await fx.rt.fetch(request("GET", HOST, "/_wizard/qr/manifest", { cookie }))).status).toBe(501);
  });
});
