// Templates first (product.yaml#decisions.D75_templates_first): the screens of a system class are generated by code from
// the spec, never written by a model. ui-kit components bind to entities through the data API under the role's
// permissions (LeadForm, DataTable, RecordCard, RecordForm), so the pages need no server functions: a landing with the
// lead form for the public role and a cabinet per login role with a table, a card with status actions and a create
// form for every entity the role may read. The model only writes the landing texts (submit_landing, from the card).
// The page generators are shared with the module engine (@wizard/modules, B2-11).
import type { AppSpec } from "@wizard/appspec";
import { cabinetPage, cabinetRoute, can, fragmentPage, js, jsxEl, startPage } from "@wizard/modules";
import { z } from "zod";
import { defineTool } from "../core/index.js";
import type { BuildCard } from "./types.js";

/**
 * Card segments built from the template (D75 order: site with leads first, then booking and CRM on the same screens).
 * Booking needs no function either: the visitor creates the booking through LeadForm (service ref, starts_at), one
 * time — one booking by a unique index (the runtime answers CONFLICT), the staff confirm and cancel in the cabinet.
 */
export const TEMPLATE_SEGMENTS: ReadonlySet<string> = new Set(["site", "booking", "crm"]);

const line = (max: number) => z.string().trim().min(1).max(max);

export const landingSchema = z.object({
  hero: z.object({
    eyebrow: line(60).optional(),
    title: line(90),
    subtitle: line(220).optional(),
    cta: line(30),
  }),
  features: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ title: line(60), text: line(220).optional() }))
        .min(1)
        .max(6),
    })
    .optional(),
  steps: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ title: line(60), text: line(200).optional() }))
        .min(2)
        .max(5),
    })
    .optional(),
  faq: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ question: line(140), answer: line(400) }))
        .min(1)
        .max(6),
    })
    .optional(),
  form: z.object({ title: line(60), intro: line(220).optional(), submitLabel: line(30).optional() }),
  footer: z.object({ text: line(200).optional() }).optional(),
});
export type LandingTexts = z.infer<typeof landingSchema>;

export const submitLandingTool = () =>
  defineTool({
    name: "submit_landing",
    description: "Texts of the public landing page of the system, only from the card.",
    input: landingSchema,
  });

export const LANDING_SYSTEM = [
  "Ты пишешь тексты лендинга системы по её карточке. Все тексты — на русском, коротко и по делу.",
  "Только факты из карточки: что предлагают, кому, как это работает. Не придумывай цены, адреса, отзывы, цифры и обещания.",
  "Если фактов для блока нет, не заполняй его (features, steps, faq необязательны). Ответ — вызов submit_landing.",
].join("\n");

/** Texts without a model: the card's title and summary (the fallback when submit_landing fails). */
export function fallbackLanding(card: BuildCard): LandingTexts {
  const title = String(card.title ?? "Оставьте заявку").slice(0, 90);
  return {
    hero: {
      title,
      ...(card.summary ? { subtitle: String(card.summary).slice(0, 220) } : {}),
      cta: "Оставить заявку",
    },
    form: { title: "Оставьте заявку", intro: "Мы свяжемся с вами и ответим на вопросы." },
  };
}

type Op = Record<string, unknown>;

/** Why the spec does not fit the template (empty — it fits). */
export function templateGaps(spec: AppSpec): string[] {
  const out: string[] = [];
  if ((spec.functions ?? []).length > 0) out.push("в спеке есть серверные функции — их пишет харнесс");
  if (!spec.roles.some((r) => r.access === "login")) out.push("нет роли со входом для кабинета");
  if (spec.entities.length === 0) out.push("нет сущностей");
  return out;
}

export interface TemplateResult {
  ops: Op[];
  files: [string, string][];
}

/** Pages of the template for this spec: add_page ops and the TSX files (deterministic). */
export function templatePages(spec: AppSpec, texts: LandingTexts): TemplateResult {
  const ops: Op[] = [];
  const files: [string, string][] = [];
  const publicRole = spec.roles.find((r) => r.access === "public");
  const loginRoles = spec.roles.filter((r) => r.access === "login");
  const leadEntity = publicRole
    ? spec.entities.find((e) => can(spec, publicRole.name, e.name, "create"))
    : undefined;
  const catalog = publicRole
    ? spec.entities.filter((e) => e !== leadEntity && can(spec, publicRole.name, e.name, "read"))
    : [];

  // Cabinets: one per login role, with the entities it may read.
  const cabinets: { role: (typeof loginRoles)[number]; route: string; file: string }[] = [];
  for (const [i, role] of loginRoles.entries()) {
    const readable = spec.entities.filter((e) => can(spec, role.name, e.name, "read"));
    if (readable.length === 0) continue;
    const { route, file } = cabinetRoute(role.name, i === 0);
    cabinets.push({ role, route, file });
    ops.push({
      op: "add_page",
      route,
      title: `Кабинет: ${role.label}`.slice(0, 80),
      file,
      roles: [role.name],
    });
    files.push([
      file,
      cabinetPage(
        spec,
        role.name,
        role.label,
        readable.map((e) => e.name),
      ),
    ]);
  }

  // Home: the landing for the public role (and everyone), else a short start page for the login roles.
  const homeRoles = [...(publicRole ? [publicRole.name] : []), ...loginRoles.map((r) => r.name)];
  ops.push({
    op: "add_page",
    route: "/",
    title: "Главная",
    file: "ui/pages/Home.tsx",
    roles: homeRoles,
    nav: true,
  });
  files.push([
    "ui/pages/Home.tsx",
    publicRole
      ? landingPage(
          spec,
          texts,
          leadEntity?.name,
          catalog.map((e) => ({ name: e.name, label: e.label })),
        )
      : startPage(texts.hero.title || spec.app.name, texts.hero.subtitle, cabinets[0]?.route),
  ]);
  return { ops, files };
}

function landingPage(
  spec: AppSpec,
  t: LandingTexts,
  lead: string | undefined,
  catalog: { name: string; label: string }[],
): string {
  const imports = new Set(["Header", "Hero", "Footer"]);
  const blocks: string[] = [];
  const brand = spec.app.name;
  const links: { label: string; href: string }[] = [];
  if (t.features) links.push({ label: t.features.title, href: "#features" });
  if (t.faq) links.push({ label: t.faq.title, href: "#faq" });
  if (lead) links.push({ label: t.form.title, href: "#lead" });
  const toForm = lead ? { label: t.hero.cta, href: "#lead" } : undefined;
  blocks.push(
    jsxEl("Header", [
      ["brand", brand],
      ["links", links],
      ["cta", toForm],
      ["sticky", true],
    ]),
  );
  blocks.push(
    jsxEl("Hero", [
      ["title", t.hero.title],
      ["subtitle", t.hero.subtitle],
      ["eyebrow", t.hero.eyebrow],
      ["primary", toForm],
      ["variant", "centered", "lit"],
    ]),
  );
  if (t.features) {
    imports.add("Features");
    blocks.push(
      jsxEl("Features", [
        ["title", t.features.title],
        ["items", t.features.items],
        ["anchor", "features", "lit"],
      ]),
    );
  }
  for (const c of catalog) {
    imports.add("DataTable");
    blocks.push(
      `<section aria-label={${js(c.label)}}>\n        <h2>{${js(c.label)}}</h2>\n        <DataTable entity={${js(c.name)}} emptyText="Скоро здесь появятся записи" />\n      </section>`,
    );
  }
  if (t.steps) {
    imports.add("Steps");
    blocks.push(
      jsxEl("Steps", [
        ["title", t.steps.title],
        ["steps", t.steps.items],
        ["tone", "alt", "lit"],
      ]),
    );
  }
  if (t.faq) {
    imports.add("Faq");
    blocks.push(
      jsxEl("Faq", [
        ["title", t.faq.title],
        ["items", t.faq.items],
        ["anchor", "faq", "lit"],
      ]),
    );
  }
  if (lead) {
    imports.add("LeadForm");
    blocks.push(
      jsxEl("LeadForm", [
        ["entity", lead],
        ["title", t.form.title],
        ["intro", t.form.intro],
        ["submitLabel", t.form.submitLabel],
      ]),
    );
  }
  blocks.push(
    jsxEl("Footer", [
      ["brand", brand],
      ["text", t.footer?.text],
    ]),
  );
  return fragmentPage(
    "// Generated by the site template (D75): texts from the card, components bound to the data API.",
    imports,
    blocks,
  );
}
