// Templates first (product.yaml#decisions.D75_templates_first): the screens of a system class are generated by code from
// the spec, never written by a model. ui-kit components bind to entities through the data API under the role's
// permissions (LeadForm, DataTable, RecordCard, RecordForm), so the pages need no server functions: a landing with the
// lead form for the public role and a cabinet per login role with a table, a card with status actions and a create
// form for every entity the role may read. The model only writes the landing texts (submit_landing, from the card).
import type { AppSpec } from "@wizard/appspec";
import { z } from "zod";
import { defineTool } from "../core/index.js";
import type { BuildCard } from "./types.js";

/**
 * Card segments built from the template (D75 order: site with leads first, then booking and CRM on the same screens).
 * Booking needs no function either: the visitor creates the booking through LeadForm (service ref, starts_at), one
 * time — one booking by a unique index (the runtime answers CONFLICT), the staff confirm and cancel in the cabinet.
 */
export const TEMPLATE_SEGMENTS: ReadonlySet<string> = new Set(["site", "booking", "crm"]);

const line = (max: number) => z.string().trim().min(1).max(max);

export const landingSchema = z.object({
  hero: z.object({
    eyebrow: line(60).optional(),
    title: line(90),
    subtitle: line(220).optional(),
    cta: line(30),
  }),
  features: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ title: line(60), text: line(220).optional() }))
        .min(1)
        .max(6),
    })
    .optional(),
  steps: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ title: line(60), text: line(200).optional() }))
        .min(2)
        .max(5),
    })
    .optional(),
  faq: z
    .object({
      title: line(60),
      items: z
        .array(z.object({ question: line(140), answer: line(400) }))
        .min(1)
        .max(6),
    })
    .optional(),
  form: z.object({ title: line(60), intro: line(220).optional(), submitLabel: line(30).optional() }),
  footer: z.object({ text: line(200).optional() }).optional(),
});
export type LandingTexts = z.infer<typeof landingSchema>;

export const submitLandingTool = () =>
  defineTool({
    name: "submit_landing",
    description: "Texts of the public landing page of the system, only from the card.",
    input: landingSchema,
  });

export const LANDING_SYSTEM = [
  "Ты пишешь тексты лендинга системы по её карточке. Все тексты — на русском, коротко и по делу.",
  "Только факты из карточки: что предлагают, кому, как это работает. Не придумывай цены, адреса, отзывы, цифры и обещания.",
  "Если фактов для блока нет, не заполняй его (features, steps, faq необязательны). Ответ — вызов submit_landing.",
].join("\n");

/** Texts without a model: the card's title and summary (the fallback when submit_landing fails). */
export function fallbackLanding(card: BuildCard): LandingTexts {
  const title = String(card.title ?? "Оставьте заявку").slice(0, 90);
  return {
    hero: {
      title,
      ...(card.summary ? { subtitle: String(card.summary).slice(0, 220) } : {}),
      cta: "Оставить заявку",
    },
    form: { title: "Оставьте заявку", intro: "Мы свяжемся с вами и ответим на вопросы." },
  };
}

type Op = Record<string, unknown>;
type Perm = NonNullable<AppSpec["permissions"]>[number];

const pascal = (s: string) =>
  s
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => p[0]?.toUpperCase() + p.slice(1))
    .join("");
const js = (v: unknown) => JSON.stringify(v);

function perm(spec: AppSpec, role: string, entity: string): Perm | undefined {
  return (spec.permissions ?? []).find((p) => p.role === role && p.entity === entity);
}
const can = (spec: AppSpec, role: string, entity: string, op: "read" | "create" | "update" | "delete") =>
  (perm(spec, role, entity)?.ops ?? []).includes(op);

/** Fields the role sees in a list (not hidden, not qr_token), at most 6. */
function columns(spec: AppSpec, role: string, entity: string): string[] {
  const e = spec.entities.find((x) => x.name === entity);
  const hidden = new Set(perm(spec, role, entity)?.hiddenFields ?? []);
  return (e?.fields ?? [])
    .filter((f) => !hidden.has(f.name) && f.type !== "qr_token" && f.type !== "json")
    .map((f) => f.name)
    .slice(0, 6);
}

/** The status field of an entity: `status` of type enum, else the first enum field. */
function statusField(spec: AppSpec, entity: string) {
  const e = spec.entities.find((x) => x.name === entity);
  const enums = (e?.fields ?? []).filter((f) => f.type === "enum" && f.enum?.length);
  return enums.find((f) => f.name === "status") ?? enums[0];
}

/** Why the spec does not fit the template (empty — it fits). */
export function templateGaps(spec: AppSpec): string[] {
  const out: string[] = [];
  if ((spec.functions ?? []).length > 0) out.push("в спеке есть серверные функции — их пишет харнесс");
  if (!spec.roles.some((r) => r.access === "login")) out.push("нет роли со входом для кабинета");
  if (spec.entities.length === 0) out.push("нет сущностей");
  return out;
}

export interface TemplateResult {
  ops: Op[];
  files: [string, string][];
}

/** Pages of the template for this spec: add_page ops and the TSX files (deterministic). */
export function templatePages(spec: AppSpec, texts: LandingTexts): TemplateResult {
  const ops: Op[] = [];
  const files: [string, string][] = [];
  const publicRole = spec.roles.find((r) => r.access === "public");
  const loginRoles = spec.roles.filter((r) => r.access === "login");
  const leadEntity = publicRole
    ? spec.entities.find((e) => can(spec, publicRole.name, e.name, "create"))
    : undefined;
  const catalog = publicRole
    ? spec.entities.filter((e) => e !== leadEntity && can(spec, publicRole.name, e.name, "read"))
    : [];

  // Cabinets: one per login role, with the entities it may read.
  const cabinets: { role: (typeof loginRoles)[number]; route: string; file: string }[] = [];
  for (const [i, role] of loginRoles.entries()) {
    const readable = spec.entities.filter((e) => can(spec, role.name, e.name, "read"));
    if (readable.length === 0) continue;
    const route = i === 0 ? "/cabinet" : `/cabinet-${role.name.replace(/_/g, "-")}`;
    const file = `ui/pages/Cabinet${i === 0 ? "" : pascal(role.name)}.tsx`;
    cabinets.push({ role, route, file });
    ops.push({
      op: "add_page",
      route,
      title: `Кабинет: ${role.label}`.slice(0, 80),
      file,
      roles: [role.name],
    });
    files.push([
      file,
      cabinetPage(
        spec,
        role.name,
        role.label,
        readable.map((e) => e.name),
      ),
    ]);
  }

  // Home: the landing for the public role (and everyone), else a short start page for the login roles.
  const homeRoles = [...(publicRole ? [publicRole.name] : []), ...loginRoles.map((r) => r.name)];
  ops.push({
    op: "add_page",
    route: "/",
    title: "Главная",
    file: "ui/pages/Home.tsx",
    roles: homeRoles,
    nav: true,
  });
  files.push([
    "ui/pages/Home.tsx",
    publicRole
      ? landingPage(
          spec,
          texts,
          leadEntity?.name,
          catalog.map((e) => ({ name: e.name, label: e.label })),
        )
      : startPage(
          spec,
          texts,
          cabinets.map((c) => ({ route: c.route, label: c.role.label })),
        ),
  ]);
  return { ops, files };
}

function landingPage(
  spec: AppSpec,
  t: LandingTexts,
  lead: string | undefined,
  catalog: { name: string; label: string }[],
): string {
  const imports = new Set(["Header", "Hero", "Footer"]);
  const blocks: string[] = [];
  const brand = spec.app.name;
  const links: { label: string; href: string }[] = [];
  if (t.features) links.push({ label: t.features.title, href: "#features" });
  if (t.faq) links.push({ label: t.faq.title, href: "#faq" });
  if (lead) links.push({ label: t.form.title, href: "#lead" });
  blocks.push(
    `<Header brand={${js(brand)}} links={${js(links)}}${lead ? ` cta={${js({ label: t.hero.cta, href: "#lead" })}}` : ""} sticky />`,
  );
  blocks.push(
    `<Hero title={${js(t.hero.title)}}${t.hero.subtitle ? ` subtitle={${js(t.hero.subtitle)}}` : ""}${t.hero.eyebrow ? ` eyebrow={${js(t.hero.eyebrow)}}` : ""}${lead ? ` primary={${js({ label: t.hero.cta, href: "#lead" })}}` : ""} variant="centered" />`,
  );
  if (t.features) {
    imports.add("Features");
    blocks.push(
      `<Features title={${js(t.features.title)}} items={${js(t.features.items)}} anchor="features" />`,
    );
  }
  for (const c of catalog) {
    imports.add("DataTable");
    blocks.push(
      `<section aria-label={${js(c.label)}}>\n        <h2>{${js(c.label)}}</h2>\n        <DataTable entity={${js(c.name)}} emptyText="Скоро здесь появятся записи" />\n      </section>`,
    );
  }
  if (t.steps) {
    imports.add("Steps");
    blocks.push(`<Steps title={${js(t.steps.title)}} steps={${js(t.steps.items)}} tone="alt" />`);
  }
  if (t.faq) {
    imports.add("Faq");
    blocks.push(`<Faq title={${js(t.faq.title)}} items={${js(t.faq.items)}} anchor="faq" />`);
  }
  if (lead) {
    imports.add("LeadForm");
    blocks.push(
      `<LeadForm entity={${js(lead)}} title={${js(t.form.title)}}${t.form.intro ? ` intro={${js(t.form.intro)}}` : ""}${t.form.submitLabel ? ` submitLabel={${js(t.form.submitLabel)}}` : ""} />`,
    );
  }
  blocks.push(`<Footer brand={${js(brand)}}${t.footer?.text ? ` text={${js(t.footer.text)}}` : ""} />`);
  return [
    "// Generated by the site template (D75): texts from the card, components bound to the data API.",
    `import { ${[...imports].sort().join(", ")} } from "@wizard/ui-kit";`,
    "",
    "export default function Home() {",
    "  return (",
    "    <>",
    ...blocks.map((b) => `      ${b}`),
    "    </>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function startPage(spec: AppSpec, t: LandingTexts, cabinets: { route: string; label: string }[]): string {
  const first = cabinets[0];
  return [
    "// Generated by the template (D75): the start page of a system without a public role.",
    'import { Hero } from "@wizard/ui-kit";',
    "",
    "export default function Home() {",
    "  return (",
    `    <Hero title={${js(t.hero.title || spec.app.name)}}${t.hero.subtitle ? ` subtitle={${js(t.hero.subtitle)}}` : ""}${first ? ` primary={${js({ label: "Открыть кабинет", href: first.route })}}` : ""} variant="centered" />`,
    "  );",
    "}",
    "",
  ].join("\n");
}

function cabinetPage(spec: AppSpec, role: string, roleLabel: string, entities: string[]): string {
  const parts: string[] = [];
  const sections: string[] = [];
  for (const name of entities) {
    const e = spec.entities.find((x) => x.name === name);
    if (!e) continue;
    const comp = `${pascal(name)}Section`;
    const cols = columns(spec, role, name);
    const st = can(spec, role, name, "update") ? statusField(spec, name) : undefined;
    const ro = new Set(perm(spec, role, name)?.readonlyFields ?? []);
    const actions: string[] = [];
    if (st && !ro.has(st.name))
      for (const opt of st.enum ?? [])
        actions.push(
          `{ id: ${js(`to_${opt.value}`)}, label: ${js(opt.label)}, kind: "update", patch: { ${st.name}: ${js(opt.value)} }, visible: (r: Doc) => r.${st.name} !== ${js(opt.value)} }`,
        );
    if (can(spec, role, name, "delete"))
      actions.push(
        `{ id: "delete", label: "Удалить", tone: "danger", kind: "delete", confirm: "Удалить запись?" }`,
      );
    const canCreate = can(spec, role, name, "create");
    const canEdit = can(spec, role, name, "update");
    parts.push(
      [
        `function ${comp}() {`,
        `  type Doc = ClientDoc<${js(name)}>;`,
        "  const [selected, setSelected] = useState<string | null>(null);",
        '  const [mode, setMode] = useState<"view" | "edit" | "create">("view");',
        "  return (",
        "    <>",
        `      <DataTable entity={${js(name)}} columns={${js([...cols, "created_at"])}} defaultSort={{ field: "created_at", dir: "desc" }} searchable onRowClick={(r: Doc) => { setSelected(r.id); setMode("view"); }} emptyText="Записей пока нет" />`,
        `      {selected && mode === "view" ? (`,
        "        <>",
        `          <RecordCard entity={${js(name)}} id={selected} actions={[${actions.join(", ")}]} onDeleted={() => setSelected(null)} />`,
        canEdit
          ? '          <Button variant="secondary" onClick={() => setMode("edit")}>Изменить</Button>'
          : "",
        '          <Button variant="ghost" onClick={() => setSelected(null)}>Закрыть</Button>',
        "        </>",
        "      ) : null}",
        canEdit
          ? `      {selected && mode === "edit" ? (\n        <RecordForm key={selected} entity={${js(name)}} mode="edit" id={selected} onSuccess={() => setMode("view")} onCancel={() => setMode("view")} />\n      ) : null}`
          : "",
        canCreate
          ? `      {mode === "create" ? (\n        <RecordForm entity={${js(name)}} mode="create" onSuccess={() => setMode("view")} onCancel={() => setMode("view")} />\n      ) : (\n        <Button variant="primary" onClick={() => { setSelected(null); setMode("create"); }}>Добавить</Button>\n      )}`
          : "",
        "    </>",
        "  );",
        "}",
      ]
        .filter((l) => l !== "")
        .join("\n"),
    );
    sections.push(`{ id: ${js(name)}, label: ${js(e.label)}, content: <${comp} /> }`);
  }
  return [
    "// Generated by the template (D75): a cabinet of the role — table, card with status actions, create and edit forms.",
    'import { type ClientDoc, useState } from "@wizard/sdk";',
    'import { Button, CabinetLayout, DataTable, RecordCard, RecordForm } from "@wizard/ui-kit";',
    "",
    "export default function Cabinet() {",
    "  return (",
    `    <CabinetLayout title={${js(`Кабинет: ${roleLabel}`)}} defaultSection={${js(entities[0])}} sections={[${sections.join(", ")}]} />`,
    "  );",
    "}",
    "",
    ...parts.flatMap((p) => [p, ""]),
  ].join("\n");
}
