// Runtime functions of «Запись по слотам» (sources generated from the parameters, sdk.md):
// - busySlots (public query): occupied times of a period for the booking page — start, end and seat only, read through
//   ctx.systemDb because visitors do not read bookings (names and contacts are never returned);
// - scheduleLoad (owner/staff query): the goal-panel metric «Занятость расписания» by the contract of function metrics
//   of «Отчёты и панель цели» ({period: "week" | "month"} → {value, previous}): the share of the working time of every
//   resource and seat held by bookings over the last 7 or 30 days and the same span before it, in percent;
// - clientFromBooking (workflow client_from_booking, with «Клиенты с историей»): a new booking finds or creates its
//   client by the contact and joins the client's history (as clientFromLead of the leads).
import type { ModuleContext } from "../types.js";
import { scheduleOf, scheduleSource } from "./schedule.js";

export const BUSY_SLOTS_FILE = "functions/booking/busySlots.ts";
export const SCHEDULE_LOAD_FILE = "functions/booking/scheduleLoad.ts";
export const CLIENT_FROM_BOOKING_FILE = "functions/booking/clientFromBooking.ts";

const withSpecialists = (ctx: ModuleContext) => ctx.params.with_specialists === true;

export function busySlotsSource(ctx: ModuleContext): string {
  const spec = withSpecialists(ctx);
  return `// Generated by the module «Запись по слотам» (B2-14): occupied times of a period for the booking page.
import { query, v } from "@wizard/sdk";

const DAY = 86_400_000;

export default query({
  args: {
    from: v.datetime(),
    to: v.datetime(),${spec ? `\n    specialist: v.id("specialist"),` : ""}
  },
  handler: async (ctx, args) => {
    const from = Date.parse(args.from);
    const to = Date.parse(args.to);
    if (!(to > from) || to - from > 8 * DAY)
      throw ctx.error("BAD_RANGE", { message: "Период — не больше недели" });
    const rows = await ctx.systemDb.booking.list({
      where: { ${spec ? "specialist: args.specialist, " : ""}starts_at: { gte: args.from, lt: args.to } },
      limit: 1000,
    });
    return rows
      .filter((r) => r.status !== "cancelled" && r.seat !== null)
      .map((r) => ({ starts_at: r.starts_at, ends_at: r.ends_at, seat: r.seat }));
  },
});
`;
}

export function scheduleLoadSource(ctx: ModuleContext): string {
  const spec = withSpecialists(ctx);
  return `// Generated by the module «Запись по слотам» (B2-14): metric «Занятость расписания» for the goal panel.
import { query, v } from "@wizard/sdk";

${scheduleSource(scheduleOf(ctx.params))}
const PERIOD_DAYS = { week: 7, month: 30 } as const;

/** Working slots of one step in [from, to): whole working days whose start falls into the span. */
function workingSlots(from: number, to: number): number {
  let days = 0;
  for (let day = dayKey(from); zonedAt(day, 0) < to; day = addDays(day, 1)) {
    const start = zonedAt(day, SCHEDULE.start);
    if (SCHEDULE.days.includes(weekdayOf(day)) && start >= from && start < to) days += 1;
  }
  return days * slotsPerDay();
}

export default query({
  args: { period: v.enum("week", "month") },
  handler: async (ctx, args) => {
    const now = ctx.now.getTime();
    const len = PERIOD_DAYS[args.period] * 86_400_000;
    ${
      spec
        ? `const resources = Math.max(1, (await ctx.db.specialist.list({ limit: 100 })).filter((s) => s.active !== false).length);`
        : "const resources = 1;"
    }
    const load = async (from: number, to: number): Promise<number | null> => {
      const capacity = workingSlots(from, to) * resources * SCHEDULE.capacity;
      if (capacity === 0) return null;
      const rows = await ctx.db.booking.list({
        where: { starts_at: { gte: new Date(from).toISOString(), lt: new Date(to).toISOString() } },
        limit: 1000,
      });
      let held = 0;
      for (const r of rows) {
        if (r.status === "cancelled" || r.seat === null) continue;
        const length = (Date.parse(r.ends_at) - Date.parse(r.starts_at)) / MINUTE;
        held += Math.max(1, Math.ceil(length / SCHEDULE.step));
      }
      return Math.min(100, Math.round((held / capacity) * 1000) / 10);
    };
    return { value: await load(now - len, now), previous: await load(now - 2 * len, now - len) };
  },
});
`;
}

/**
 * clientFromBooking: finds the client by the contact of match_by (falls back to the other one), creates one when none
 * matches (create=false: the client has required extra fields — only an existing client is linked) and links the
 * booking. Idempotent: a booking that already has a client is left as is.
 */
export const CLIENT_FROM_BOOKING = `// Module «Запись по слотам»: a new booking finds or creates its client by contact and joins the client's history.
import { mutation, v } from "@wizard/sdk";

export default mutation({
  args: { id: v.id("booking"), matchBy: v.enum("phone", "email"), create: v.boolean() },
  handler: async (ctx, args) => {
    const booking = await ctx.db.booking.get(args.id);
    if (!booking) return { client: null };
    if (booking.client) return { client: booking.client };
    const doc = booking as unknown as Record<string, unknown>;
    const text = (key: string): string | null => {
      const value = doc[key];
      return typeof value === "string" && value.trim() !== "" ? value.trim() : null;
    };
    const phone = text("phone");
    const email = text("email")?.toLowerCase() ?? null;
    const order = args.matchBy === "email" ? ["email", "phone"] : ["phone", "email"];
    let client: { id: string } | null = null;
    for (const key of order) {
      if (client) break;
      if (key === "phone" && phone) client = await ctx.db.client.first({ where: { phone } });
      if (key === "email" && email) client = await ctx.db.client.first({ where: { email } });
    }
    if (!client && (!args.create || (!phone && !email))) return { client: null };
    const id = client
      ? client.id
      : await ctx.db.client.insert({ name: text("name") ?? "Без имени", phone, email } as never);
    await ctx.db.booking.patch(args.id, { client: id as never });
    return { client: id };
  },
});
`;
