// Generates packages/pii/data/names.ru.txt and src/names.data.ts (specs/security/data-boundary.yaml#detectors.kinds.person_name).
//
// Provenance: the seed lists below were compiled for this repository from general knowledge of Russian
// anthroponymy (given names in common use in Russia, including Tatar, Bashkir, Caucasian and Central Asian
// names common in RF, standard hypocoristic forms, and frequent surnames that do not end in a regular
// surname suffix). Personal names are facts and not copyrightable; the seed lists and all derived output are
// dedicated to the public domain (CC0-1.0). FU-2 added authored lists of Japanese, Chinese, Korean, Indian, Arabic/Persian,
// Turkish, Latin-American, Dutch/Irish and African given names and surnames (same provenance and license). FU-1 added authored lists of Central Asian, Caucasian, Turkic and Siberian
// names and surnames and of common English/European first names and surnames (same provenance and license). Derived entries are generated by heuristics in this script:
// "-ка/-енька/-юша" diminutives and Latin transliterations (BGN/PCGN-like, passport ICAO-like and common
// English spellings). Case forms are NOT stored — they are generated at load time by src/dict.ts.
//
// Run: node packages/pii/scripts/gen-names.ts   (Node 22 strips types natively; no imports from src/ on purpose)

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// ---------------------------------------------------------------- seeds (full names)

const MALE = `
Август Авдей Аким Александр Алексей Альберт Алан Амвросий Анатолий Андрей Андриан Антон Аристарх Аркадий Арнольд Арсений
Артём Артемий Артур Архип Афанасий Богдан Болеслав Борис Бронислав Вадим Валентин Валерий Валериан Василий Вацлав Велимир
Вениамин Венедикт Викентий Виктор Виссарион Виталий Влад Владилен Владимир Владислав Владлен Власий Всеволод Всеслав
Вячеслав Гавриил Гаврила Геннадий Георгий Герасим Герман Глеб Гордей Григорий Гурий Давид Даниил Данила Данислав Дементий
Демид Демьян Денис Дмитрий Добрыня Донат Евгений Евграф Евдоким Евстафий Егор Елисей Емельян Еремей Ерофей Ефим Ефрем Ждан
Захар Зиновий Иван Игнат Игнатий Игорь Илларион Иларион Илья Иннокентий Иосиф Ираклий Исаак Исай Капитон Карен Карл Касьян
Ким Кирилл Клим Климент Кондрат Кондратий Константин Корней Кузьма Лаврентий Лавр Лазарь Лев Леон Леонид Леонтий Леопольд
Лука Лукьян Любим Любомир Май Макар Макарий Максим Максимилиан Мартын Марк Матвей Мефодий Милан Мир Мирон Мирослав Митрофан
Михаил Модест Моисей Мстислав Назар Назарий Натан Наум Нестор Никанор Никита Никифор Никодим Николай Никон Нил Олег Олесь
Онисим Орест Осип Остап Павел Панкрат Пантелей Пантелеймон Парфён Пётр Пимен Платон Порфирий Потап Прокопий Прохор
Радомир Радислав Рафаил Родион Роберт Роман Ростислав Рудольф Руслан Савва Савелий Самсон Самуил Святослав Святополк
Севастьян Семён Серафим Сергей Спартак Спиридон Станислав Станимир Степан Тарас Тимофей Тимур Тит Тихомир Тихон Трифон
Трофим Ульян Устин Фадей Фёдор Федот Феликс Феофан Филимон Филипп Фома Фрол Харитон Христиан Эдуард Эмиль Эммануил Эрик
Юлиан Юлий Юрий Юстин Яков Ян Ярополк Ярослав Яромир
Абдулла Азамат Азат Айдар Айрат Алишер Алмаз Амир Анвар Арман Арсен Аслан Ахмед Ахмад Ашот Бахтияр Булат Вазген Гамлет
Гарик Гурам Дамир Данияр Джамал Джамиль Динар Заур Зураб Ибрагим Ильгиз Ильдар Ильнур Ильшат Ильяс Ирек Ислам Исмаил
Казбек Камиль Карим Ленар Магомед Мансур Марат Марсель Мераб Мурат Мухаммед Мухаммад Наиль Нодар Нурлан Отар Раиль Раис
Рамзан Рамиль Рафаэль Рафис Рашид Равиль Радик Ренат Ринат Ришат Рифат Рубен Рустам Рустем Саид Салават Самир Сослан
Султан Тагир Тамерлан Тигран Фанис Фаниль Фарид Хасан Шамиль Шота Эльдар Эльман Юсуф Якуб Артак Вагиф Гейдар Мамед
`;

const FEMALE = `
Аврора Агата Агафья Агния Аграфена Ада Аделина Аксинья Алевтина Александра Алёна Алеся Алина Алиса Алла Альбина Амалия
Анастасия Ангелина Анжела Анжелика Анисья Анна Антонина Анфиса Ариадна Ариана Арина Богдана Валентина Валерия Ванда Варвара
Василина Василиса Венера Вера Вероника Весна Виктория Вилена Виолетта Вита Виталина Виталия Влада Владислава Галина Глафира
Грета Дана Дарина Дарья Диана Дина Доминика Ева Евгения Евдокия Евфросиния Ефросинья Екатерина Елена Елизавета Есения Жанна
Зарина Зинаида Злата Зоряна Зоя Иветта Изабелла Изольда Илона Инга Инесса Инна Ираида Ирина Ирма Капитолина Камила Камилла
Карина Каролина Кира Клавдия Клара Кристина Ксения Лада Лариса Лаура Лейла Леся Лиана Лидия Лилиана Лилия Лина Лолита
Любава Любовь Людмила Майя Маргарита Марианна Марина Мария Марта Марьяна Мелания Мила Милана Милена Милослава Мирослава
Мирра Муза Надежда Наталья Наталия Нелли Ника Нина Нинель Нонна Оксана Олеся Олимпиада Ольга Пелагея Полина Прасковья Рада
Радмила Раиса Регина Рената Римма Роза Розалия Руслана Сабина Сабрина Светлана Серафима Снежана София Софья Станислава
Стелла Стефания Сусанна Таисия Тамара Татьяна Тереза Ульяна Устинья Фаина Феврония Фёкла Эвелина Эдита Элеонора Элина
Эльвира Эльза Эмилия Эмма Эрика Юлиана Юлия Юна Ядвига Яна Ярослава Ясмина
Айгуль Айсылу Алсу Альфия Асель Гузель Гульнара Гульнур Джамиля Диляра Динара Жасмин Зарема Земфира Зульфия Ильмира Ильнара
Камилла Лейсан Ляйсан Луиза Мадина Малика Марьям Наиля Наргиз Патимат Резеда Сания Тамила Фатима Хадижат Эльмира Айлин
`;

// Hypocoristic forms (authored). Gender u = both.
const DIMINUTIVE_M = `
Саша Шура Саня Санёк Лёша Алёша Лёха Толя Толик Андрюша Андрюха Антоша Тоша Аркаша Арсюша Сеня Тёма Боря Вадик Валера Вася
Вова Володя Витя Виталик Владик Славик Гена Гоша Жора Гера Гриша Даня Дениска Дима Димон Митя Егорка Жека Захарка Ваня Ванюша
Игорёк Илюша Илюха Кеша Кирюша Киря Костя Лёня Лёва Макс Максик Миша Мишаня Коля Коленька Никитка Олежка Паша Павлик Петя
Рома Ромка Родя Серёжа Стас Стасик Стёпа Тима Тимоша Федя Эдик Юра Юрочка Яша Ярик Сёма Матвейка Платоша Тиша Тимка Фима
Эрик Тёмка Славка Прохорка Гордейка Богдаша Данилка Вовчик Юрик Женёк Толян Колян Вован Димыч Серёга Лёнчик
`;

const DIMINUTIVE_F = `
Настя Настенька Ася Аня Анюта Анечка Нюра Нюша Аля Алёнка Варя Вика Галя Даша Дашенька Катя Катюша Лена Леночка Лиза Лизонька
Ира Ирочка Иришка Ксюша Лара Лида Лиля Люда Люся Маша Машенька Маруся Мариша Мариночка Надя Наденька Наташа Ната Ниночка
Оля Оленька Олечка Поля Рая Рита Светочка Соня Сонечка Софа Тася Тома Таня Танечка Танюша Уля Юля Юленька Янка Зина Тоня
Клава Фая Эля Верочка Геля Гуля Ксеня Лёля Марго Маня Надюша Оксанка Полинка Сима Стеша Стефа Ульянка Лиса Ксюха Катенька
Галочка Валечка Любаша Настюша Дашуля Машуля Ариша Алинка Кристи Викуля Вероничка Златочка Милочка Сонька Людочка
`;

const DIMINUTIVE_U = "Женя Валя Слава Шура Саша";
const DIMINUTIVE_AMBIGUOUS = "Света Люба";

// Words that are also common nouns, months or place names: detected only together with a surname/patronymic.
const AMBIGUOUS = new Set(
  `Вера Надежда Любовь Роман Лев Мир Слава Май Роза Лилия Виктория Лада Ника Мила Злата Алиса Август Ян Эра Лиана Дана Вита
   Мира Любим Милан Марсель Лавр Никон Ислам Христиан Султан Лука Муза Аврора Олимпиада Весна Венера Жасмин Ким Света Люба
   Рада Мирра Марк Нил Гарик Спартак Донат Ада Марта Юна Стелла Лиса Поля Тома Рая Софа Булат Алмаз Динар Салават Казбек
   Гамлет Тёма Тёмка`
    .split(/\s+/)
    .filter(Boolean),
);

// Generated "-ка" diminutives that coincide with common nouns.
const GENERATED_BLOCKLIST = new Set(
  "Галка Милка Кирка Серёжка Славка Лиска Зорька Ладка Верка Любка Лёвка Витька Ромашка Ленка Ванька Тонька Настька".split(
    " ",
  ),
);

const DIMINUTIVE_BASES = `Саша Маша Даша Паша Таня Катя Оля Коля Юля Лена Света Наташа Женя Лёша Петя Вася Ваня Дима Вова Витя Миша
Настя Ира Надя Галя Валя Люба Аня Соня Лиза Рома Юра Серёжа Гриша Костя Толя Митя Лёня Федя Стёпа Тоня Зина Вера Рая Люда
Варя Поля Ксюша Алёна Вика Рита Слава Тома Уля Гена Боря Лида Аля Ася Сеня Даня Кира`;

// Frequent Russian surnames (masculine form; feminine and case forms are covered by the suffix rules in
// src/detectors/names.ts#SURNAME_SUFFIX_CYR).
const SURNAMES_COMMON = `
Иванов Смирнов Кузнецов Попов Васильев Петров Соколов Михайлов Новиков Фёдоров Морозов Волков Алексеев Лебедев Семёнов
Егоров Павлов Козлов Степанов Николаев Орлов Андреев Макаров Никитин Захаров Зайцев Соловьёв Борисов Яковлев Григорьев
Романов Воробьёв Сергеев Кузьмин Фролов Александров Дмитриев Королёв Гусев Киселёв Ильин Максимов Поляков Сорокин
Виноградов Ковалёв Белов Медведев Антонов Тарасов Жуков Баранов Филиппов Комаров Давыдов Беляев Герасимов Богданов Осипов
Сидоров Матвеев Титов Марков Миронов Крылов Куликов Карпов Власов Мельников Денисов Гаврилов Тихонов Казаков Афанасьев
Данилов Савельев Тимофеев Фомин Чернов Абрамов Мартынов Ефимов Федотов Щербаков Назаров Калинин Исаев Чернышёв Быков
Маслов Родионов Коновалов Лазарев Воронин Климов Филатов Пономарёв Голубев Кудрявцев Прохоров Наумов Потапов Журавлёв
Овчинников Трофимов Леонов Соболев Ермаков Колесников Гончаров Емельянов Никифоров Грачёв Котов Гришин Ефремов Архипов
Громов Кириллов Малышев Панов Моисеев Румянцев Акимов Кондратьев Бирюков Горбунов Анисимов Ерёмин Тихомиров Галкин
Лукьянов Михеев Скворцов Юдин Белоусов Нестеров Симонов Прокофьев Харитонов Князев Цветков Левин Митрофанов Воронов
Аксёнов Софронов Мальцев Логинов Горшков Савин Краснов Майоров Демидов Елисеев Рыбаков Сафонов Плотников Дёмин Хохлов
Фадеев Молчанов Игнатов Литвинов Ершов Ушаков Дементьев Рябов Мухин Калашников Леонтьев Лобанов Кузин Корнилов
Евдокимов Бородин Платонов Некрасов Балашов Бобров Жданов Блинов Игнатьев Коротков Муравьёв Крюков Беляков Богомолов
Дроздов Лавров Зуев Петухов Ларин Никулин Серов Терентьев Зотов Устинов Фокин Самойлов Константинов Сахаров Шишкин
Самсонов Черкасов Чистяков Носов Спиридонов Карасёв Авдеев Воронцов Зверев Владимиров Селезнёв Нечаев Кудряшов Седов
Фирсов Андрианов Панин Головин Терехов Ульянов Шестаков Агеев Никонов Селиванов Баженов Гордеев Кожевников Пахомов
Зимин Костин Широков Филимонов Ларионов Овсянников Сазонов Суворов Нефёдов Любимов Львов Горбачёв Копылов Лукин
Токарев Кулешов Шилов Большаков Панкратов Родин Шаповалов Покровский Бочаров Никольский Маркин Горелов Агафонов Березин
Ермолаев Зубков Куприянов Трифонов Масленников Круглов Третьяков Колосов Рожков Артамонов Шмелёв Лаптев Лапшин Федосеев
Зиновьев Зорин Уткин Столяров Зубов Ткачёв Дорофеев Антипов Завьялов Свиридов Золотарёв Кулаков Мещеряков Макеев
Дьяконов Гуляев Петровский Бондарев Поздняков Панфилов Кочетков Суханов Рыжов Старостин Калмыков Колесов Золотов
Кравцов Субботин Шубин Щукин Лосев Винокуров Лапин Парфёнов Исаков Голованов Коровин Розанов Артёмов Козырев Русаков
Алёшин Крючков Булгаков Кошелев Сычёв Синицын Олейников Кононов Евсеев Калугин Комиссаров Кирсанов Обухов Сапожников
Хабибуллин Галиев Сафин Гарипов Шарипов Валиев Мухаметшин Ахметов Нуриев Зарипов Юсупов Алиев Мамедов Гасанов Магомедов
Абдуллаев Рахимов Каримов Исмаилов Назарбаев Саргсян Петросян Акопян Григорян Оганесян Геворгян Гелашвили Беридзе
Шевченко Бондаренко Коваленко Кравченко Ткаченко Олейник Мельниченко Савченко Руденко Лысенко Марченко Шевчук Коваль
Мельник Бойко Кравчук Полищук Ковальчук Романюк Лукашенко Ковалевский Жуковский Вишневский Новицкий Янковский
`;

// Surnames that do not end in a regular Russian surname suffix (see src/detectors/names.ts#SURNAME_SUFFIX_CYR).
const SURNAMES = `
Ким Цой Пак Ли Хан Тен Шин Югай Огай Когай Нам Мун Чен Толстой Толстая Донской Трубецкой Лановой Коваль Мельник Бондарь Гончар Кравец Швец Ткач Жук Лях
Мороз Бойко Сирота Гоголь Шмидт Миллер Фишер Вебер Шульц Беккер Рихтер Вагнер Гофман Кох Кац Коган Фельдман Розенберг
Гольдман Лифшиц Шапиро Гинзбург Цукерман Эпштейн Кузнец Бородай Литвак Гладкий Грач Сокол Волк Заяц Лысый Чёрный Белый
Рыбак Соловей Шевчик Мазур Бандера Тимошенко Гриценко Олейник Кушнир Павлюк Савчук Марченко Руденко Сорока Демченко
Карпенко Клименко Вакуленко Федоренко Шевченко Ковальчук Мельниченко Ющенко Лебедь Гуревич Кнут Бах Гейнц Клюев
`;

// Common Latin spellings that the transliteration heuristics do not produce.
const LATIN_EXTRA = `
Alexander Alexandra Alex Alexei Alexey Aleksei Sergei Sergey Dmitri Dmitry Dmitriy Nikolai Nikolay Maxim Maksim Pyotr Petr
Fedor Fyodor Semyon Semen Artem Artyom Alyona Alena Ksenia Kseniya Xenia Sofia Sofya Sophia Daria Darya Anastasia Ilia
Ilya Vitaly Vitaliy Valery Valeriy Yuri Yury Yuriy Iurii Evgeny Evgeniy Yevgeny Eugene Evgenia Evgeniya Yevgeniya Ekaterina
Yekaterina Katerina Elena Yelena Helen Elizaveta Yelizaveta Julia Yulia Yuliya Iuliia Natalia Natalya Nataliya Tatiana
Tatyana Tatjana Ludmila Lyudmila Liudmila Larisa Larissa Viktoriya Victoria Veronica Kristina Christina Mariya Maria Marija
Olga Oksana Svetlana Irina Nadezhda Galina Valentina Tamara Zoya Lidia Lidiya Raisa Polina Alina Diana Vera Lyubov Nina Inna
Alla Anna Aleksandr Aleksandra Aleksey Mikhail Michail Andrei Andrey Anton Artur Boris Vadim Viktor Victor Vladimir
Vladislav Vyacheslav Gennady Gennadiy Georgy Georgiy Grigory Grigoriy Denis Egor Yegor Igor Ivan Kirill Konstantin Leonid
Mark Nikita Oleg Pavel Roman Ruslan Stanislav Stepan Timur Timofey Fedor Yaroslav Yakov Anatoly Anatoliy Arkady Arkadiy
Arseny Arseniy Bogdan Daniil Danila Gleb Lev Matvey Makar Platon Savva Semyon Taras Tikhon Zakhar Sasha Masha Dasha Pasha
Katya Misha Dima Vova Kolya Tanya Olya Natasha Lena Sveta Yulya Zhenya Nastya Kostya Seryozha Serezha Lyosha Lesha Vanya
Petya Vasya Ira Nadya Galya Valya Lyuba Anya Sonya Liza Roma Yura Grisha Tolya Mitya Fedya Styopa Tonya Zina Vika Rita Slava
`;

// FU-1: Central Asian, Caucasian, Turkic, Finno-Ugric/Siberian given names common in RF (flag "o").
const OTHER_MALE = `
Абдулазиз Абдурахмон Азиз Акбар Акмаль Алимардон Анвар Аскар Ахрор Бахром Бахтиёр Баходир Бекзод Бобур Бунёд Давлат
Далер Джамшед Джамшид Джахонгир Дилшод Достон Жасур Зафар Икром Исмоил Камол Комил Лазиз Мансур Мурод Мухаммаджон Нодир
Носир Одил Отабек Парвиз Равшан Рахим Сардор Сорбон Сухроб Темур Улугбек Умид Фаррух Фарход Фирдавс Фируз Хуршид Хусрав
Шавкат Шахзод Шахриёр Шерзод Шухрат Элёр Эркин Ойбек Манучехр Исфандиёр Абдулло Бахтовар Мехрож Рустамжон Сайфулло
Айбек Айдос Асхат Бауыржан Галым Данияр Ерлан Ержан Ербол Жандос Кайрат Мирас Нурлан Нурсултан Олжас Серик Талгат
Бакыт Бекболот Жыргалбек Нурбек Эрлан Алмат Бейбит Габит Дастан Ельдос Женис Мади Нуржан Руслан Самат Тимур Азамат
Алихан Хусейн Умар Усман Юнус Идрис Алибек Муса Иса Салман Сулейман Джабраил Мовсар Лема Зелимхан Хамзат Висхан Турпал
Аюб Байсангур Мурад Абдул Гасан Хабиб Забит Омар Рамазан Курбан Магомедали Гаджимурад Абакар Арсланбек Нурмагомед
Батраз Хетаг Таймураз Сармат Алан Сослан Эльбрус
Арам Гагик Гурген Левон Нарек Самвел Саркис Ваган Ваграм Геворг Айк Мгер Норайр Овик Оганес Размик Сурен Эдгар Вардан
Грачья Арутюн Акоп Мкртич Хачик Ашот Тигран Артак Вазген Карен Армен Арсен Гарегин Мануэл Грант
Гиви Гоги Звиад Леван Реваз Тамаз Теймураз Шалва Гела Бадри Важа Вахтанг Автандил Давит Зураб Мераб Нодар Отар Гурам
Коба Бесик Бидзина
Эльчин Рашад Фуад Ильхам Вугар Эмин Рауф Намик Ровшан Самед Тофик Гусейн Алекпер Эльнур Эльшад Акиф Аяз Бахрам Джейхун
Орхан Октай Рамиз Сабир Тельман Шахин Эмиль Фархад Ильгар Натиг Турал Эльвин Анар Камран Мехман Алескер
Габдулла Газинур Ильназ Ильфат Ильнар Искандер Минтимер Нияз Ранис Фарит Халиль Ильгам Нафис Рифкат Зуфар Рушан
Ильдус Рамис Айдар Айрат Азат Ильгиз Ильдар Ильнур Ильшат Ирек Ленар Марат Наиль Раиль Рамиль Ришат Рустем Тагир
Фанис Фаниль Динар Булат Салават Азамат Альфред Ринат Рафис Радик Раис Рифат Ильяс Алмаз
Айаал Айсен Эрхан Тускун Кэскил Нюргун Мичил Дьулус Айтал Арчын Дохсун Ньургун Эрчим Дьулустан
Баир Баяр Жаргал Солбон Тумэн Цырен Санжар Доржи Очир Бадма Чингис Аржаан Шолбан Айдыс Буянто Дамдин Мерген
`;

const OTHER_FEMALE = `
Гулноза Дилноза Дилором Зулайхо Камола Лобар Лола Мохинур Нигора Нилуфар Нодира Сабохат Севара Феруза Шахло Шахноза
Мунира Мехрибон Гулчехра Зебо Мавлюда Дильфуза Хилола Умида Гульнора Замира Муниса Мадина Малика Зарина
Айгерим Айжан Айдана Айнура Акмарал Асель Гульмира Дамира Динара Жанар Жулдыз Индира Камила Меруерт Сауле Толкын
Томирис Балжан Салтанат Айсулу Нургуль Бермет Чолпон Жибек Асем Айым Гаухар Дана Жансая Карлыгаш Мадина Мольдир
Аминат Асият Зайнаб Хава Седа Хеда Муслимат Сакинат Айшат Зарема Патимат Хадижат Марьям Луиза Милана Петимат Залина
Агунда Дзерасса Мадина Фатима
Анаит Гаяне Лилит Нунэ Сирануш Шушан Асмик Карине Мариам Нарине Татевик Ануш Армине Эрмине Астхик Сона Ани
Тамрико Манана Кетеван Нана Натела Тинатин Лали Мзия Нателла Нино Кето Маиа Ламара Софико Марика
Айдан Айнур Гюнай Гюльнара Наргиз Севиндж Севда Тарана Ульвия Фидан Хаяла Чинара Эсмира Нигяр Кёнуль Аида Лейла
Сабина Самира Туркан Ламия Нармин Джамиля
Азалия Гульназ Гульшат Зиля Ильсия Миляуша Рузиля Чулпан Энже Гульфия Раушания Фания Фирдаус Флюра Алия Аделя
Гульчачак Рамиля Лейсан Ляйсан Резеда Айгуль Айсылу Алсу Альфия Гузель Гульнара Гульнур Диляра Ильмира Ильнара Сания
Зульфия Эльмира Наиля Лилиана Гульсина Зайтуна Ильзира Лиана
Сахаайа Туйаара Айыына Сардаана Нарыйа Кюннэй Мичийэ Уйгулаана Дайаана Саина Сайаара Ньургуйаана Туяра Айталина
Номин Сэсэг Туяна Эржена Янжима Баира Арюна Дарима Сарюна Долгор Аяна Айлана Чечена Урана Намжилма Цыпилма
`;

// Words or places among the FU-1 names (need a surname/patronymic).
const OTHER_AMBIGUOUS = new Set(
  `Ахмат Беслан Улан Дархан Алма Ландыш Грант Буян Хасан Эмир Мирза Али Аида Канат Батыр Назгуль Рамазан Курбан Саян
   Физули Эльбрус Сармат Анар Дастан Мерген Сона Ани Лола Дана Динар Булат Салават Алмаз Коба Самат Габит`
    .split(/\s+/)
    .filter(Boolean),
);

// FU-1: non-Slavic surnames common in RF (flag "o"); feminine -ова/-ева/-ина forms are generated by src/dict.ts.
const OTHER_SURNAMES = `
Юлдашев Турсунов Эргашев Султанов Рахмонов Каримов Усмонов Холматов Абдуллаев Мирзаев Хакимов Шарипов Исмоилов
Кадыров Умаров Азимов Аминов Бобоев Давлатов Джураев Икромов Камолов Мамадалиев Норматов Одилов Пулатов Рахматуллаев
Сафаров Тошматов Файзуллаев Хасанов Холиков Шукуров Эшонов Юнусов Якубов Ахмедов Бакиров Рахимов Рахмон Шарипзода
Давлатзода Саидзода Каримзода Раджабов Назарзода Рахимзода Мирзоев Исмаилзода Турсунзода Собиров Мухаммадиев
Назарбаев Токаев Жумабаев Бекмамбетов Сулейменов Кенжебаев Абенов Байтурсынов Есимов Жаксыбеков Искаков Кайратов
Оспанов Сагинтаев Тасмагамбетов Утемисов Нургалиев Байжанов Сарсенбаев Тулегенов Ермеков Атамбаев Жапаров Акаев
Бакиев Ташиев Мамытов Садыров Абдылдаев Токтогулов
Галиев Сафин Гарипов Валиев Мухаметшин Зарипов Нуриев Ахмадуллин Батыршин Габдрахманов Гайнуллин Ганиев Гильманов
Закиров Зиннатуллин Ибрагимов Идрисов Имамов Исхаков Камалов Латыпов Минниханов Мингазов Миннуллин Муратов Набиуллин
Нигматуллин Низамов Рахматуллин Сабиров Садыков Сайфуллин Сафиуллин Султангалиев Тагиров Файзуллин Фаттахов
Хайруллин Хамитов Шайхутдинов Шакиров Юсупов Ямалетдинов Гумеров Хуснуллин Хабибуллин Шаймиев Гатауллин Мустафин
Дудаев Масхадов Алханов Джабраилов Хаджиев Магомедов Гаджиев Абдулаев Гамзатов Нурмагомедов Омаров Рамазанов Халилов
Шамилов Хабибов Дзагоев Газзаев Кокоев Тедеев Цаллагов Хетагуров Бесаев Габараев Кабисов Кочиев Мамсуров Евлоев
Мальсагов Ахмадов Байсаров Делимханов Хизриев Даудов Шахбанов Алибеков Курбанов Мусаев Эльдаров
Алиев Мамедов Гасанов Гусейнов Керимов Исмаилов Рзаев Кулиев Мехтиев Агаев Бабаев Велиев Джафаров Зейналов
Искендеров Насибов Оруджев Рустамов Талыбов Фарзалиев Халафов Эфендиев Юсифов Аббасов Ахундов Гулиев Гаджиев
Мамедли Гасанли Керимли Ахмедли Гусейнли Алили Султанли Исмаилли Рагимли Аббаслы Джафарли Шахбазлы Гулузаде
Рзазаде Ализаде Гусейнзаде Мамедзаде Кулизаде Мирзазаде Гаджизаде
Саргсян Петросян Акопян Григорян Оганесян Геворгян Арутюнян Аветисян Айвазян Бабаян Варданян Габриелян Галстян
Гаспарян Давтян Даниелян Егиазарян Закарян Карапетян Киракосян Манукян Маргарян Мартиросян Мелконян Минасян
Мкртчян Мовсисян Нерсисян Овсепян Погосян Саакян Сафарян Симонян Степанян Товмасян Хачатрян Шахназарян Агаджанян
Карапетянц Бабаянц Шахназарянц Аванесянц Галустянц Арзуманянц Меликянц Мирзоянц Тер-Петросян Тер-Оганян
Абашидзе Гогоберидзе Джапаридзе Кикнадзе Кобахидзе Лордкипанидзе Нижарадзе Орджоникидзе Табидзе Чхеидзе Шеварднадзе
Эбаноидзе Бахтадзе Мчедлидзе Капанадзе Нозадзе Табатадзе Чавчавадзе Джанелидзе Какабадзе Натадзе Сванидзе Тевзадзе
Цулукидзе Шарашидзе Беридзе Хуцишвили Бараташвили Гаприндашвили Джугашвили Маргвелашвили Саакашвили Ревишвили
Мерабишвили Гогичайшвили Квирикашвили Мамардашвили Мгалоблишвили Гелашвили Церетели Кипиани Иоселиани Мачавариани
Шенгелия Гамсахурдия Данелия Гогия Пирцхалава Элиава Бекаури
Аммосов Эверстов Ойунский Кулаковский Николаев Слепцов Томский Бадмаев Цыденов Дамдинов Доржиев Намжилов Батуев
Будаев Цыбиков Жамсуев Ондар Монгуш Куулар Сат Оюн Хомушку
`;

// FU-1: common English/European given names (flag "w"; Latin, need a neighbour like every Latin name).
const WESTERN_FIRST = `
James John Robert Michael William David Richard Joseph Thomas Charles Christopher Daniel Matthew Anthony Donald Steven
Paul Andrew Joshua Kenneth Kevin Brian George Timothy Ronald Edward Jason Jeffrey Ryan Jacob Gary Nicholas Eric
Jonathan Stephen Larry Justin Scott Brandon Benjamin Samuel Gregory Alexander Patrick Dennis Jerry Tyler Aaron Henry
Douglas Peter Adam Nathan Zachary Walter Kyle Harold Carl Jeremy Keith Roger Gerald Ethan Arthur Terry Christian Sean
Lawrence Austin Joe Noah Jesse Albert Bryan Billy Bruce Willie Jordan Dylan Alan Ralph Gabriel Roy Juan Wayne Eugene
Logan Randy Louis Russell Vincent Philip Bobby Johnny Bradley Oliver Harry Jack Charlie Oscar Leo Liam Lucas Mason
Elijah Owen Luke Isaac Caleb Connor Evan Ian Julian Adrian Colin Neil Simon Graham Stuart Nigel Trevor Craig Derek
Gordon Howard Leonard Marcus Nathaniel Victor Tom Tim Sam Ben Dan Mike Bob Steve Dave Chris Matt Tony Nick Josh Andy
Jim Jimmy Rick Ted Fred Hans Klaus Stefan Pierre Jacques Philippe Francois Antoine Marco Giovanni Giuseppe Luca
Matteo Alessandro Lorenzo Carlos Jose Miguel Pablo Diego Javier Luis Antonio Manuel Pedro Fernando Rafael Sergio Jorge
Andres Alejandro Francisco Hugo Lars Sven Nils Anders Johan Piotr Tomasz Krzysztof Wojciech Jan Mateusz Friedrich
Wolfgang Heinrich Dieter Jurgen Uwe Matthias Florian Tobias Sebastian Maximilian Jonas Felix Lukas Leon Elias
Mary Patricia Jennifer Linda Elizabeth Barbara Susan Jessica Sarah Karen Nancy Lisa Betty Margaret Sandra Ashley
Kimberly Emily Donna Michelle Dorothy Carol Amanda Melissa Deborah Stephanie Rebecca Sharon Laura Cynthia Kathleen Amy
Shirley Angela Helen Anna Brenda Pamela Nicole Emma Samantha Katherine Christine Debra Rachel Catherine Carolyn Janet
Ruth Maria Heather Diane Virginia Julie Joyce Victoria Olivia Kelly Christina Lauren Joan Evelyn Judith Megan Cheryl
Andrea Hannah Martha Jacqueline Frances Gloria Ann Teresa Kathryn Sara Janice Jean Alice Madison Doris Abigail Julia
Judy Grace Denise Amber Marilyn Beverly Danielle Theresa Sophia Marie Diana Brittany Natalie Isabella Charlotte Rose
Alexis Kayla Chloe Ava Mia Harper Zoe Lily Ella Scarlett Aria Layla Nora Hazel Ellie Stella Lucy Claire Sophie Jane
Kate Molly Holly Jessie Paula Monica Wendy Tiffany Tracy Vanessa Veronica Yvonne Sylvia Irene Clara Ingrid Astrid
Greta Heidi Monika Petra Sabine Ursula Birgit Camille Juliette Chantal Giulia Francesca Chiara Valentina Sofia Lucia
Isabel Carmen Elena Marta Ines Agnieszka Katarzyna Magdalena Ewa Joanna Malgorzata Anneliese Brigitte Claudia Susanne
`;

// FU-1: common English/European surnames (flag "w").
const WESTERN_SURNAMES = `
Smith Johnson Williams Brown Jones Garcia Miller Davis Rodriguez Martinez Hernandez Lopez Gonzalez Wilson Anderson Thomas
Taylor Moore Jackson Lee Perez Thompson White Harris Sanchez Clark Ramirez Lewis Robinson Walker Young Allen Wright
Scott King Torres Nguyen Hill Flores Green Adams Nelson Baker Hall Rivera Campbell Mitchell Carter Roberts Gomez
Phillips Evans Turner Diaz Parker Cruz Edwards Collins Reyes Stewart Morris Morales Murphy Cook Rogers Gutierrez Ortiz
Cooper Peterson Bailey Reed Kelly Howard Ramos Cox Ward Richardson Watson Brooks Chavez Wood James Bennett Gray Mendoza
Ruiz Hughes Price Alvarez Castillo Sanders Patel Myers Long Ross Foster Jimenez Powell Jenkins Perry Russell Sullivan
Bell Coleman Butler Henderson Barnes Gonzales Fisher Vasquez Simmons Romero Jordan Patterson Hamilton Graham Reynolds
Griffin Wallace Moreno West Cole Hayes Bryant Herrera Gibson Ellis Tran Medina Aguilar Stevens Murray Ford Castro
Marshall Owens Harrison Fernandez Mcdonald Woods Washington Kennedy Wells Vargas Chen Freeman Webb Tucker Guzman Burns
Crawford Olson Simpson Porter Hunter Gordon Mendez Silva Shaw Snyder Mason Dixon Munoz Hunt Hicks Holmes Palmer Wagner
Black Robertson Boyd Rose Stone Salazar Fox Warren Mills Meyer Rice Schmidt Garza Daniels Ferguson Nichols Stephens
Soto Weaver Ryan Gardner Payne Grant Dunn Kelley Spencer Hawkins Arnold Pierce Hansen Peters Santos Hart Bradley Knight
Elliott Cunningham Duncan Armstrong Hudson Carroll Lane Riley Andrews Johnston Berry Perkins Hoffman Lawrence Carlson
Williamson Harper Fuller Newman Walsh Lynch Barker Burke Dawson Fletcher Lambert Mccarthy Kowalski Nowak Wisniewski
Mueller Muller Schneider Fischer Weber Becker Hoffmann Schulz Koch Richter Klein Wolf Schroeder Neumann Braun
Zimmermann Hartmann Dubois Durand Lefebvre Moreau Laurent Michel Leroy Roux Fournier Girard Bonnet Dupont Rossi Russo
Ferrari Esposito Bianchi Romano Colombo Ricci Marino Greco Bruno Gallo Conti Costa Giordano Mancini Rizzo Lombardi
Moretti Jansen Visser Bakker Andersson Johansson Karlsson Nilsson Eriksson Larsson Olsson Nielsen Jensen Pedersen
Kowalczyk Novak Horvath Doe
`;

// FU-2: given names beyond English/European (flag "g"; Latin, ASCII — lookups strip diacritics): Japanese, Chinese
// pinyin, Korean, Indian, Arabic/Persian, Turkish, Latin-American, Dutch/Irish/Nordic.
const GLOBAL_FIRST = `
Hiroshi Takeshi Kenji Haruto Sota Yuto Kaito Riku Hinata Yui Aoi Akira Satoshi Kazuki Daiki Shota Takumi Ryota Naoki
Tomoko Yoko Keiko Naomi Emi Ayumi Haruka Misaki Nanami Kaori Megumi Yumi Mariko Hiroko Akiko Kenta Shun Yusuke Kohei
Masato Hideo Kazuo Makoto Tetsuya Takashi Koji Shinji Ichiro Jiro Taro Hayato Minato Itsuki Tsubasa Ryo Yuna Rin Mio
Airi Hana Kenichi Shinichi Noriko Sachiko Kumiko Junko Masako Reiko Chika Yuki Sakura Hiroki Kazuya Tatsuya Yoshiko
Hitomi Asuka Rei Sayaka Yuko Etsuko Fumiko Hideki Isamu Katsuro Masaru Nobuo Osamu Susumu Toshiro Yasuo Yoshiro
Wei Fang Lei Jun Ming Hui Yan Jing Na Min Jie Tao Hao Xin Qiang Ping Gang Chao Feng Hua Kai Mei Ning Qing Rui Ting
Ying Yun Zhen Xiaoming Xiaohong Jianguo Zhiwei Weiwei Haoran Yichen Zihan Yuxuan Zixuan Xinyi Yutong Jiahao Junjie
Tianyu Chenxi Mingyu Jiayi Shuang Lihua Guoqiang Jianhua Xiaoli Xiaoyan Yanling Meiling Liying Huiling Zhihao Yifan
Ruoxi Siyu Kaiwen Wenjie Wenbo Haoyu Boyang Xiaowei Jiawei Zhiqiang Yongmei Qiuyue Shufen Guiying Xiuying Guilan
Minjun Seoyeon Jihoon Jiwoo Haeun Doyoon Seojun Yejin Soojin Hyejin Minji Jihye Eunji Jaehyun Sungmin Donghyun
Hyunwoo Youngho Sanghoon Joonho Minseo Jiyeon Jaewon Yoojin Seunghoon Kyungsoo Junseo Hyewon Daeun Jisoo Taeyang
Min-jun Seo-yeon Ji-hoon Ji-woo Ha-eun Do-yoon Seo-jun Ye-jin Soo-jin Hye-jin Min-ji Ji-hye Eun-ji Jae-hyun Sung-min
Dong-hyun Hyun-woo Young-ho Sang-hoon Joon-ho Min-seo Ji-yeon Jae-won Yoo-jin Seung-hoon Kyung-soo Jun-seo Hye-won
Rahul Amit Rajesh Suresh Ramesh Vijay Anil Sunil Sanjay Arjun Aarav Vivaan Aditya Vihaan Rohan Rohit Vikram Anand Deepak
Manoj Pradeep Rakesh Ashok Arun Kiran Krishna Ravi Sachin Nikhil Siddharth Karan Varun Gaurav Abhishek Akshay Pranav
Ishaan Aryan Dev Priya Anjali Pooja Neha Sneha Divya Kavya Ananya Aditi Shreya Riya Isha Meera Lakshmi Sunita Anita
Geeta Rekha Deepika Swati Nisha Preeti Shalini Aishwarya Saanvi Diya Aanya Kavita Manisha Pallavi Radhika Shweta
Tanvi Vidya Sanjana Asha Venkatesh Srinivas Naveen Praveen Harish Girish Mahesh Dinesh Ganesh Rajiv Sameer Tarun
Mohammed Muhammad Mohamed Mohammad Omar Hassan Hussein Hussain Khalid Yusuf Youssef Ibrahim Mustafa Mahmoud Abdullah
Abdallah Tariq Karim Faisal Hamza Bilal Samir Nabil Walid Rashid Said Saeed Majid Nasser Jamal Fadi Rami Ziad Hani
Imad Adel Amr Fatima Aisha Mariam Maryam Layla Leila Noor Nour Zainab Yasmin Yasmine Salma Huda Rania Hala Samira
Amira Nadia Reem Farah Hiba Asma Soraya Reza Mehdi Hossein Alireza Dariush Kourosh Babak Farid Farhad Behrouz Arash
Kaveh Parviz Shahram Siamak Navid Omid Pouya Sina Ashkan Hamid Mahsa Shirin Parisa Neda Nasrin Azadeh Roya Negar
Ladan Fariba Golnaz Setareh Bahar Elham Yousef Ahmad Hamed Mansour Osama Anwar Jalal Kamal Munir Nizar Wael Ayman
Mehmet Ahmet Huseyin Hasan Ismail Osman Murat Emre Burak Cem Can Deniz Kerem Mert Onur Serkan Tolga Volkan Baris Enes
Furkan Gokhan Hakan Kaan Oguz Ozan Selim Sinan Tuncay Ugur Umut Yasin Ayse Fatma Emine Hatice Zeynep Elif Merve Busra
Esra Ozge Seda Derya Ebru Gizem Ece Defne Asli Pinar Sibel Tugba Yasemin Selin Irmak Cansu Dilara Gamze Sevgi Recep
Santiago Mateo Matias Nicolas Emiliano Joaquin Tomas Agustin Facundo Gonzalo Rodrigo Ricardo Eduardo Guillermo Gustavo
Ramon Raul Ruben Hector Esteban Ignacio Julio Cesar Arturo Alfredo Enrique Emilio Felipe Mauricio Martin Marcelo
Leonardo Thiago Joao Paulo Camila Valeria Mariana Gabriela Daniela Luciana Florencia Martina Catalina Ximena
Guadalupe Fernanda Paola Alejandra Adriana Beatriz Leticia Lorena Marisol Milagros Rocio Silvia Yolanda Juliana
Bruna Renata Vitoria Luana Thais Bianca Gabriel Rafaela Jimena Agustina Josefina Constanza Rosario
Pieter Willem Joost Sander Bram Daan Ruud Sjoerd Maarten Siobhan Niamh Aoife Ciaran Oisin Padraig Saoirse Eoin
Kwame Kofi Chidi Chinedu Oluwaseun Adebayo Tendai Thabo Sipho Amara Nkechi Ngozi Folake Abena
`;

// FU-2: surnames beyond English/European (flag "g"), incl. the second parts of Spanish/Portuguese double surnames.
const GLOBAL_SURNAMES = `
Sato Suzuki Takahashi Tanaka Watanabe Ito Yamamoto Nakamura Kobayashi Kato Yoshida Yamada Sasaki Yamaguchi Matsumoto
Inoue Kimura Hayashi Shimizu Yamazaki Mori Abe Ikeda Hashimoto Ishikawa Ogawa Okada Hasegawa Fujita Goto Kondo Murakami
Endo Aoki Sakamoto Fujii Nishimura Fukuda Ota Miura Okamoto Matsuda Nakagawa Harada Ono Takeda Kaneko Wada Nakano
Zhang Wang Li Liu Chen Yang Huang Zhao Wu Zhou Xu Sun Ma Zhu Hu Guo He Lin Luo Gao Zheng Liang Xie Song Tang Han Feng
Deng Cao Peng Zeng Xiao Tian Dong Pan Yuan Cai Jiang Yu Du Ye Cheng Wei Su Lu Ding Ren Shen Yao Jin Cui Zhong Tan
Kim Lee Park Choi Jung Kang Cho Yoon Jang Lim Shin Seo Kwon Hwang Ahn Song Jeon Hong Yoo Ko Moon Yang Son Baek Heo
Sharma Gupta Singh Kumar Patel Reddy Rao Iyer Nair Mehta Shah Joshi Das Bose Chatterjee Banerjee Mukherjee Agarwal
Verma Mishra Pandey Srivastava Chopra Malhotra Kapoor Bhat Menon Pillai Naidu Desai Kulkarni Deshpande Chaudhary
Yadav Saxena Trivedi Bhatt Sinha Ghosh Dutta Sen Basu Khanna Arora Sethi Iyengar Krishnan Subramanian Venkatesan
Hassan Hussein Ahmed Khalil Haddad Nasser Mansour Saleh Aziz Rahman Hamdan Khoury Aboud Awad Barakat Darwish Farouk
Ghanem Habib Hamad Ibrahim Jaber Kassem Mahmoud Najjar Qasim Sabbagh Shaheen Suleiman Yassin Zaki Hosseini Mohammadi
Rezaei Ahmadi Karimi Jafari Moradi Hashemi Rahimi Sadeghi Ghorbani Bagheri Rostami Tehrani Shirazi Esfahani
Yilmaz Kaya Demir Sahin Celik Yildiz Yildirim Ozturk Aydin Ozdemir Arslan Dogan Kilic Aslan Cetin Kara Koc Kurt
Ozkan Simsek Polat Erdogan Ozcan Korkmaz Cakir Erdem Tekin Gunes Aktas Keskin Acar Uysal Bulut Guler Unal Karaca
Oliveira Souza Pereira Carvalho Ferreira Rodrigues Almeida Gomes Ribeiro Martins Araujo Barbosa Rocha Dias
Nascimento Moreira Cardoso Teixeira Correia Mendes Nunes Soares Vieira Monteiro Pinto Machado Freitas Lopes Marques
Marquez Vega Guerrero Delgado Ortega Navarro Molina Blanco Suarez Rubio Iglesias Nunez Cabrera Pascual Fuentes
Carrasco Aguirre Vidal Sandoval Espinoza Cortes Contreras Figueroa Villanueva Pena Paredes Salinas Valencia
Montoya Ochoa Zamora Velasquez Cordero Rios Acosta Benitez Ibarra Bustamante Quintero Villalobos
Berg Dijk Vries Bosch Meer Jong Graaf Heuvel Linden Visser Smits Mulder Dekker Brouwer Vos Peeters Maes Janssens
Neill Connor Brien Sullivan Donnell Reilly Mcgregor Mcallister Mcdermott Mckenzie Mcintyre Macarthur Macdonald
Mackenzie Maclean Macleod Mensah Boateng Owusu Asante Okafor Okonkwo Adeyemi Oyelaran Nkosi Dlamini Mwangi Kamau
Weller Brennan Kowalczyk Lindqvist Bergstrom Haugen Virtanen Korhonen Nieminen
`;

// Latin forms that are also common words, places or brands: never an anchor for the Title-case pair heuristic.
const LATIN_WEAK = new Set(
  `Mark Will Bill Rose Grace Joy Hope Faith May June April Summer Autumn Jordan Austin Georgia Virginia Carolina Sydney
   Chelsea Florence Victoria Paris Dallas Jack Frank Ray Max Guy Art Pat Sue Rob Dean Chase Hunter Mason Taylor Page
   Crystal Amber Ruby Pearl Jade Holly Ivy Lily Daisy Violet Iris Olive Hazel Dawn Eve Robin Sky Angel Star Ginger Candy
   Sandy Rocky Price King Prince Duke Earl Miles Lincoln Jackson Madison Houston Phoenix Aurora Alexa Siri Nova Luna Stella
   Bella Charlotte Carmen Jean Harper Lucky Christian Brooks Madison Florence Mercedes Roman Vera Lev Mir Slava
   Kim Nika Lada Mila Alisa Zlata Liliya Lilia Rada Dana Vita Ada Lina Mira Nil Tit Yan Ian Mai Maya Rita Luka Ali
   Lola Dina Alma Amir Emir Almaz Bulat Salavat Sultan Islam Marsel Milan Nikon Lavr Luka Muza Avrora Vesna Venera
   Rosa Roza Ida Ira Alla Leo Roy
   Sakura Can Said Dev Ping Hong Gang Chao Fang Tao Ming Kai Mei Lin Hana Julio Santiago Catalina Rosario Guadalupe
   Florencia Deniz Bahar Noor Nour Asha Sina Mina Reem Yuki Minato Taro Hala Amr`
    .split(/\s+/)
    .filter(Boolean),
);

// Surnames that are also common words, places or brands (flag "x"): count only next to a dictionary first name or
// patronymic, never as the dictionary side of the Title-case pair heuristic.
const WEAK_SURNAMES = new Set(
  `Ким Цой Пак Ли Хан Тен Шин Нам Мун Чен Сат Оюн Толстой Толстая Донской Коваль Мельник Бондарь Гончар Кравец Швец Ткач
   Жук Лях Мороз Сирота Гоголь Кузнец Бородай Литвак Гладкий Грач Сокол Волк Заяц Лысый Чёрный Белый Рыбак Соловей Лебедь
   Сорока Кнут Бах Кох Мазур Бандера Королёв Калинин Жуковский Томский Рахмон Львов Серов
   Brown Miller Taylor White Walker Young Wright King Hill Green Baker Hall Carter Turner Parker Cook Cooper Reed Ward Brooks
   Wood James Gray Price Long Ross Bell Butler Fisher Jordan West Cole Ford Marshall Woods Washington Wells Porter Hunter
   Mason Hunt Black Rose Stone Fox Mills Rice Grant Hart Knight Lane Berry Harper Newman Lambert Wolf Koch Klein Braun
   Bruno Costa Doe Lee Chen Kelly Russell Graham Gordon Simpson Holmes Ryan Kennedy Lawrence Michel Durand Gallo Santos
   Silva Cruz Long Payne Fuller Weaver Hudson
   Sun Song Tang Hong Moon Park Long Jung Shin Son Han Tan Pan Ren Das Sen Kara Kurt Vos Berg Mori Ono Abe Jin Ding Dong
   Feng Yang Yuan Pinto Vega Valencia Rios Blanco Guerrero Molina Vidal Kaya Gunes Koc Acar Suzuki Cheng Lin Gao Cao Cai
   Goto Endo Seo Lim Bose Bosch Meer Linden Aydin Yildiz Kang Cho Yoo Ota Sato Jang Ahn Heo Baek Tian Guo Zeng Xie Deng
   Peng Tan Jiang Ye Yu Du Su Lu Ren Shen Yao Cui Zhong Wei Song Pena Dias Rocha Dekker Maes Rao Ma He Hu Xu Wu Li`
    .split(/\s+/)
    .filter(Boolean),
);

// ---------------------------------------------------------------- helpers

const words = (s: string): string[] => s.split(/\s+/).filter(Boolean);

function uniq(xs: Iterable<string>): string[] {
  return [...new Set(xs)];
}

function diminutivesFrom(base: string): string[] {
  const out: string[] = [];
  const last = base.slice(-1);
  const stem = base.slice(0, -1);
  if (last === "а") {
    out.push(`${stem}ка`, `${stem}енька`);
  } else if (last === "я") {
    if (/[аеёиоуыэюя]$/.test(stem)) out.push(`${stem}йка`);
    else out.push(`${stem}ька`, `${stem}ечка`, `${stem}юша`);
  }
  return out.filter((w) => !GENERATED_BLOCKLIST.has(w));
}

const TR: Record<string, string> = {
  а: "a",
  б: "b",
  в: "v",
  г: "g",
  д: "d",
  е: "e",
  ё: "yo",
  ж: "zh",
  з: "z",
  и: "i",
  й: "y",
  к: "k",
  л: "l",
  м: "m",
  н: "n",
  о: "o",
  п: "p",
  р: "r",
  с: "s",
  т: "t",
  у: "u",
  ф: "f",
  х: "kh",
  ц: "ts",
  ч: "ch",
  ш: "sh",
  щ: "shch",
  ъ: "",
  ы: "y",
  ь: "",
  э: "e",
  ю: "yu",
  я: "ya",
};

function translitBase(name: string): string {
  const lower = name.toLowerCase();
  let out = "";
  for (let i = 0; i < lower.length; i++) {
    const ch = lower[i] ?? "";
    // Word-initial е → ye (Yelena); ье → ye.
    if (ch === "е" && (i === 0 || lower[i - 1] === "ь" || lower[i - 1] === "ъ")) out += "ye";
    else out += TR[ch] ?? ch;
  }
  return out;
}

function latinVariants(name: string): string[] {
  const base = translitBase(name);
  const vs = new Set<string>([base]);
  const add = (s: string) => vs.add(s);
  for (const v of [...vs]) {
    add(v.replace(/^ye/, "e"));
    add(v.replace(/iy$/, "y"));
    add(v.replace(/iy$/, "ii"));
    add(v.replace(/ey$/, "ei"));
    add(v.replace(/kh/g, "h"));
    add(v.replace(/ks/g, "x"));
    add(v.replace(/iya$/, "ia"));
    add(v.replace(/ya$/, "ia"));
    add(v.replace(/yo/g, "e"));
    add(v.replace(/^yu/, "ju").replace(/iya$/, "ia"));
  }
  return [...vs].filter((v) => v.length >= 2).map((v) => v.charAt(0).toUpperCase() + v.slice(1));
}

// ---------------------------------------------------------------- build

type Entry = { form: string; flags: string; extra?: string };

// Irregular stems: explicit case forms (fleeting vowels, feminine -ь).
const EXTRA_FORMS: Record<string, string> = {
  Павел: "Павла Павлу Павлом Павле",
  Пётр: "Петра Петру Петром Петре",
  Лев: "Льва Льву Львом Льве",
  Любовь: "Любови Любовью",
  Нинель: "Нинели Нинелью",
  Лавр: "Лавра Лавру Лавром Лавре",
};

function build(): Entry[] {
  const entries = new Map<string, Entry>();
  const put = (form: string, flags: string) => {
    const prev = entries.get(form);
    if (prev) {
      // Merge flags; a form is ambiguous only if every source is ambiguous.
      const merged = new Set([...prev.flags, ...flags]);
      if (!(prev.flags.includes("a") && flags.includes("a"))) merged.delete("a");
      prev.flags = [...merged].sort().join("");
      return;
    }
    const e: Entry = { form, flags };
    const extra = EXTRA_FORMS[form];
    if (extra) e.extra = extra;
    entries.set(form, e);
  };
  const amb = (w: string) => (AMBIGUOUS.has(w) || OTHER_AMBIGUOUS.has(w) ? "a" : "");

  const otherMale = uniq(words(OTHER_MALE));
  const otherFemale = uniq(words(OTHER_FEMALE));
  const male = uniq([...words(MALE), ...otherMale]);
  const female = uniq([...words(FEMALE), ...otherFemale]);
  for (const n of male) put(n, `m${amb(n)}`);
  for (const n of female) put(n, `f${amb(n)}`);
  for (const n of [...otherMale, ...otherFemale]) put(n, `o${amb(n)}`);
  for (const n of words(DIMINUTIVE_M)) put(n, `md${amb(n)}`);
  for (const n of words(DIMINUTIVE_F)) put(n, `fd${amb(n)}`);
  for (const n of words(DIMINUTIVE_U)) put(n, `ud${amb(n)}`);
  for (const n of words(DIMINUTIVE_AMBIGUOUS)) put(n, "fda");
  for (const base of words(DIMINUTIVE_BASES)) {
    const g = entries.get(base)?.flags.includes("m") ? "m" : "f";
    for (const d of diminutivesFrom(base)) put(d, `${g}d${AMBIGUOUS.has(base) ? "a" : ""}`);
  }
  for (const s of uniq([...words(SURNAMES_COMMON), ...words(SURNAMES)])) put(s, "s");
  for (const s of words(OTHER_SURNAMES)) put(s, "os");

  // Latin: every full name and the frequent diminutives; Latin tokens always need a surname next to them.
  const latin = new Set<string>(words(LATIN_EXTRA));
  const fromPlain = new Set<string>();
  const fromAmbiguous = new Set<string>();
  for (const n of [...male, ...female]) {
    for (const v of latinVariants(n)) {
      latin.add(v);
      (AMBIGUOUS.has(n) || OTHER_AMBIGUOUS.has(n) ? fromAmbiguous : fromPlain).add(v);
    }
  }
  const western = new Set(words(WESTERN_FIRST));
  for (const l of latin) if (!entries.has(l)) entries.set(l, { form: l, flags: "l" });
  for (const n of western) put(n, "lw");
  for (const s of words(WESTERN_SURNAMES)) put(s, "sw");
  const global = new Set(words(GLOBAL_FIRST));
  for (const n of global) put(n, "gl");
  for (const s of words(GLOBAL_SURNAMES)) put(s, "gs");

  // Weak forms (common words, places, brands, very short transliterations) are never pair anchors: flag "a".
  for (const e of entries.values()) {
    const weakLatin =
      e.flags.includes("l") &&
      (LATIN_WEAK.has(e.form) ||
        (fromAmbiguous.has(e.form) && !fromPlain.has(e.form)) ||
        (e.form.length <= 3 && !western.has(e.form)));
    const weakSurname = e.flags.includes("s") && (WEAK_SURNAMES.has(e.form) || e.form.length <= 2);
    const add = `${weakLatin && !e.flags.includes("a") ? "a" : ""}${weakSurname ? "x" : ""}`;
    if (add) e.flags = [...e.flags, ...add].sort().join("");
  }

  return [...entries.values()].sort((a, b) => (a.form < b.form ? -1 : a.form > b.form ? 1 : 0));
}

const HEADER = `# names.ru.txt — словарь имён для packages/pii (specs/security/data-boundary.yaml#detectors.kinds.person_name)
# GENERATED by packages/pii/scripts/gen-names.ts — do not edit by hand.
# Provenance: seed lists authored for this repository (general knowledge of Russian anthroponymy); derived forms
# (diminutives, Latin transliterations) generated by heuristics in the script. License: CC0-1.0 (public domain).
# Format: <form>\\t<flags>[\\t<irregular case forms>]
# Flags: m/f/u — gender; d — diminutive; a — ambiguous word (needs surname/patronymic; never a pair anchor); s — surname;
#        l — Latin spelling (needs an adjacent surname); o — Central Asian, Caucasian, Turkic or Siberian origin;
#        w — English/European name; g — Japanese, Chinese, Korean, Indian, Arabic/Persian, Turkish, Latin-American or other
#        name beyond English/European (Latin, ASCII; lookups strip diacritics); x — surname that is also a common word or place (never a pair anchor). Case forms of Cyrillic names are generated at load time.
`;

function main(): void {
  const entries = build();
  const body = entries.map((e) => [e.form, e.flags, ...(e.extra ? [e.extra] : [])].join("\t")).join("\n");
  const names = entries.filter((e) => !e.flags.includes("s")).length;
  const cyrillic = entries.filter((e) => !e.flags.includes("s") && !e.flags.includes("l")).length;
  const surnames = entries.filter((e) => e.flags.includes("s")).length;
  // data-boundary.yaml: ≥ 1500 names incl. diminutives; backlog M0-05: ≥ 300 names and ≥ 300 surnames.
  const has = (e: Entry, a: string, b: string) => e.flags.includes(a) && e.flags.includes(b);
  const other = entries.filter((e) => e.flags.includes("o") && /[mf]/.test(e.flags)).length;
  const otherSur = entries.filter((e) => has(e, "o", "s")).length;
  const west = entries.filter((e) => has(e, "w", "l")).length;
  const westSur = entries.filter((e) => has(e, "w", "s")).length;
  const glob = entries.filter((e) => has(e, "g", "l")).length;
  const globSur = entries.filter((e) => has(e, "g", "s")).length;
  if (names < 1500 || cyrillic < 300 || surnames < 300) {
    throw new Error(`dictionary too small: ${names} names, ${cyrillic} Cyrillic, ${surnames} surnames`);
  }
  // FU-1: ≥ 300 non-Slavic first names, ≥ 200 non-Slavic surnames, ≥ 200 English/European first names and surnames.
  if (other < 300 || otherSur < 200 || west < 200 || westSur < 200) {
    throw new Error(`FU-1 lists too small: o=${other} o-s=${otherSur} w=${west} w-s=${westSur}`);
  }
  // FU-2: ≥ 300 given names and ≥ 200 surnames beyond English/European.
  if (glob < 300 || globSur < 200) throw new Error(`FU-2 lists too small: g=${glob} g-s=${globSur}`);
  writeFileSync(join(ROOT, "data/names.ru.txt"), `${HEADER}${body}\n`);
  const ts = `// GENERATED by scripts/gen-names.ts from data/names.ru.txt — do not edit by hand.\n// Provenance and license: see data/names.ru.txt header (CC0-1.0).\nexport const NAMES_DATA = \`\n${body}\n\`;\n`;
  writeFileSync(join(ROOT, "src/names.data.ts"), ts);
  const count = (f: string) => entries.filter((e) => e.flags.includes(f)).length;
  console.log(
    `names.ru.txt: ${entries.length} entries (${names} names: m=${count("m")} f=${count("f")} d=${count("d")} l=${count("l")}; surnames=${count("s")}; o=${other} o-s=${otherSur} w=${west} w-s=${westSur} g=${glob} g-s=${globSur})`,
  );
}

main();
