// Generates packages/pii/data/names.ru.txt and src/names.data.ts (specs/security/data-boundary.yaml#detectors.kinds.person_name).
//
// Provenance: the seed lists below were compiled for this repository from general knowledge of Russian
// anthroponymy (given names in common use in Russia, including Tatar, Bashkir, Caucasian and Central Asian
// names common in RF, standard hypocoristic forms, and frequent surnames that do not end in a regular
// surname suffix). Personal names are facts and not copyrightable; the seed lists and all derived output are
// dedicated to the public domain (CC0-1.0). Derived entries are generated by heuristics in this script:
// "-ка/-енька/-юша" diminutives and Latin transliterations (BGN/PCGN-like, passport ICAO-like and common
// English spellings). Case forms are NOT stored — they are generated at load time by src/dict.ts.
//
// Run: node packages/pii/scripts/gen-names.ts   (Node 22 strips types natively; no imports from src/ on purpose)

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");

// ---------------------------------------------------------------- seeds (full names)

const MALE = `
Август Авдей Аким Александр Алексей Альберт Алан Амвросий Анатолий Андрей Андриан Антон Аристарх Аркадий Арнольд Арсений
Артём Артемий Артур Архип Афанасий Богдан Болеслав Борис Бронислав Вадим Валентин Валерий Валериан Василий Вацлав Велимир
Вениамин Венедикт Викентий Виктор Виссарион Виталий Влад Владилен Владимир Владислав Владлен Власий Всеволод Всеслав
Вячеслав Гавриил Гаврила Геннадий Георгий Герасим Герман Глеб Гордей Григорий Гурий Давид Даниил Данила Данислав Дементий
Демид Демьян Денис Дмитрий Добрыня Донат Евгений Евграф Евдоким Евстафий Егор Елисей Емельян Еремей Ерофей Ефим Ефрем Ждан
Захар Зиновий Иван Игнат Игнатий Игорь Илларион Иларион Илья Иннокентий Иосиф Ираклий Исаак Исай Капитон Карен Карл Касьян
Ким Кирилл Клим Климент Кондрат Кондратий Константин Корней Кузьма Лаврентий Лавр Лазарь Лев Леон Леонид Леонтий Леопольд
Лука Лукьян Любим Любомир Май Макар Макарий Максим Максимилиан Мартын Марк Матвей Мефодий Милан Мир Мирон Мирослав Митрофан
Михаил Модест Моисей Мстислав Назар Назарий Натан Наум Нестор Никанор Никита Никифор Никодим Николай Никон Нил Олег Олесь
Онисим Орест Осип Остап Павел Панкрат Пантелей Пантелеймон Парфён Пётр Пимен Платон Порфирий Потап Прокопий Прохор
Радомир Радислав Рафаил Родион Роберт Роман Ростислав Рудольф Руслан Савва Савелий Самсон Самуил Святослав Святополк
Севастьян Семён Серафим Сергей Спартак Спиридон Станислав Станимир Степан Тарас Тимофей Тимур Тит Тихомир Тихон Трифон
Трофим Ульян Устин Фадей Фёдор Федот Феликс Феофан Филимон Филипп Фома Фрол Харитон Христиан Эдуард Эмиль Эммануил Эрик
Юлиан Юлий Юрий Юстин Яков Ян Ярополк Ярослав Яромир
Абдулла Азамат Азат Айдар Айрат Алишер Алмаз Амир Анвар Арман Арсен Аслан Ахмед Ахмад Ашот Бахтияр Булат Вазген Гамлет
Гарик Гурам Дамир Данияр Джамал Джамиль Динар Заур Зураб Ибрагим Ильгиз Ильдар Ильнур Ильшат Ильяс Ирек Ислам Исмаил
Казбек Камиль Карим Ленар Магомед Мансур Марат Марсель Мераб Мурат Мухаммед Мухаммад Наиль Нодар Нурлан Отар Раиль Раис
Рамзан Рамиль Рафаэль Рафис Рашид Равиль Радик Ренат Ринат Ришат Рифат Рубен Рустам Рустем Саид Салават Самир Сослан
Султан Тагир Тамерлан Тигран Фанис Фаниль Фарид Хасан Шамиль Шота Эльдар Эльман Юсуф Якуб Артак Вагиф Гейдар Мамед
`;

const FEMALE = `
Аврора Агата Агафья Агния Аграфена Ада Аделина Аксинья Алевтина Александра Алёна Алеся Алина Алиса Алла Альбина Амалия
Анастасия Ангелина Анжела Анжелика Анисья Анна Антонина Анфиса Ариадна Ариана Арина Богдана Валентина Валерия Ванда Варвара
Василина Василиса Венера Вера Вероника Весна Виктория Вилена Виолетта Вита Виталина Виталия Влада Владислава Галина Глафира
Грета Дана Дарина Дарья Диана Дина Доминика Ева Евгения Евдокия Евфросиния Ефросинья Екатерина Елена Елизавета Есения Жанна
Зарина Зинаида Злата Зоряна Зоя Иветта Изабелла Изольда Илона Инга Инесса Инна Ираида Ирина Ирма Капитолина Камила Камилла
Карина Каролина Кира Клавдия Клара Кристина Ксения Лада Лариса Лаура Лейла Леся Лиана Лидия Лилиана Лилия Лина Лолита
Любава Любовь Людмила Майя Маргарита Марианна Марина Мария Марта Марьяна Мелания Мила Милана Милена Милослава Мирослава
Мирра Муза Надежда Наталья Наталия Нелли Ника Нина Нинель Нонна Оксана Олеся Олимпиада Ольга Пелагея Полина Прасковья Рада
Радмила Раиса Регина Рената Римма Роза Розалия Руслана Сабина Сабрина Светлана Серафима Снежана София Софья Станислава
Стелла Стефания Сусанна Таисия Тамара Татьяна Тереза Ульяна Устинья Фаина Феврония Фёкла Эвелина Эдита Элеонора Элина
Эльвира Эльза Эмилия Эмма Эрика Юлиана Юлия Юна Ядвига Яна Ярослава Ясмина
Айгуль Айсылу Алсу Альфия Асель Гузель Гульнара Гульнур Джамиля Диляра Динара Жасмин Зарема Земфира Зульфия Ильмира Ильнара
Камилла Лейсан Ляйсан Луиза Мадина Малика Марьям Наиля Наргиз Патимат Резеда Сания Тамила Фатима Хадижат Эльмира Айлин
`;

// Hypocoristic forms (authored). Gender u = both.
const DIMINUTIVE_M = `
Саша Шура Саня Санёк Лёша Алёша Лёха Толя Толик Андрюша Андрюха Антоша Тоша Аркаша Арсюша Сеня Тёма Боря Вадик Валера Вася
Вова Володя Витя Виталик Владик Славик Гена Гоша Жора Гера Гриша Даня Дениска Дима Димон Митя Егорка Жека Захарка Ваня Ванюша
Игорёк Илюша Илюха Кеша Кирюша Киря Костя Лёня Лёва Макс Максик Миша Мишаня Коля Коленька Никитка Олежка Паша Павлик Петя
Рома Ромка Родя Серёжа Стас Стасик Стёпа Тима Тимоша Федя Эдик Юра Юрочка Яша Ярик Сёма Матвейка Платоша Тиша Тимка Фима
Эрик Тёмка Славка Прохорка Гордейка Богдаша Данилка Вовчик Юрик Женёк Толян Колян Вован Димыч Серёга Лёнчик
`;

const DIMINUTIVE_F = `
Настя Настенька Ася Аня Анюта Анечка Нюра Нюша Аля Алёнка Варя Вика Галя Даша Дашенька Катя Катюша Лена Леночка Лиза Лизонька
Ира Ирочка Иришка Ксюша Лара Лида Лиля Люда Люся Маша Машенька Маруся Мариша Мариночка Надя Наденька Наташа Ната Ниночка
Оля Оленька Олечка Поля Рая Рита Светочка Соня Сонечка Софа Тася Тома Таня Танечка Танюша Уля Юля Юленька Янка Зина Тоня
Клава Фая Эля Верочка Геля Гуля Ксеня Лёля Марго Маня Надюша Оксанка Полинка Сима Стеша Стефа Ульянка Лиса Ксюха Катенька
Галочка Валечка Любаша Настюша Дашуля Машуля Ариша Алинка Кристи Викуля Вероничка Златочка Милочка Сонька Людочка
`;

const DIMINUTIVE_U = "Женя Валя Слава Шура Саша";
const DIMINUTIVE_AMBIGUOUS = "Света Люба";

// Words that are also common nouns, months or place names: detected only together with a surname/patronymic.
const AMBIGUOUS = new Set(
  `Вера Надежда Любовь Роман Лев Мир Слава Май Роза Лилия Виктория Лада Ника Мила Злата Алиса Август Ян Эра Лиана Дана Вита
   Мира Любим Милан Марсель Лавр Никон Ислам Христиан Султан Лука Муза Аврора Олимпиада Весна Венера Жасмин Ким Света Люба
   Рада Мирра Марк Нил Гарик Спартак Донат Ада Марта Юна Стелла Лиса Поля Тома Рая Софа Булат Алмаз Динар Салават Казбек
   Гамлет Тёма Тёмка`
    .split(/\s+/)
    .filter(Boolean),
);

// Generated "-ка" diminutives that coincide with common nouns.
const GENERATED_BLOCKLIST = new Set(
  "Галка Милка Кирка Серёжка Славка Лиска Зорька Ладка Верка Любка Лёвка Витька Ромашка Ленка Ванька Тонька Настька".split(
    " ",
  ),
);

const DIMINUTIVE_BASES = `Саша Маша Даша Паша Таня Катя Оля Коля Юля Лена Света Наташа Женя Лёша Петя Вася Ваня Дима Вова Витя Миша
Настя Ира Надя Галя Валя Люба Аня Соня Лиза Рома Юра Серёжа Гриша Костя Толя Митя Лёня Федя Стёпа Тоня Зина Вера Рая Люда
Варя Поля Ксюша Алёна Вика Рита Слава Тома Уля Гена Боря Лида Аля Ася Сеня Даня Кира`;

// Frequent Russian surnames (masculine form; feminine and case forms are covered by the suffix rules in
// src/detectors/names.ts#SURNAME_SUFFIX_CYR).
const SURNAMES_COMMON = `
Иванов Смирнов Кузнецов Попов Васильев Петров Соколов Михайлов Новиков Фёдоров Морозов Волков Алексеев Лебедев Семёнов
Егоров Павлов Козлов Степанов Николаев Орлов Андреев Макаров Никитин Захаров Зайцев Соловьёв Борисов Яковлев Григорьев
Романов Воробьёв Сергеев Кузьмин Фролов Александров Дмитриев Королёв Гусев Киселёв Ильин Максимов Поляков Сорокин
Виноградов Ковалёв Белов Медведев Антонов Тарасов Жуков Баранов Филиппов Комаров Давыдов Беляев Герасимов Богданов Осипов
Сидоров Матвеев Титов Марков Миронов Крылов Куликов Карпов Власов Мельников Денисов Гаврилов Тихонов Казаков Афанасьев
Данилов Савельев Тимофеев Фомин Чернов Абрамов Мартынов Ефимов Федотов Щербаков Назаров Калинин Исаев Чернышёв Быков
Маслов Родионов Коновалов Лазарев Воронин Климов Филатов Пономарёв Голубев Кудрявцев Прохоров Наумов Потапов Журавлёв
Овчинников Трофимов Леонов Соболев Ермаков Колесников Гончаров Емельянов Никифоров Грачёв Котов Гришин Ефремов Архипов
Громов Кириллов Малышев Панов Моисеев Румянцев Акимов Кондратьев Бирюков Горбунов Анисимов Ерёмин Тихомиров Галкин
Лукьянов Михеев Скворцов Юдин Белоусов Нестеров Симонов Прокофьев Харитонов Князев Цветков Левин Митрофанов Воронов
Аксёнов Софронов Мальцев Логинов Горшков Савин Краснов Майоров Демидов Елисеев Рыбаков Сафонов Плотников Дёмин Хохлов
Фадеев Молчанов Игнатов Литвинов Ершов Ушаков Дементьев Рябов Мухин Калашников Леонтьев Лобанов Кузин Корнилов
Евдокимов Бородин Платонов Некрасов Балашов Бобров Жданов Блинов Игнатьев Коротков Муравьёв Крюков Беляков Богомолов
Дроздов Лавров Зуев Петухов Ларин Никулин Серов Терентьев Зотов Устинов Фокин Самойлов Константинов Сахаров Шишкин
Самсонов Черкасов Чистяков Носов Спиридонов Карасёв Авдеев Воронцов Зверев Владимиров Селезнёв Нечаев Кудряшов Седов
Фирсов Андрианов Панин Головин Терехов Ульянов Шестаков Агеев Никонов Селиванов Баженов Гордеев Кожевников Пахомов
Зимин Костин Широков Филимонов Ларионов Овсянников Сазонов Суворов Нефёдов Любимов Львов Горбачёв Копылов Лукин
Токарев Кулешов Шилов Большаков Панкратов Родин Шаповалов Покровский Бочаров Никольский Маркин Горелов Агафонов Березин
Ермолаев Зубков Куприянов Трифонов Масленников Круглов Третьяков Колосов Рожков Артамонов Шмелёв Лаптев Лапшин Федосеев
Зиновьев Зорин Уткин Столяров Зубов Ткачёв Дорофеев Антипов Завьялов Свиридов Золотарёв Кулаков Мещеряков Макеев
Дьяконов Гуляев Петровский Бондарев Поздняков Панфилов Кочетков Суханов Рыжов Старостин Калмыков Колесов Золотов
Кравцов Субботин Шубин Щукин Лосев Винокуров Лапин Парфёнов Исаков Голованов Коровин Розанов Артёмов Козырев Русаков
Алёшин Крючков Булгаков Кошелев Сычёв Синицын Олейников Кононов Евсеев Калугин Комиссаров Кирсанов Обухов Сапожников
Хабибуллин Галиев Сафин Гарипов Шарипов Валиев Мухаметшин Ахметов Нуриев Зарипов Юсупов Алиев Мамедов Гасанов Магомедов
Абдуллаев Рахимов Каримов Исмаилов Назарбаев Саргсян Петросян Акопян Григорян Оганесян Геворгян Гелашвили Беридзе
Шевченко Бондаренко Коваленко Кравченко Ткаченко Олейник Мельниченко Савченко Руденко Лысенко Марченко Шевчук Коваль
Мельник Бойко Кравчук Полищук Ковальчук Романюк Лукашенко Ковалевский Жуковский Вишневский Новицкий Янковский
`;

// Surnames that do not end in a regular Russian surname suffix (see src/detectors/names.ts#SURNAME_SUFFIX_CYR).
const SURNAMES = `
Ким Цой Пак Ли Хан Тен Шин Югай Огай Когай Нам Мун Чен Толстой Толстая Донской Трубецкой Лановой Коваль Мельник Бондарь Гончар Кравец Швец Ткач Жук Лях
Мороз Бойко Сирота Гоголь Шмидт Миллер Фишер Вебер Шульц Беккер Рихтер Вагнер Гофман Кох Кац Коган Фельдман Розенберг
Гольдман Лифшиц Шапиро Гинзбург Цукерман Эпштейн Кузнец Бородай Литвак Гладкий Грач Сокол Волк Заяц Лысый Чёрный Белый
Рыбак Соловей Шевчик Мазур Бандера Тимошенко Гриценко Олейник Кушнир Павлюк Савчук Марченко Руденко Сорока Демченко
Карпенко Клименко Вакуленко Федоренко Шевченко Ковальчук Мельниченко Ющенко Лебедь Гуревич Кнут Бах Гейнц Клюев
`;

// Common Latin spellings that the transliteration heuristics do not produce.
const LATIN_EXTRA = `
Alexander Alexandra Alex Alexei Alexey Aleksei Sergei Sergey Dmitri Dmitry Dmitriy Nikolai Nikolay Maxim Maksim Pyotr Petr
Fedor Fyodor Semyon Semen Artem Artyom Alyona Alena Ksenia Kseniya Xenia Sofia Sofya Sophia Daria Darya Anastasia Ilia
Ilya Vitaly Vitaliy Valery Valeriy Yuri Yury Yuriy Iurii Evgeny Evgeniy Yevgeny Eugene Evgenia Evgeniya Yevgeniya Ekaterina
Yekaterina Katerina Elena Yelena Helen Elizaveta Yelizaveta Julia Yulia Yuliya Iuliia Natalia Natalya Nataliya Tatiana
Tatyana Tatjana Ludmila Lyudmila Liudmila Larisa Larissa Viktoriya Victoria Veronica Kristina Christina Mariya Maria Marija
Olga Oksana Svetlana Irina Nadezhda Galina Valentina Tamara Zoya Lidia Lidiya Raisa Polina Alina Diana Vera Lyubov Nina Inna
Alla Anna Aleksandr Aleksandra Aleksey Mikhail Michail Andrei Andrey Anton Artur Boris Vadim Viktor Victor Vladimir
Vladislav Vyacheslav Gennady Gennadiy Georgy Georgiy Grigory Grigoriy Denis Egor Yegor Igor Ivan Kirill Konstantin Leonid
Mark Nikita Oleg Pavel Roman Ruslan Stanislav Stepan Timur Timofey Fedor Yaroslav Yakov Anatoly Anatoliy Arkady Arkadiy
Arseny Arseniy Bogdan Daniil Danila Gleb Lev Matvey Makar Platon Savva Semyon Taras Tikhon Zakhar Sasha Masha Dasha Pasha
Katya Misha Dima Vova Kolya Tanya Olya Natasha Lena Sveta Yulya Zhenya Nastya Kostya Seryozha Serezha Lyosha Lesha Vanya
Petya Vasya Ira Nadya Galya Valya Lyuba Anya Sonya Liza Roma Yura Grisha Tolya Mitya Fedya Styopa Tonya Zina Vika Rita Slava
`;

// ---------------------------------------------------------------- helpers

const words = (s: string): string[] => s.split(/\s+/).filter(Boolean);

function uniq(xs: Iterable<string>): string[] {
  return [...new Set(xs)];
}

function diminutivesFrom(base: string): string[] {
  const out: string[] = [];
  const last = base.slice(-1);
  const stem = base.slice(0, -1);
  if (last === "а") {
    out.push(`${stem}ка`, `${stem}енька`);
  } else if (last === "я") {
    if (/[аеёиоуыэюя]$/.test(stem)) out.push(`${stem}йка`);
    else out.push(`${stem}ька`, `${stem}ечка`, `${stem}юша`);
  }
  return out.filter((w) => !GENERATED_BLOCKLIST.has(w));
}

const TR: Record<string, string> = {
  а: "a",
  б: "b",
  в: "v",
  г: "g",
  д: "d",
  е: "e",
  ё: "yo",
  ж: "zh",
  з: "z",
  и: "i",
  й: "y",
  к: "k",
  л: "l",
  м: "m",
  н: "n",
  о: "o",
  п: "p",
  р: "r",
  с: "s",
  т: "t",
  у: "u",
  ф: "f",
  х: "kh",
  ц: "ts",
  ч: "ch",
  ш: "sh",
  щ: "shch",
  ъ: "",
  ы: "y",
  ь: "",
  э: "e",
  ю: "yu",
  я: "ya",
};

function translitBase(name: string): string {
  const lower = name.toLowerCase();
  let out = "";
  for (let i = 0; i < lower.length; i++) {
    const ch = lower[i] ?? "";
    // Word-initial е → ye (Yelena); ье → ye.
    if (ch === "е" && (i === 0 || lower[i - 1] === "ь" || lower[i - 1] === "ъ")) out += "ye";
    else out += TR[ch] ?? ch;
  }
  return out;
}

function latinVariants(name: string): string[] {
  const base = translitBase(name);
  const vs = new Set<string>([base]);
  const add = (s: string) => vs.add(s);
  for (const v of [...vs]) {
    add(v.replace(/^ye/, "e"));
    add(v.replace(/iy$/, "y"));
    add(v.replace(/iy$/, "ii"));
    add(v.replace(/ey$/, "ei"));
    add(v.replace(/kh/g, "h"));
    add(v.replace(/ks/g, "x"));
    add(v.replace(/iya$/, "ia"));
    add(v.replace(/ya$/, "ia"));
    add(v.replace(/yo/g, "e"));
    add(v.replace(/^yu/, "ju").replace(/iya$/, "ia"));
  }
  return [...vs].filter((v) => v.length >= 2).map((v) => v.charAt(0).toUpperCase() + v.slice(1));
}

// ---------------------------------------------------------------- build

type Entry = { form: string; flags: string; extra?: string };

// Irregular stems: explicit case forms (fleeting vowels, feminine -ь).
const EXTRA_FORMS: Record<string, string> = {
  Павел: "Павла Павлу Павлом Павле",
  Пётр: "Петра Петру Петром Петре",
  Лев: "Льва Льву Львом Льве",
  Любовь: "Любови Любовью",
  Нинель: "Нинели Нинелью",
  Лавр: "Лавра Лавру Лавром Лавре",
};

function build(): Entry[] {
  const entries = new Map<string, Entry>();
  const put = (form: string, flags: string) => {
    const prev = entries.get(form);
    if (prev) {
      // Merge flags; a form is ambiguous only if every source is ambiguous.
      const merged = new Set([...prev.flags, ...flags]);
      if (!(prev.flags.includes("a") && flags.includes("a"))) merged.delete("a");
      prev.flags = [...merged].sort().join("");
      return;
    }
    const e: Entry = { form, flags };
    const extra = EXTRA_FORMS[form];
    if (extra) e.extra = extra;
    entries.set(form, e);
  };
  const amb = (w: string) => (AMBIGUOUS.has(w) ? "a" : "");

  const male = uniq(words(MALE));
  const female = uniq(words(FEMALE));
  for (const n of male) put(n, `m${amb(n)}`);
  for (const n of female) put(n, `f${amb(n)}`);
  for (const n of words(DIMINUTIVE_M)) put(n, `md${amb(n)}`);
  for (const n of words(DIMINUTIVE_F)) put(n, `fd${amb(n)}`);
  for (const n of words(DIMINUTIVE_U)) put(n, `ud${amb(n)}`);
  for (const n of words(DIMINUTIVE_AMBIGUOUS)) put(n, "fda");
  for (const base of words(DIMINUTIVE_BASES)) {
    const g = entries.get(base)?.flags.includes("m") ? "m" : "f";
    for (const d of diminutivesFrom(base)) put(d, `${g}d${AMBIGUOUS.has(base) ? "a" : ""}`);
  }
  for (const s of uniq([...words(SURNAMES_COMMON), ...words(SURNAMES)])) put(s, "s");

  // Latin: every full name and the frequent diminutives; Latin tokens always need a surname next to them.
  const latin = new Set<string>(words(LATIN_EXTRA));
  for (const n of [...male, ...female]) for (const v of latinVariants(n)) latin.add(v);
  for (const l of latin) if (!entries.has(l)) entries.set(l, { form: l, flags: "l" });

  return [...entries.values()].sort((a, b) => (a.form < b.form ? -1 : a.form > b.form ? 1 : 0));
}

const HEADER = `# names.ru.txt — словарь имён для packages/pii (specs/security/data-boundary.yaml#detectors.kinds.person_name)
# GENERATED by packages/pii/scripts/gen-names.ts — do not edit by hand.
# Provenance: seed lists authored for this repository (general knowledge of Russian anthroponymy); derived forms
# (diminutives, Latin transliterations) generated by heuristics in the script. License: CC0-1.0 (public domain).
# Format: <form>\\t<flags>[\\t<irregular case forms>]
# Flags: m/f/u — gender; d — diminutive; a — ambiguous word (needs surname/patronymic); s — surname without a regular
#        suffix; l — Latin spelling (needs an adjacent surname). Case forms of Cyrillic names are generated at load time.
`;

function main(): void {
  const entries = build();
  const body = entries.map((e) => [e.form, e.flags, ...(e.extra ? [e.extra] : [])].join("\t")).join("\n");
  const names = entries.filter((e) => !e.flags.includes("s")).length;
  const cyrillic = entries.filter((e) => !e.flags.includes("s") && !e.flags.includes("l")).length;
  const surnames = entries.filter((e) => e.flags.includes("s")).length;
  // data-boundary.yaml: ≥ 1500 names incl. diminutives; backlog M0-05: ≥ 300 names and ≥ 300 surnames.
  if (names < 1500 || cyrillic < 300 || surnames < 300) {
    throw new Error(`dictionary too small: ${names} names, ${cyrillic} Cyrillic, ${surnames} surnames`);
  }
  writeFileSync(join(ROOT, "data/names.ru.txt"), `${HEADER}${body}\n`);
  const ts = `// GENERATED by scripts/gen-names.ts from data/names.ru.txt — do not edit by hand.\n// Provenance and license: see data/names.ru.txt header (CC0-1.0).\nexport const NAMES_DATA = \`\n${body}\n\`;\n`;
  writeFileSync(join(ROOT, "src/names.data.ts"), ts);
  const count = (f: string) => entries.filter((e) => e.flags.includes(f)).length;
  console.log(
    `names.ru.txt: ${entries.length} entries (${names} names: m=${count("m")} f=${count("f")} d=${count("d")} l=${count("l")}; surnames=${count("s")})`,
  );
}

main();
