// Reserved identifiers for entity, field and role names (specs/appspec/ops.yaml#semantic_rules).
// All names become quoted SQL identifiers, so keywords are rejected defensively (readability of
// generated SQL, safety of any unquoted use) rather than because quoting would fail.

/** Columns every table gets automatically (specs/appspec/ops.yaml#migrations.ddl_rules). */
export const SYSTEM_FIELDS = ["id", "created_at", "updated_at", "created_by"] as const;

/** Built-in entity that holds end users of the generated system (target of ownerField refs). */
export const USERS_ENTITY = "users";

/** Postgres hidden system columns: a user column with these names cannot be created. */
const PG_SYSTEM_COLUMNS = ["tableoid", "xmin", "xmax", "cmin", "cmax", "ctid", "oid"];

/** PostgreSQL 16 reserved keywords (incl. "reserved, can be function or type"), Appendix C. */
export const SQL_KEYWORDS = [
  "all",
  "analyse",
  "analyze",
  "and",
  "any",
  "array",
  "as",
  "asc",
  "asymmetric",
  "authorization",
  "binary",
  "both",
  "case",
  "cast",
  "check",
  "collate",
  "collation",
  "column",
  "concurrently",
  "constraint",
  "create",
  "cross",
  "current_catalog",
  "current_date",
  "current_role",
  "current_schema",
  "current_time",
  "current_timestamp",
  "current_user",
  "default",
  "deferrable",
  "desc",
  "distinct",
  "do",
  "else",
  "end",
  "except",
  "false",
  "fetch",
  "for",
  "foreign",
  "freeze",
  "from",
  "full",
  "grant",
  "group",
  "having",
  "ilike",
  "in",
  "initially",
  "inner",
  "intersect",
  "into",
  "is",
  "isnull",
  "join",
  "lateral",
  "leading",
  "left",
  "like",
  "limit",
  "localtime",
  "localtimestamp",
  "natural",
  "not",
  "notnull",
  "null",
  "offset",
  "on",
  "only",
  "or",
  "order",
  "outer",
  "overlaps",
  "placing",
  "primary",
  "references",
  "returning",
  "right",
  "select",
  "session_user",
  "similar",
  "some",
  "symmetric",
  "system_user",
  "table",
  "tablesample",
  "then",
  "to",
  "trailing",
  "true",
  "union",
  "unique",
  "user",
  "using",
  "variadic",
  "verbose",
  "when",
  "where",
  "window",
  "with",
  // DML/DDL verbs: not reserved in Postgres, but confusing as table/column names.
  "insert",
  "update",
  "delete",
  "drop",
  "alter",
  "truncate",
  "values",
  "exists",
  "between",
  "revoke",
  "begin",
  "commit",
  "rollback",
] as const;

/** Names reserved by the platform itself (auth, RLS context, system entity). */
const PLATFORM_NAMES = [USERS_ENTITY, "user", "role", "public"];

export const RESERVED_NAMES: ReadonlySet<string> = new Set<string>([
  ...SYSTEM_FIELDS,
  ...PG_SYSTEM_COLUMNS,
  ...PLATFORM_NAMES,
  ...SQL_KEYWORDS,
]);

export function isReservedName(name: string): boolean {
  return RESERVED_NAMES.has(name) || name.startsWith("pg_");
}
