// Generates TypeScript declarations for a spec's entities (consumed by @wizard/sdk, M0-07).
import type { AppSpec, Entity, Field } from "./schema.js";

function pascal(name: string): string {
  return name
    .split("_")
    .filter(Boolean)
    .map((p) => p[0]?.toUpperCase() + p.slice(1))
    .join("");
}

function tsType(field: Field): string {
  switch (field.type) {
    case "int":
    case "decimal":
    case "money":
      return "number";
    case "bool":
      return "boolean";
    case "json":
      return "unknown";
    case "enum":
      return (field.enum ?? []).map((o) => JSON.stringify(o.value)).join(" | ") || "string";
    case "ref":
      return "Id";
    default:
      return "string";
  }
}

function doc(label: string): string {
  return `/** ${label.replace(/\*\//g, "*\\/")} */`;
}

function entityDecl(entity: Entity, typeName: string): string {
  const row = entity.fields.map((f) => `  ${doc(f.label)}\n  ${f.name}: ${tsType(f)}${f.required ? "" : " | null"};`);
  const input = entity.fields.map((f) => {
    const optional = !f.required || f.default !== undefined;
    return `  ${f.name}${optional ? "?" : ""}: ${tsType(f)}${f.required ? "" : " | null"};`;
  });
  return [
    `${doc(entity.label)}`,
    `export interface ${typeName} extends SystemFields {`,
    ...row,
    "}",
    `export interface ${typeName}Input {`,
    ...input,
    "}",
  ].join("\n");
}

/** Returns a self-contained .d.ts source: Row/Input interface per entity, `DataModel` map, role names. */
export function generateTypes(spec: AppSpec): string {
  const used = new Set<string>(["Id", "SystemFields", "DataModel", "EntityName", "RoleName"]);
  const names = new Map<string, string>();
  for (const e of spec.entities) {
    let n = pascal(e.name);
    for (let i = 2; used.has(n) || used.has(`${n}Input`); i++) n = `${pascal(e.name)}${i}`;
    used.add(n);
    used.add(`${n}Input`);
    names.set(e.name, n);
  }
  const lines = [
    "// Generated by @wizard/appspec generateTypes(). Do not edit.",
    "export type Id = string;",
    "export interface SystemFields {",
    "  id: Id;",
    "  created_at: string;",
    "  updated_at: string | null;",
    "  created_by: Id | null;",
    "}",
    ...spec.entities.map((e) => entityDecl(e, names.get(e.name) as string)),
    "export interface DataModel {",
    ...spec.entities.map((e) => {
      const n = names.get(e.name) as string;
      return `  ${e.name}: { row: ${n}; input: ${n}Input };`;
    }),
    "}",
    "export type EntityName = keyof DataModel;",
    `export type RoleName = ${spec.roles.map((r) => JSON.stringify(r.name)).join(" | ") || "never"};`,
    "",
  ];
  return lines.join("\n");
}
