// M0 tables of specs/platform/db.yaml (milestone M0) and the deployments view. Forward-only.
import { type Kysely, sql } from "kysely";

const STATEMENTS = [
  `CREATE SCHEMA IF NOT EXISTS platform`,
  `CREATE TABLE platform.users (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email text NOT NULL CHECK (email = lower(email)),
    name text,
    is_staff boolean NOT NULL DEFAULT false,
    totp_secret_ref text,
    mfa_enrolled_at timestamptz,
    deleted_at timestamptz,
    pd_consent_at timestamptz,
    offer_accepted_at timestamptz,
    offer_version text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_email_key UNIQUE (email)
  )`,
  `CREATE TABLE platform.orgs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name text NOT NULL CHECK (length(name) BETWEEN 1 AND 120),
    plan text NOT NULL DEFAULT 'free' CHECK (plan IN ('free','start','business')),
    ru_only boolean NOT NULL DEFAULT false,
    require_founder_review boolean NOT NULL DEFAULT true,
    passport_collection_allowed boolean NOT NULL DEFAULT false,
    suspended_at timestamptz,
    region_code text CHECK (region_code ~ '^[0-9]{2}$'),
    t1_restricted boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE platform.memberships (
    org_id uuid NOT NULL REFERENCES platform.orgs ON DELETE CASCADE,
    user_id uuid NOT NULL REFERENCES platform.users ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('owner','editor','viewer')),
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (org_id, user_id)
  )`,
  `CREATE INDEX memberships_user_id_idx ON platform.memberships (user_id)`,
  `CREATE TABLE platform.systems (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL REFERENCES platform.orgs,
    slug text NOT NULL CHECK (slug ~ '^[a-z][a-z0-9-]{1,30}[a-z0-9]$' AND position('--' in slug) = 0),
    schema_key text NOT NULL CHECK (schema_key ~ '^[a-z0-9]{12}$'),
    name text NOT NULL,
    stage text NOT NULL DEFAULT 'interview' CHECK (stage IN ('interview','card','building','ready','failed')),
    card jsonb,
    card_version integer NOT NULL DEFAULT 0,
    card_approved_version integer,
    pending_questions jsonb NOT NULL DEFAULT '[]',
    draft_revision integer NOT NULL DEFAULT 0,
    preview_revision integer,
    prod_revision integer,
    schema_hwm_revision integer,
    shard_id text,
    suspended_at timestamptz,
    draft_data_purged_at timestamptz,
    last_activity_at timestamptz NOT NULL DEFAULT now(),
    created_by uuid NOT NULL REFERENCES platform.users,
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT systems_slug_key UNIQUE (slug),
    CONSTRAINT systems_schema_key_key UNIQUE (schema_key)
  )`,
  `CREATE INDEX systems_org_created_idx ON platform.systems (org_id, created_at DESC) WHERE deleted_at IS NULL`,
  `CREATE TABLE platform.runs (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL REFERENCES platform.orgs,
    system_id uuid REFERENCES platform.systems,
    kind text NOT NULL CHECK (kind IN ('interview_turn','build','publish','rollback','import_table','retention','nightly_eval','export')),
    mode text CHECK (mode IN ('create','change','fix','point_edit')),
    status text NOT NULL DEFAULT 'queued' CHECK (status IN ('queued','waiting_lock','running','needs_input','succeeded','failed','cancelled')),
    current_step text,
    input jsonb NOT NULL DEFAULT '{}',
    pending_input jsonb,
    card_version integer,
    credits_estimate_milli bigint,
    credits_cap_milli bigint,
    credits_used_milli bigint NOT NULL DEFAULT 0,
    base_revision integer,
    result_revision integer,
    failure_code text,
    failure_message_ru text,
    cancel_requested_at timestamptz,
    started_by uuid REFERENCES platform.users,
    dbos_workflow_id text,
    heartbeat_at timestamptz,
    started_at timestamptz,
    finished_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT runs_dbos_workflow_id_key UNIQUE (dbos_workflow_id)
  )`,
  `CREATE INDEX runs_system_created_idx ON platform.runs (system_id, created_at DESC)`,
  `CREATE INDEX runs_active_status_idx ON platform.runs (status) WHERE status IN ('queued','waiting_lock','running','needs_input')`,
  `CREATE TABLE platform.messages (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    system_id uuid NOT NULL REFERENCES platform.systems ON DELETE CASCADE,
    seq integer NOT NULL,
    role text NOT NULL CHECK (role IN ('user','assistant','system')),
    kind text NOT NULL CHECK (kind IN ('text','questions','answers','card','run_report','notice')),
    text text,
    payload jsonb,
    run_id uuid,
    author_user_id uuid REFERENCES platform.users,
    created_at timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT messages_system_seq_key UNIQUE (system_id, seq)
  )`,
  `CREATE TABLE platform.revisions (
    system_id uuid NOT NULL REFERENCES platform.systems ON DELETE CASCADE,
    version integer NOT NULL CHECK (version >= 1),
    parent_version integer,
    kind text NOT NULL CHECK (kind IN ('ops','files','style','revert','compliance')),
    author text NOT NULL CHECK (author IN ('user','agent','system')),
    author_user_id uuid REFERENCES platform.users,
    run_id uuid REFERENCES platform.runs,
    spec jsonb NOT NULL,
    ops jsonb NOT NULL DEFAULT '[]',
    files_manifest_sha text NOT NULL,
    bundle_key text,
    g0_passed boolean,
    idempotency_key text,
    summary_ru text,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (system_id, version),
    FOREIGN KEY (system_id, parent_version) REFERENCES platform.revisions (system_id, version)
  )`,
  `CREATE UNIQUE INDEX revisions_idempotency_key_idx ON platform.revisions (system_id, idempotency_key) WHERE idempotency_key IS NOT NULL`,
  `CREATE INDEX revisions_run_id_idx ON platform.revisions (run_id)`,
  `CREATE TABLE platform.files (
    sha256 text PRIMARY KEY CHECK (sha256 ~ '^[0-9a-f]{64}$'),
    size bigint NOT NULL CHECK (size >= 0 AND size <= 5242880),
    content_type text NOT NULL,
    storage_key text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE platform.run_events (
    run_id uuid NOT NULL REFERENCES platform.runs ON DELETE CASCADE,
    seq integer NOT NULL CHECK (seq >= 1),
    type text NOT NULL,
    payload jsonb NOT NULL,
    ts timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, seq)
  )`,
  `CREATE TABLE platform.gate_reports (
    run_id uuid NOT NULL REFERENCES platform.runs ON DELETE CASCADE,
    system_id uuid NOT NULL REFERENCES platform.systems ON DELETE CASCADE,
    revision integer NOT NULL,
    level text NOT NULL CHECK (level IN ('G0','G1','G2')),
    passed boolean NOT NULL,
    report jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (run_id, level, revision)
  )`,
  `CREATE INDEX gate_reports_system_level_idx ON platform.gate_reports (system_id, level, revision DESC)`,
  `CREATE TABLE platform.llm_calls (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id uuid NOT NULL REFERENCES platform.orgs,
    system_id uuid,
    run_id uuid REFERENCES platform.runs,
    step text,
    call_type text NOT NULL,
    agent_role text,
    tier text NOT NULL CHECK (tier IN ('T0','T1')),
    provider text NOT NULL,
    model_id text NOT NULL,
    attempt smallint NOT NULL DEFAULT 1,
    status text NOT NULL CHECK (status IN ('ok','error','timeout','circuit_open','aborted')),
    error_code text,
    route_reason text NOT NULL CHECK (route_reason IN ('policy_ru_only','policy_region_restricted','callType_forbidden_T1','pii_high_risk','pii_detected_interview','pii_hint','default_T1','default_T0','fallback_circuit_open','fallback_error')),
    fallback_from text,
    policy_version text NOT NULL,
    scrubbed boolean NOT NULL,
    pii_categories_count jsonb NOT NULL DEFAULT '{}',
    input_tokens integer NOT NULL DEFAULT 0,
    cached_tokens integer NOT NULL DEFAULT 0,
    output_tokens integer NOT NULL DEFAULT 0,
    tool_calls integer NOT NULL DEFAULT 0,
    latency_ms integer,
    ttft_ms integer,
    cost_rub numeric(12,4) NOT NULL DEFAULT 0,
    credits_milli bigint NOT NULL DEFAULT 0,
    billable boolean NOT NULL DEFAULT true,
    mode text NOT NULL CHECK (mode IN ('live','fixture','record')),
    request_hash text,
    created_at timestamptz NOT NULL DEFAULT now(),
    CHECK (tier = 'T0' OR scrubbed)
  )`,
  `CREATE INDEX llm_calls_run_id_idx ON platform.llm_calls (run_id)`,
  `CREATE INDEX llm_calls_org_created_idx ON platform.llm_calls (org_id, created_at)`,
  `CREATE INDEX llm_calls_tier_type_created_idx ON platform.llm_calls (tier, call_type, created_at)`,
  `CREATE TABLE platform.locks (
    system_id uuid PRIMARY KEY REFERENCES platform.systems ON DELETE CASCADE,
    run_id uuid NOT NULL REFERENCES platform.runs,
    holder_user_id uuid REFERENCES platform.users,
    acquired_at timestamptz NOT NULL DEFAULT now(),
    lease_until timestamptz NOT NULL
  )`,
  // M0: draft rows only; prod rows (publications) arrive with M1.
  `CREATE VIEW platform.deployments AS
    SELECT s.schema_key AS system_id,
           s.slug,
           'draft'::text AS env,
           s.preview_revision AS revision,
           encode(sha256(convert_to(r.spec::text, 'UTF8')), 'hex') AS spec_hash,
           r.bundle_key,
           r.created_at AS published_at,
           (s.suspended_at IS NOT NULL) AS suspended,
           jsonb_build_object('phoneOtp', o.plan IN ('start','business')) AS features
      FROM platform.systems s
      JOIN platform.orgs o ON o.id = s.org_id
      JOIN platform.revisions r ON r.system_id = s.id AND r.version = s.preview_revision
     WHERE s.preview_revision IS NOT NULL AND s.deleted_at IS NULL`,
];

export async function up(db: Kysely<unknown>): Promise<void> {
  await sql`SET LOCAL lock_timeout = '3s'`.execute(db);
  for (const stmt of STATEMENTS) await sql.raw(stmt).execute(db);
}
