// gates.yaml#report.rules: every G0 check has a positive and a negative fixture in test/fixtures/<checkId>/
// (generated by scripts/gen-fixtures.mjs from the forum baseline); each fixture gives the expected verdict.
import { mkdtempSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { AppSpec } from "@wizard/appspec";
import { afterAll, describe, expect, test } from "vitest";
// @ts-expect-error — plain ESM script without types
import { FIXTURES_DIR, fixtureCases, writeFixtures } from "../scripts/gen-fixtures.mjs";
import { G0_CHECKS, runG0 } from "../src/index.js";
import { connect, forumCtx, forumFiles, loadForum } from "./helpers.js";

type Patch = { op: "set" | "push" | "remove"; path: string; value?: unknown };
type Generated = { prefix: string; repeat: string; count: number; suffix: string };
interface FixtureCase {
  check: string;
  expect: "pass" | "fail" | "warn";
  description: string;
  spec?: Patch[];
  files?: Record<string, string | null | Generated>;
  prevSpec?: null | "forum" | Patch[];
  env?: "draft" | "prod";
  milestone?: string;
  match?: string;
}

const db = connect();
afterAll(() => db.end());

function applyPatches(spec: AppSpec, patches: Patch[] = []): AppSpec {
  const root = structuredClone(spec) as unknown as Record<string, unknown>;
  for (const p of patches) {
    const segs = p.path
      .split("/")
      .slice(1)
      .map((s) => s.replace(/~1/g, "/").replace(/~0/g, "~"));
    const last = segs.pop() as string;
    let cur: Record<string, unknown> | unknown[] = root;
    for (const s of segs) cur = (cur as Record<string, unknown>)[s] as Record<string, unknown>;
    if (p.op === "set") (cur as Record<string, unknown>)[last] = p.value;
    else if (p.op === "push") ((cur as Record<string, unknown>)[last] as unknown[]).push(p.value);
    else if (Array.isArray(cur)) cur.splice(Number(last), 1);
    else delete cur[last];
  }
  return root as unknown as AppSpec;
}

function materialize(c: FixtureCase) {
  const files = forumFiles();
  for (const [p, v] of Object.entries(c.files ?? {})) {
    if (v === null) files.delete(p);
    else if (typeof v === "string") files.set(p, v);
    else files.set(p, `${v.prefix}${v.repeat.repeat(v.count)}${v.suffix}`);
  }
  const prevSpec =
    c.prevSpec === "forum"
      ? loadForum()
      : Array.isArray(c.prevSpec)
        ? applyPatches(loadForum(), c.prevSpec)
        : null;
  return forumCtx(db, {
    spec: applyPatches(loadForum(), c.spec),
    files,
    prevSpec,
    env: c.env ?? "draft",
    milestone: c.milestone ?? "M0",
  });
}

const onDisk = (): Map<string, FixtureCase> => {
  const out = new Map<string, FixtureCase>();
  for (const check of readdirSync(FIXTURES_DIR)) {
    for (const f of readdirSync(join(FIXTURES_DIR, check))) {
      out.set(`${check}/${f}`, JSON.parse(readFileSync(join(FIXTURES_DIR, check, f), "utf8")) as FixtureCase);
    }
  }
  return out;
};

describe("fixtures", () => {
  test("are up to date with scripts/gen-fixtures.mjs", () => {
    const dir = mkdtempSync(join(tmpdir(), "gates-fixtures-"));
    try {
      writeFixtures(dir);
      const fresh = new Map<string, string>();
      for (const check of readdirSync(dir)) {
        for (const f of readdirSync(join(dir, check)))
          fresh.set(`${check}/${f}`, readFileSync(join(dir, check, f), "utf8"));
      }
      const current = new Map<string, string>();
      for (const check of readdirSync(FIXTURES_DIR)) {
        for (const f of readdirSync(join(FIXTURES_DIR, check))) {
          current.set(`${check}/${f}`, readFileSync(join(FIXTURES_DIR, check, f), "utf8"));
        }
      }
      expect([...current.keys()].sort()).toEqual([...fresh.keys()].sort());
      for (const [k, v] of fresh) expect(current.get(k), k).toBe(v);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test("every M0 check (blocker, and warning without since) has a positive and a negative fixture", () => {
    const cases = [...onDisk().values()];
    for (const def of G0_CHECKS.filter((d) => !d.since)) {
      const mine = cases.filter((c) => c.check === def.id);
      expect(
        mine.some((c) => c.expect === "pass"),
        `${def.id} pass`,
      ).toBe(true);
      expect(
        mine.some((c) => c.expect !== "pass"),
        `${def.id} negative`,
      ).toBe(true);
    }
  });

  const all = (fixtureCases() as { check: string; name: string; case: FixtureCase }[]).map(
    (c) => [`${c.check}/${c.name}`, c.case] as const,
  );
  test.each(all)("%s", async (_name, c) => {
    const report = await runG0(materialize(c), { only: [c.check] });
    const mine = report.checks.filter((x) => x.id === c.check);
    expect(mine.length).toBeGreaterThan(0);
    const detail = JSON.stringify(mine, null, 1).slice(0, 2000);
    if (c.expect === "pass") {
      expect(
        mine.every((x) => x.status === "pass"),
        detail,
      ).toBe(true);
      return;
    }
    const bad = mine.filter((x) => x.status === c.expect);
    expect(bad.length, detail).toBeGreaterThan(0);
    if (c.expect === "warn")
      expect(
        mine.some((x) => x.status === "fail"),
        detail,
      ).toBe(false);
    if (c.match) {
      const m = c.match;
      expect(
        bad.some((x) => `${x.message_ru} ${x.evidence ?? ""}`.includes(m)),
        detail,
      ).toBe(true);
    }
  });
});
