// V3-14: the similarity of site fingerprints and the verdict of the template gate, on fingerprints generated by code
// (a seeded generator of sections, shapes and hashes): token and sequence alignment, shapes, page and site scores
// (pages matched by route, the home page counting twice), the structure-only mode with its own threshold, and the
// verdict — near-duplicates of a recent site are over TEMPLATE_THRESHOLD, different sites of the niche are not.
import { describe, expect, test } from "vitest";
import {
  alignment,
  DOM_BASELINE,
  HOME_WEIGHT,
  type PageView,
  pageSimilarity,
  type SectionShape,
  type SectionToken,
  type SiteFingerprint,
  sectionToken,
  shapeSimilarity,
  siteSimilarity,
  siteStructure,
  TEMPLATE_STRUCTURE_THRESHOLD,
  TEMPLATE_THRESHOLD,
  type TemplateMemoryItem,
  templateVerdict,
  thresholdOf,
  tokenSimilarity,
} from "../src/template/index.js";

const rng = (seed: number) => {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), a | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
};

const TYPES = ["header", "hero", "services", "about", "testimonials", "faq", "form", "footer"] as const;
const LAYOUTS = ["split", "centered", "grid", "list", "band", "columns"] as const;
const tok = (type: string, variant: string, layout = "split"): SectionToken => ({ type, layout, variant });

/** A random 64-bit hash; `flip` bits of `base` flipped instead when given. */
function hash(r: () => number, base?: string, flip = 0): string {
  if (!base) return Array.from({ length: 16 }, () => Math.floor(r() * 16).toString(16)).join("");
  const bits = [...base].flatMap((c) => [...Number.parseInt(c, 16).toString(2).padStart(4, "0")].map(Number));
  const idx = new Set<number>();
  while (idx.size < flip) idx.add(Math.floor(r() * 64));
  for (const i of idx) bits[i] = 1 - (bits[i] as number);
  let out = "";
  for (let i = 0; i < 64; i += 4) out += Number.parseInt(bits.slice(i, i + 4).join(""), 2).toString(16);
  return out;
}

function shape(r: () => number): SectionShape {
  return {
    h: Math.round((0.2 + r() * 1.6) * 10) / 10,
    depth: 3 + Math.floor(r() * 8),
    cols: 1 + Math.floor(r() * 4),
    media: Math.floor(r() * 4),
    text: 1 + Math.floor(r() * 14),
    controls: Math.floor(r() * 6),
    center: r() < 0.5 ? 0 : 1,
  };
}

/** A shape nudged as other texts would (height ±10 %, a text block more or less). */
const nudge = (s: SectionShape, r: () => number): SectionShape => ({
  ...s,
  h: Math.round(s.h * (0.9 + r() * 0.2) * 10) / 10,
  text: Math.max(1, s.text + Math.round(r() * 2 - 1)),
});

interface Gen {
  variants: string[];
  layouts: string[];
  shapes: SectionShape[];
  hashes: string[];
}

function generate(seed: number): Gen {
  const r = rng(seed);
  return {
    variants: TYPES.map(() => `v${Math.floor(r() * 8)}`),
    layouts: TYPES.map(() => LAYOUTS[Math.floor(r() * LAYOUTS.length)] as string),
    shapes: TYPES.map(() => shape(r)),
    hashes: Array.from({ length: 4 }, () => hash(r)),
  };
}

function site(g: Gen, o: { views?: boolean; route?: string } = {}): SiteFingerprint {
  const view = (k: number): PageView => ({
    shapes: g.shapes,
    first: { p: g.hashes[k] as string, d: g.hashes[k + 1] as string },
    full: { p: g.hashes[(k + 2) % 4] as string, d: g.hashes[(k + 3) % 4] as string },
  });
  return {
    version: 1,
    pages: [
      {
        route: o.route ?? "/",
        sections: TYPES.map((t, i) => tok(t, g.variants[i] as string, g.layouts[i] as string)),
        ...(o.views === false ? {} : { views: { "390": view(0), "1440": view(1) } }),
      },
    ],
  };
}

/** The same sections and variants; shapes nudged, hashes with a few flipped bits (other texts and colours). */
function nearCopy(g: Gen, seed: number): Gen {
  const r = rng(seed);
  return {
    ...g,
    shapes: g.shapes.map((s) => nudge(s, r)),
    hashes: g.hashes.map((h) => hash(r, h, 3 + Math.floor(r() * 6))),
  };
}

/** Every section in another variant and layout; own shapes and hashes. */
function different(g: Gen, seed: number): Gen {
  const other = generate(seed);
  return {
    ...other,
    variants: g.variants.map((v, i) => `${v}x${i}`),
    layouts: g.layouts.map((l) => LAYOUTS[(LAYOUTS.indexOf(l as never) + 1) % LAYOUTS.length] as string),
  };
}

describe("tokens, sequences and shapes", () => {
  test("token similarity: same pattern 1, same layout family 0.6, same type 0.3, signature 0.3, other type 0", () => {
    expect(tokenSimilarity(tok("hero", "split"), tok("hero", "split"))).toBe(1);
    expect(tokenSimilarity(tok("hero", "a", "split"), tok("hero", "b", "split"))).toBe(0.6);
    expect(tokenSimilarity(tok("hero", "a", "split"), tok("hero", "b", "centered"))).toBe(0.3);
    expect(tokenSimilarity(tok("hero", "a", ""), tok("hero", "b", ""))).toBe(0.3);
    expect(tokenSimilarity(tok("hero", "a"), tok("faq", "a"))).toBe(0);
    const sig = sectionToken({ type: "signature", pattern: "signature" });
    expect(sig).toEqual({ type: "signature", layout: "signature", variant: "" });
    expect(tokenSimilarity(sig, sig)).toBe(0.3);
  });

  test("tokens from the site model: the lookup's layout and variant; outside the library <type>-<variant>", () => {
    const lookup = (id: string) =>
      id === "hero-split" ? { sectionType: "hero", layout: "split", variant: "split" } : undefined;
    const s = siteStructure(
      {
        pages: [
          {
            route: "/",
            sections: [
              { type: "hero", pattern: "hero-split" },
              { type: "faq", pattern: "faq-accordion" },
              { type: "signature", pattern: "signature" },
            ],
          },
        ],
      },
      lookup,
    );
    expect(s.pages[0]?.sections).toEqual([
      { type: "hero", layout: "split", variant: "split" },
      { type: "faq", layout: "", variant: "accordion" },
      { type: "signature", layout: "signature", variant: "" },
    ]);
    expect(s.pages[0]?.views).toBeUndefined();
  });

  test("alignment: the best non-crossing matching over the longer length", () => {
    const eq = (a: string, b: string) => (a === b ? 1 : 0);
    expect(alignment(["a", "b", "c"], ["a", "b", "c"], eq)).toBe(1);
    expect(alignment(["a", "b", "c"], ["a", "x", "b", "c"], eq)).toBe(0.75);
    expect(alignment(["a", "b", "c"], ["c", "b", "a"], eq)).toBeCloseTo(1 / 3, 9);
    expect(alignment([], [], eq)).toBe(1);
    expect(alignment(["a"], [], eq)).toBe(0);
  });

  test("shapes: the same shape is 1, a nudged one stays high, an unrelated one is lower", () => {
    const r = rng(5);
    const a = shape(r);
    expect(shapeSimilarity(a, a)).toBe(1);
    expect(shapeSimilarity(a, nudge(a, r))).toBeGreaterThan(0.9);
    const b: SectionShape = {
      h: a.h * 3 + 1,
      depth: a.depth + 6,
      cols: a.cols + 2,
      media: a.media + 3,
      text: a.text * 4,
      controls: a.controls + 8,
      center: a.center ? 0 : 1,
    };
    expect(shapeSimilarity(a, b)).toBeLessThan(0.4);
  });
});

describe("page and site similarity", () => {
  test("a page without views is compared by structure; with views on both sides by all three components", () => {
    const g = generate(1);
    const bare = site(g, { views: false }).pages[0];
    const full = site(g).pages[0];
    if (!bare || !full) throw new Error("no page");
    expect(pageSimilarity(bare, full)).toEqual({ score: 1, structure: 1, dom: null, visual: null });
    const same = pageSimilarity(full, full);
    expect(same).toEqual({ score: 1, structure: 1, dom: 1, visual: 1 });
    // The DOM component counts from its baseline: unrelated shapes give 0, not ≈ 0.5.
    const other = site(different(g, 99)).pages[0];
    if (!other) throw new Error("no page");
    expect(pageSimilarity(full, other).dom).toBeLessThan(1 - DOM_BASELINE);
  });

  test("pages are matched by route; the home page counts twice; a missing page scores 0", () => {
    const g = generate(2);
    const home = site(g).pages[0];
    if (!home) throw new Error("no page");
    const other = { ...home, route: "/prices" };
    const a: SiteFingerprint = { version: 1, pages: [home, other] };
    const onlyHome: SiteFingerprint = { version: 1, pages: [home] };
    const s = siteSimilarity(a, onlyHome);
    expect(s.score).toBeCloseTo(HOME_WEIGHT / (HOME_WEIGHT + 1), 9);
    expect(s.pages.map((p) => [p.route, p.similarity?.score ?? null])).toEqual([
      ["/", 1],
      ["/prices", null],
    ]);
    // Not symmetric: the smaller site is entirely a copy of the bigger one.
    expect(siteSimilarity(onlyHome, a).score).toBe(1);
    expect(siteSimilarity({ version: 1, pages: [] }, a).score).toBe(0);
  });
});

describe("templateVerdict on generated fingerprints", () => {
  const SEEDS = [3, 7, 11, 19, 23, 31];

  test("near-duplicates are over TEMPLATE_THRESHOLD, different sites of the niche are not (with room on both sides)", () => {
    const near: number[] = [];
    const diff: number[] = [];
    for (const seed of SEEDS) {
      const g = generate(seed);
      near.push(siteSimilarity(site(nearCopy(g, seed + 100)), site(g)).score);
      diff.push(siteSimilarity(site(different(g, seed + 200)), site(g)).score);
    }
    expect(Math.min(...near)).toBeGreaterThanOrEqual(TEMPLATE_THRESHOLD + 0.1);
    expect(Math.max(...diff)).toBeLessThan(TEMPLATE_THRESHOLD - 0.2);
  });

  test("structure only (no browser on one side): its own threshold — 1 of 8 sections changed is over, 2 are not", () => {
    const g = generate(41);
    const changed = (n: number): Gen => ({
      ...g,
      variants: g.variants.map((v, i) => (i < n ? `${v}z` : v)),
      layouts: g.layouts.map((l, i) => (i < n ? `${l}z` : l)),
    });
    const one = siteSimilarity(site(changed(1), { views: false }), site(g));
    const two = siteSimilarity(site(changed(2), { views: false }), site(g));
    expect(one.mode).toBe("structure");
    expect(one.score).toBeCloseTo((7 + 0.3) / 8, 9);
    expect(two.score).toBeCloseTo((6 + 0.6) / 8, 9);
    expect(thresholdOf("structure")).toBe(TEMPLATE_STRUCTURE_THRESHOLD);
    expect(thresholdOf("full")).toBe(TEMPLATE_THRESHOLD);
    const memory: TemplateMemoryItem[] = [{ id: "sys-old", archetype: "swiss", fingerprint: site(g) }];
    expect(templateVerdict(site(changed(1), { views: false }), memory).over).toBe(true);
    expect(templateVerdict(site(changed(2), { views: false }), memory).over).toBe(false);
  });

  test("the verdict lists the matches most similar first, the nearest even when nothing matches", () => {
    const g = generate(53);
    const memory: TemplateMemoryItem[] = [
      { id: "far", archetype: "swiss", fingerprint: site(different(g, 1)) },
      { id: "copy", archetype: "calm_medical", fingerprint: site(nearCopy(g, 2)) },
      { id: "closer", archetype: "editorial", fingerprint: site(nearCopy(g, 3)) },
    ];
    const v = templateVerdict(site(g), memory);
    expect(v.over).toBe(true);
    expect(v.matches.map((m) => m.id).sort()).toEqual(["closer", "copy"]);
    expect(v.matches[0]?.score).toBeGreaterThanOrEqual(v.matches[1]?.score ?? 1);
    expect(v.nearest).toEqual(v.matches[0]);
    const none = templateVerdict(site(g), [memory[0] as TemplateMemoryItem]);
    expect(none.over).toBe(false);
    expect(none.nearest?.id).toBe("far");
    expect(templateVerdict(site(g), [])).toEqual({ over: false, nearest: null, matches: [] });
    // A stricter threshold of the caller applies.
    expect(templateVerdict(site(g), memory, { threshold: 0.999 }).over).toBe(false);
  });
});
